// 一年级数学内容包的拼音：键与 i18n.ts 的中文词条一致，每条与模板里的汉字逐字对齐
// （占位符、数字、标点、emoji 不占位）。一 / 不 按实际读音标变调，个 / 什么 / 认识等按课本习惯标轻声。
// 有测试保证每个中文词条都有拼音、音节数与汉字数相等。
import { registerPinyin } from '@/engine/i18n'
import { CN_PINYIN } from './cnum'

export const PINYIN: Record<string, string> = {
  // 题干
  'q.countDots': 'yí gòng yǒu duō shao gè diǎn zi',
  'q.countPicAll': 'kàn tú suàn yi suàn yí gòng yǒu duō shao gè',
  'q.countPicLeft': 'kàn tú suàn yi suàn hái shèng duō shao gè',
  'q.decompose': 'kě yǐ fēn chéng hé jǐ',
  'q.composeWith': 'hé jǐ zǔ chéng',
  'q.composeOf': 'hé zǔ chéng jǐ',
  'q.breakTenHint': 'xiān cóng shí gé zhèn lǐ ná zǒu gè shèng xià de hé wài miàn de yí gòng yǒu jǐ gè',
  'q.whichMore': 'nǎ ge duō ne',
  'q.fillCompare': 'bǐ yi bǐ tián huò',
  'q.countAll': 'shǔ yi shǔ yí gòng yǒu jǐ gè',
  'q.composeTensOnes': 'gè shí hé gè yī hé qǐ lái shì jǐ',
  'q.composeTens': 'gè shí shì jǐ',
  'q.onesWith': 'gè shí hé jǐ gè yī zǔ chéng',
  'q.tensWith': 'jǐ gè shí hé gè yī zǔ chéng',
  'q.tensDigit': 'de shí wèi shàng shì jǐ',
  'q.onesDigit': 'de gè wèi shàng shì jǐ',
  'q.closer': 'gèng jiē jìn hái shì gèng jiē jìn',
  'q.writeNum': 'xiě zuò jǐ',
  'q.readNum': 'dú zuò shén me',
  'q.addOne': 'tiān shì jǐ',
  'q.midNum': 'hé zhōng jiān de shù shì jǐ',
  'q.muchBigger': 'bǐ dà de duō hái shì dà yì xiē',
  'q.muchSmaller': 'bǐ xiǎo de duō hái shì xiǎo yì xiē',
  'q.countBlocks': 'shǔ yi shǔ yí gòng yǒu duō shao gè xiǎo fāng kuài',
  'q.after': 'hòu miàn de yí gè shù shì jǐ',
  'q.before': 'qián miàn de yí gè shù shì jǐ',
  'q.more': 'bǐ duō de shù shì jǐ',
  'q.less': 'bǐ shǎo de shù shì jǐ',
  'q.posWhich': 'cóng shǔ pái dì jǐ gè',
  'q.posAhead': 'de qián miàn yǒu jǐ gè',
  'q.posBehind': 'de hòu miàn yǒu jǐ gè',
  'q.posFrom': 'cóng shǔ dì gè shì shuí',
  'q.posNum.1': 'yī',
  'q.posNum.2': 'èr',
  'q.posNum.3': 'sān',
  'q.posNum.4': 'sì',
  'q.posNum.5': 'wǔ',
  'q.posNum.6': 'liù',
  'q.posEndmost': 'shuí zài zuì',
  'q.posNeighbor': 'de shì shuí',
  'q.countShape': 'shǔ yi shǔ yǒu jǐ gè',
  'q.whatShape': 'zhè shì shén me tú xíng',
  'q.rollAnyWay': 'nǎ ge tú xíng néng xiàng sì miàn bā fāng gǔn dòng',
  'q.traceFrom': 'yòng nǎ ge wù tǐ kě yǐ huà chū zhè ge tú xíng',
  'q.joinedShape': 'yòng gè tóng yàng de pīn chéng le shén me tú xíng',
  'q.tangramPieces': 'yí tào qī qiǎo bǎn yǒu jǐ kuài',
  'q.tangramCount': 'yí tào qī qiǎo bǎn lǐ yǒu jǐ gè',
  // 人民币
  'q.whatMoney': 'zhè shì duō shao qián',
  'q.totalMoney': 'yí gòng yǒu duō shao qián',
  'q.moneyChange': 'mǎi dōng xi yòng le fù le yīng zhǎo huí duō shao',
  'q.moneyY2J': 'yuán jǐ jiǎo',
  'q.moneyJ2Y': 'jiǎo jǐ yuán',
  'q.moneyJ2F': 'jiǎo jǐ fēn',
  'q.moneyF2J': 'fēn jǐ jiǎo',
  'q.exchangeNote': 'zhāng kě yǐ huàn jǐ zhāng',
  'q.exchangeCoin': 'kě yǐ huàn jǐ gè',
  'q.exchangeMix': 'zhāng kě yǐ huàn zhāng hé jǐ zhāng',
  // 解决问题与其它题型
  'q.findSum': 'nǎ zhāng kǎ piàn de dé shù shì',
  'q.wpRows': 'qián pái yǒu rén hòu pái yǒu rén yí gòng yǒu duō shao rén',
  'q.wpTookLeft': 'lǐng zǒu le gè hái shèng gè yuán lái yǒu duō shao gè',
  'q.wpCome': 'yuán lái yǒu gè yòu ná lái gè yí gòng yǒu duō shao gè',
  'q.wpTotal': 'zuǒ biān yǒu gè yòu biān yǒu gè yí gòng yǒu jǐ gè',
  'q.wpTakeAway': 'yí gòng yǒu gè ná zǒu le gè hái shèng jǐ gè',
  'q.wpGive': 'yuán lái yǒu gè sòng chū gè hái shèng jǐ gè',
  'q.wpPart': 'hé yí gòng yǒu gè yǒu gè yǒu jǐ gè',
  'q.wpPartExtra': 'gè xiǎo péng yǒu yí gòng zuò le gè qí zhōng hóng sè de yǒu gè qí yú de shì lǜ sè de lǜ sè de yǒu jǐ gè',
  'q.thinkAdd': 'suàn jiǎn kě yǐ xiǎng',
  'q.mixStory': 'yuán lái yǒu gè xiān gè yòu gè xiàn zài yǒu jǐ gè',
  'q.verbIn': 'ná lái',
  'q.verbOut': 'ná zǒu',
  'q.between': 'pái dì pái dì hé zhī jiān yǒu jǐ gè',
  // 100 以内加减法 / 数量间的加减关系
  'q.bagFull': 'gè měi gè zhuāng yí dài kě yǐ zhuāng mǎn jǐ dài',
  'q.bagLeft': 'gè měi gè zhuāng yí dài zhuāng mǎn yǐ hòu hái shèng jǐ gè',
  'q.repeatSub': 'lián xù jiǎn jiǎn le cì yǐ hòu shì jǐ',
  'q.diffPic': 'bǐ duō jǐ gè',
  'q.diffMore': 'yǒu gè yǒu gè bǐ duō jǐ gè',
  'q.diffLess': 'yǒu gè yǒu gè bǐ shǎo jǐ gè',
  'q.moreThan': 'yǒu gè bǐ duō gè yǒu jǐ gè',
  'q.lessThan': 'yǒu gè bǐ shǎo gè yǒu jǐ gè',
  'q.moreThanTotal': 'yǒu gè bǐ duō gè liǎng rén yí gòng yǒu jǐ gè',
  'q.lessThanTotal': 'yǒu gè bǐ shǎo gè liǎng rén yí gòng yǒu jǐ gè',
  // 选项 / 方位
  'opt.same': 'tóng yàng duō',
  'opt.muchMore': 'dà de duō',
  'opt.bitMore': 'dà yì xiē',
  'opt.muchLess': 'xiǎo de duō',
  'opt.bitLess': 'xiǎo yì xiē',
  'dir.left': 'zuǒ',
  'dir.right': 'yòu',
  'dir.front': 'qián',
  'dir.back': 'hòu',
  'side.left': 'zuǒ biān',
  'side.right': 'yòu biān',
  'side.front': 'qián miàn',
  'side.back': 'hòu miàn',
  'rel.left': 'zuǒ biān',
  'rel.right': 'yòu biān',
  'rel.front': 'qián miàn',
  'rel.back': 'hòu miàn',
  // 图形名
  'shape.cube': 'zhèng fāng tǐ',
  'shape.cuboid': 'cháng fāng tǐ',
  'shape.cylinder': 'yuán zhù',
  'shape.sphere': 'qiú',
  'shape.square': 'zhèng fāng xíng',
  'shape.rectangle': 'cháng fāng xíng',
  'shape.triangle': 'sān jiǎo xíng',
  'shape.circle': 'yuán',
  'shape.parallelogram': 'píng xíng sì biān xíng',
  // 教具文案
  'lineup.left': 'zuǒ',
  'lineup.right': 'yòu',
  'lineup.up': 'shàng',
  'lineup.down': 'xià',
  'lineup.front': 'qián',
  'lineup.back': 'hòu',
  'tf.add.need': 'gé zi hái chà gè jiù mǎn la',
  'tf.add.split': 'bǎ fēn chéng hé',
  'tf.add.result': 'suǒ yǐ',
  'tf.sub.take': 'gè wèi bú gòu jiǎn xiān cóng lǐ ná zǒu gè',
  'tf.sub.result': 'suǒ yǐ',
  // 知识点标题（练习页页头）
  'kp.s1-00-count': 'shǔ yi shǔ',
  'kp.s1-00-compare': 'bǐ duō shao',
  'kp.s1-00-position': 'qián hòu zuǒ yòu',
  'kp.s1-01-num-5': 'de rèn shi',
  'kp.s1-01-ordinal': 'dì jǐ',
  'kp.s1-01-compose-5': 'yǐ nèi de fēn yǔ hé',
  'kp.s1-01-addsub-5': 'yǐ nèi de jiā jiǎn fǎ',
  'kp.s1-02-num-10': 'de rèn shi',
  'kp.s1-02-compose-10': 'de fēn yǔ hé',
  'kp.s1-02-addsub-10': 'yǐ nèi de jiā jiǎn fǎ',
  'kp.s1-02-mixed': 'lián jiā lián jiǎn hé jiā jiǎn hùn hé',
  'kp.s1-03-solid-shapes': 'lì tǐ tú xíng',
  'kp.s1-04-num-20': 'de rèn shi',
  'kp.s1-04-simple-addsub': 'jiǎn dān de jiā jiǎn fǎ',
  'kp.s1-05-carry-add': 'jiā jǐ',
  'kp.s1-05-add-876': 'jiā jǐ',
  'kp.s1-05-add-5432': 'jiā jǐ',
  'kp.s2-01-flat-shapes': 'píng miàn tú xíng',
  'kp.s2-02-borrow-sub': 'shí jǐ jiǎn',
  'kp.s2-02-sub-876': 'shí jǐ jiǎn',
  'kp.s2-02-sub-5432': 'shí jǐ jiǎn',
  'kp.s2-03-num-100': 'shǔ shù shù de zǔ chéng',
  'kp.s2-03-compare-100': 'shù de shùn xù bǐ jiào dà xiǎo',
  'kp.s2-03-tens-addsub': 'jiǎn dān de jiā jiǎn fǎ',
  'kp.s2-04-oral-add': 'kǒu suàn jiā fǎ',
  'kp.s2-04-oral-sub': 'kǒu suàn jiǎn fǎ',
  'kp.s2-05-written-add': 'bǐ suàn jiā fǎ',
  'kp.s2-05-written-sub': 'bǐ suàn jiǎn fǎ',
  'kp.s2-06-diff': 'liǎng shù xiāng chà jǐ',
  'kp.s2-06-more-less': 'bǐ yí gè shù duō jǐ huò shǎo jǐ',
  'kp.s2-07-money': 'rèn shi rén mín bì',
  // 100 以内数的汉字读法（cnum.ts）：每个字一条
  ...CN_PINYIN,
}

/** 金额是按数值算出来的（如「6元5角」「6角7分」），没有固定模板，这几个字逐字兜底。 */
export const CHAR_PINYIN: Record<string, string> = {
  元: 'yuán',
  角: 'jiǎo',
  分: 'fēn',
}

registerPinyin(PINYIN, CHAR_PINYIN)
