// 一年级数学内容包的拼音：键与 i18n.ts 的中文词条一致，每条与模板里的汉字逐字对齐
// （占位符、数字、标点、emoji 不占位）。一 / 不 按实际读音标变调，个 / 什么 / 认识等按课本习惯标轻声。
// 有测试保证每个中文词条都有拼音、音节数与汉字数相等。
import { registerPinyin } from '@/engine/i18n'

export const PINYIN: Record<string, string> = {
  // 题干
  'q.countDots': 'yí gòng yǒu duō shao gè diǎn zi',
  'q.countPicAll': 'kàn tú suàn yi suàn yí gòng yǒu duō shao gè',
  'q.decompose': 'kě yǐ fēn chéng hé jǐ',
  'q.breakTenHint': 'shí gé zhèn mǎn wài miàn hái yǒu jǐ gè yì qǐ jiǎn yi jiǎn',
  'q.whichMore': 'nǎ ge duō ne',
  'q.fillCompare': 'bǐ yi bǐ tián huò',
  'q.countAll': 'shǔ yi shǔ yí gòng yǒu jǐ gè',
  'q.composeTensOnes': 'gè shí hé gè yī hé qǐ lái shì jǐ',
  'q.after': 'hòu miàn de yí gè shù shì jǐ',
  'q.before': 'qián miàn de yí gè shù shì jǐ',
  'q.more': 'bǐ duō de shù shì jǐ',
  'q.less': 'bǐ shǎo de shù shì jǐ',
  'q.posWhich': 'cóng shǔ pái dì jǐ gè',
  'q.posFrom': 'cóng shǔ dì gè shì shuí',
  'q.posEndmost': 'shuí zài zuì',
  'q.posNeighbor': 'de shì shuí',
  'q.countShape': 'shǔ yi shǔ yǒu jǐ gè',
  'q.whatShape': 'zhè shì shén me tú xíng',
  'q.tilesCount': 'zhè ge tú xíng shì yòng jǐ gè xiǎo zhèng fāng xíng pīn chéng de',
  'q.tilesName': 'yòng xiǎo zhèng fāng xíng pīn chéng de zhè ge tú xíng shì shén me',
  'q.totalMoney': 'yí gòng yǒu duō shao qián',
  'q.moneyChange': 'mǎi dōng xi yòng le fù le yīng zhǎo huí duō shao',
  'q.moneyY2J': 'yuán jǐ jiǎo',
  'q.moneyJ2Y': 'jiǎo jǐ yuán',
  // 100 以内加减法 / 数量间的加减关系
  'q.usedTwice': 'yǒu gè xiān yòng le gè yòu yòng le gè hái shèng jǐ gè',
  'q.diffPic': 'bǐ duō jǐ gè',
  'q.diffMore': 'yǒu gè yǒu gè bǐ duō jǐ gè',
  'q.diffLess': 'yǒu gè yǒu gè bǐ shǎo jǐ gè',
  'q.moreThan': 'yǒu gè bǐ duō gè yǒu jǐ gè',
  'q.lessThan': 'yǒu gè bǐ shǎo gè yǒu jǐ gè',
  'q.moreThanTotal': 'yǒu gè bǐ duō gè liǎng rén yí gòng yǒu jǐ gè',
  // 选项 / 方位
  'opt.same': 'yí yàng duō',
  'dir.left': 'zuǒ',
  'dir.right': 'yòu',
  'dir.up': 'shàng',
  'dir.down': 'xià',
  'dir.front': 'qián',
  'dir.back': 'hòu',
  'side.left': 'zuǒ biān',
  'side.right': 'yòu biān',
  'side.up': 'shàng miàn',
  'side.down': 'xià miàn',
  'side.front': 'qián miàn',
  'side.back': 'hòu miàn',
  'rel.left': 'zuǒ biān',
  'rel.right': 'yòu biān',
  'rel.up': 'shàng miàn',
  'rel.down': 'xià miàn',
  'rel.front': 'qián miàn',
  'rel.back': 'hòu miàn',
  // 图形名
  'shape.cube': 'zhèng fāng tǐ',
  'shape.cuboid': 'cháng fāng tǐ',
  'shape.cylinder': 'yuán zhù',
  'shape.sphere': 'qiú',
  'shape.square': 'zhèng fāng xíng',
  'shape.rectangle': 'cháng fāng xíng',
  'shape.triangle': 'sān jiǎo xíng',
  'shape.circle': 'yuán',
  'shape.parallelogram': 'píng xíng sì biān xíng',
  // 教具文案
  'lineup.left': 'zuǒ',
  'lineup.right': 'yòu',
  'lineup.up': 'shàng',
  'lineup.down': 'xià',
  'lineup.front': 'qián',
  'lineup.back': 'hòu',
  'tf.add.need': 'gé zi hái chà gè jiù mǎn la',
  'tf.add.split': 'bǎ fēn chéng hé',
  'tf.add.result': 'suǒ yǐ',
  'tf.sub.take': 'gè wèi bú gòu jiǎn xiān cóng lǐ ná zǒu gè',
  'tf.sub.result': 'suǒ yǐ',
  // 知识点标题（练习页页头）
  'kp.s1-00-count': 'shǔ yi shǔ',
  'kp.s1-00-compare': 'bǐ duō shao',
  'kp.s1-00-position': 'shàng xià qián hòu zuǒ yòu',
  'kp.s1-01-num-5': 'de rèn shi',
  'kp.s1-01-compose-5': 'yǐ nèi fēn yǔ hé',
  'kp.s1-01-addsub-5': 'yǐ nèi jiā jiǎn fǎ',
  'kp.s1-02-num-10': 'de rèn shi',
  'kp.s1-02-compose-10': 'de zǔ chéng',
  'kp.s1-02-addsub-10': 'yǐ nèi jiā jiǎn fǎ',
  'kp.s1-02-mixed': 'lián jiā lián jiǎn jiā jiǎn hùn hé',
  'kp.s1-03-solid-shapes': 'lì tǐ tú xíng',
  'kp.s1-04-num-20': 'de rèn shi',
  'kp.s1-04-simple-addsub': 'jiǎn dān jiā jiǎn fǎ',
  'kp.s1-05-carry-add': 'còu shí fǎ',
  'kp.s2-01-flat-shapes': 'píng miàn tú xíng',
  'kp.s2-02-borrow-sub': 'pò shí fǎ',
  'kp.s2-03-num-100': 'yǐ nèi de shù',
  'kp.s2-03-compare-100': 'bǐ dà xiǎo',
  'kp.s2-03-tens-addsub': 'zhěng shí shù jiā jiǎn fǎ',
  'kp.s2-04-oral-add': 'kǒu suàn jiā fǎ',
  'kp.s2-04-oral-sub': 'kǒu suàn jiǎn fǎ',
  'kp.s2-05-written-add': 'bǐ suàn jiā fǎ',
  'kp.s2-05-written-sub': 'bǐ suàn jiǎn fǎ',
  'kp.s2-06-diff': 'liǎng shù xiāng chà jǐ',
  'kp.s2-06-more-less': 'bǐ yí gè shù duō jǐ huò shǎo jǐ',
  'kp.s2-07-money': 'rèn shi rén mín bì',
}

/** 金额是按数值算出来的（如「6元5角」），没有固定模板，这两个字逐字兜底。 */
export const CHAR_PINYIN: Record<string, string> = {
  元: 'yuán',
  角: 'jiǎo',
}

registerPinyin(PINYIN, CHAR_PINYIN)
