// 四年级数学的知识点 / 单元名（英文名 + 中文标题的拼音）：随目录一起加载——地图、页头、对战页、浏览器标题在内容包
// 按需加载之前就要用（engine/catalog.ts 的 loadCourse）。中文标题的单一事实源是 curriculum.ts。
import { registerPinyin, registerTitles } from '@/engine/i18n'
import { KNOWLEDGE_POINTS, UNITS } from './curriculum'

// 知识点英文名（中文标题在 curriculum.ts 作单一事实源）
export const KP_TITLE_EN: Record<string, string> = {
  'm4s1-01-within-yi': 'Numbers up to 100 Million',
  'm4s1-01-above-yi': 'Numbers Beyond 100 Million',
  'm4s1-01-compare': 'Comparing Large Numbers',
  'm4s1-01-round': 'Rewriting & Rounding Numbers',
  'm4s1-02-yi': 'How Big Is 100 Million?',
  'm4s1-03-angles': 'More About Angles',
  'm4s1-03-measure': 'Measuring Angles',
  'm4s1-03-draw': 'Drawing Angles',
  'm4s1-04-oral': 'Mental Multiplication',
  'm4s1-04-written': 'Written Multiplication',
  'm4s1-04-pattern': 'How Products Change',
  'm4s1-04-estimate': 'Solving Problems by Estimating',
  'm4s1-05-total-part': 'Total & Parts',
  'm4s1-05-price': 'Unit Price, Quantity & Total Price',
  'm4s1-05-speed': 'Time, Speed & Distance',
  'm4s1-06-parallel': 'Parallel & Perpendicular Lines',
  'm4s1-06-distance': 'Distance from a Point to a Line',
  'm4s1-06-parallelogram': 'Meet Parallelograms',
  'm4s1-06-trapezoid': 'Meet Trapezoids',
  'm4s1-07-single': 'Bar Graphs',
  'm4s1-07-double': 'Double Bar Graphs',
  'm4s1-08-treasure': 'Treasure Hunt at School',
  'm4s2-01-addsub': 'Meaning of Addition & Subtraction',
  'm4s2-01-muldiv': 'Meaning of Multiplication & Division',
  'm4s2-01-brackets': 'Brackets',
  'm4s2-01-solve': 'Solving Problems',
  'm4s2-02-positions': 'Viewing from Different Positions',
  'm4s2-02-objects': 'Viewing Different Objects',
  'm4s2-03-add-laws': 'Commutative & Associative Laws of Addition',
  'm4s2-03-add-apply': 'Using the Laws of Addition',
  'm4s2-03-mul-laws': 'Commutative & Associative Laws of Multiplication',
  'm4s2-03-distrib': 'Distributive Law',
  'm4s2-03-mul-apply': 'Using the Laws of Multiplication',
  'm4s2-04-meaning': 'Meaning of Decimals',
  'm4s2-04-read-write': 'Reading & Writing Decimals',
  'm4s2-04-property': 'Property of Decimals',
  'm4s2-04-compare': 'Comparing Decimals',
  'm4s2-04-shift': 'Moving the Decimal Point',
  'm4s2-04-units': 'Decimals & Unit Conversion',
  'm4s2-04-round': 'Approximating Decimals',
  'm4s2-05-traits': 'Features of Triangles',
  'm4s2-05-sides': 'Sides of a Triangle',
  'm4s2-05-kinds': 'Types of Triangles',
  'm4s2-05-angle-sum': 'Angle Sum of a Triangle',
  'm4s2-05-polygon': 'Angle Sum of Polygons',
  'm4s2-06-addsub': 'Adding & Subtracting Decimals',
  'm4s2-06-mixed': 'Mixed Decimal Addition & Subtraction',
  'm4s2-06-laws': 'Addition Laws with Decimals',
  'm4s2-07-symmetry': 'Axial Symmetry',
  'm4s2-07-translate': 'Translation',
  'm4s2-08-average': 'Average',
  'm4s2-08-double': 'Double Bar Graphs',
  'm4s2-09-lunch': 'Healthy Lunch',
  'm4s2-10-chicken': 'Chickens & Rabbits',
}

export const UNIT_TITLE_EN: Record<string, string> = {
  m4s1u1: 'Numbers Beyond Ten Thousand',
  m4s1u2: 'How Big Is 100 Million?',
  m4s1u3: 'Measuring Angles',
  m4s1u4: 'Multiplying by a Two-Digit Number',
  m4s1u5: 'Addition & Multiplication Models',
  m4s1u6: 'Parallelograms & Trapezoids',
  m4s1u7: 'Bar Graphs',
  m4s1u8: 'Treasure Hunt',
  m4s2u1: 'The Four Operations',
  m4s2u2: 'Observing Objects (II)',
  m4s2u3: 'Laws of Operations',
  m4s2u4: 'Meaning & Properties of Decimals',
  m4s2u5: 'Triangles',
  m4s2u6: 'Adding & Subtracting Decimals',
  m4s2u7: 'Moving Shapes (II)',
  m4s2u8: 'Average & Bar Graphs',
  m4s2u9: 'Healthy Lunch',
  m4s2u10: 'Chickens & Rabbits in a Cage',
}

/** 知识点标题的拼音（练习页页头注音），与 curriculum.ts 的中文标题逐字对齐（「总量与分量」的分读 fēn：部分的量） */
export const TITLE_PINYIN: Record<string, string> = {
  'kp.m4s1-01-within-yi': 'yì yǐ nèi shù de rèn shi',
  'kp.m4s1-01-above-yi': 'yì yǐ shàng shù de rèn shi',
  'kp.m4s1-01-compare': 'shù de dà xiǎo bǐ jiào',
  'kp.m4s1-01-round': 'shù de gǎi xiě hé qiú jìn sì shù',
  'kp.m4s1-02-yi': 'yì yǒu duō dà',
  'kp.m4s1-03-angles': 'jiǎo de zài rèn shi',
  'kp.m4s1-03-measure': 'jiǎo de dù liàng',
  'kp.m4s1-03-draw': 'huà jiǎo',
  'kp.m4s1-04-oral': 'kǒu suàn chéng fǎ',
  'kp.m4s1-04-written': 'bǐ suàn chéng fǎ',
  'kp.m4s1-04-pattern': 'jī de biàn huà guī lǜ',
  'kp.m4s1-04-estimate': 'yòng gū suàn jiě jué wèn tí',
  'kp.m4s1-05-total-part': 'zǒng liàng yǔ fēn liàng de guān xì',
  'kp.m4s1-05-price': 'dān jià shù liàng hé zǒng jià de guān xì',
  'kp.m4s1-05-speed': 'shí jiān sù dù lù chéng de guān xì',
  'kp.m4s1-06-parallel': 'píng xíng hé chuí zhí',
  'kp.m4s1-06-distance': 'diǎn dào zhí xiàn de jù lí',
  'kp.m4s1-06-parallelogram': 'rèn shi píng xíng sì biān xíng',
  'kp.m4s1-06-trapezoid': 'rèn shi tī xíng',
  'kp.m4s1-07-single': 'dān shì tiáo xíng tǒng jì tú',
  'kp.m4s1-07-double': 'fù shì tiáo xíng tǒng jì tú',
  'kp.m4s1-08-treasure': 'xiào yuán xún bǎo',
  'kp.m4s2-01-addsub': 'jiā jiǎn fǎ de yì yì hé gè bù fen jiān de guān xì',
  'kp.m4s2-01-muldiv': 'chéng chú fǎ de yì yì hé gè bù fen jiān de guān xì',
  'kp.m4s2-01-brackets': 'kuò hào',
  'kp.m4s2-01-solve': 'jiě jué wèn tí',
  'kp.m4s2-02-positions': 'cóng bù tóng wèi zhì guān chá wù tǐ',
  'kp.m4s2-02-objects': 'guān chá bù tóng de wù tǐ',
  'kp.m4s2-03-add-laws': 'jiā fǎ jiāo huàn lǜ hé jié hé lǜ',
  'kp.m4s2-03-add-apply': 'jiā fǎ yùn suàn lǜ de yìng yòng',
  'kp.m4s2-03-mul-laws': 'chéng fǎ jiāo huàn lǜ hé jié hé lǜ',
  'kp.m4s2-03-distrib': 'chéng fǎ fēn pèi lǜ',
  'kp.m4s2-03-mul-apply': 'chéng fǎ yùn suàn lǜ de yìng yòng',
  'kp.m4s2-04-meaning': 'xiǎo shù de yì yì',
  'kp.m4s2-04-read-write': 'xiǎo shù de dú fǎ hé xiě fǎ',
  'kp.m4s2-04-property': 'xiǎo shù de xìng zhì',
  'kp.m4s2-04-compare': 'xiǎo shù de dà xiǎo bǐ jiào',
  'kp.m4s2-04-shift': 'xiǎo shù diǎn yí dòng yǐn qǐ xiǎo shù dà xiǎo de biàn huà',
  'kp.m4s2-04-units': 'xiǎo shù yǔ dān wèi huàn suàn',
  'kp.m4s2-04-round': 'xiǎo shù de jìn sì shù',
  'kp.m4s2-05-traits': 'sān jiǎo xíng de tè xìng',
  'kp.m4s2-05-sides': 'sān jiǎo xíng de sān biān guān xì',
  'kp.m4s2-05-kinds': 'sān jiǎo xíng de fēn lèi',
  'kp.m4s2-05-angle-sum': 'sān jiǎo xíng de nèi jiǎo hé',
  'kp.m4s2-05-polygon': 'duō biān xíng de nèi jiǎo hé',
  'kp.m4s2-06-addsub': 'xiǎo shù jiā jiǎn fǎ',
  'kp.m4s2-06-mixed': 'xiǎo shù jiā jiǎn hùn hé yùn suàn',
  'kp.m4s2-06-laws': 'zhěng shù jiā fǎ yùn suàn lǜ tuī guǎng dào xiǎo shù',
  'kp.m4s2-07-symmetry': 'zhóu duì chèn',
  'kp.m4s2-07-translate': 'píng yí',
  'kp.m4s2-08-average': 'píng jūn shù',
  'kp.m4s2-08-double': 'fù shì tiáo xíng tǒng jì tú',
  'kp.m4s2-09-lunch': 'yíng yǎng wǔ cān',
  'kp.m4s2-10-chicken': 'jī tù tóng lóng',
}

registerTitles(
  { zh: Object.fromEntries(KNOWLEDGE_POINTS.map((kp) => [kp.id, kp.title])), en: KP_TITLE_EN },
  { zh: Object.fromEntries(UNITS.map((u) => [u.id, u.title])), en: UNIT_TITLE_EN },
)
registerPinyin(TITLE_PINYIN)
