// 题目里出现的 emoji 的名字（朗读用：题干里的「{item}」、答错时念正确答案），各年级数学内容包共用。
// 键是 `emoji.<字符>`；带 ️（U+FE0F）的 emoji 按原样记，engine/speech 会退一步去掉它再查。
// 新题目用了新 emoji 要在这里补名字（speech.test 会查选项里的 emoji）。

export const EMOJI_ZH: Record<string, string> = {
  // 水果 / 食物
  'emoji.🍎': '苹果',
  'emoji.🍌': '香蕉',
  'emoji.🍓': '草莓',
  'emoji.🍇': '葡萄',
  'emoji.🍊': '橘子',
  'emoji.🍉': '西瓜',
  'emoji.🍑': '桃子',
  'emoji.🍐': '梨',
  'emoji.🍭': '棒棒糖',
  'emoji.🍬': '糖',
  'emoji.🍪': '饼干',
  'emoji.🧁': '小蛋糕',
  'emoji.🥟': '饺子',
  'emoji.🍞': '面包',
  'emoji.🥚': '鸡蛋',
  'emoji.🥕': '胡萝卜',
  // 动物
  'emoji.🐶': '小狗',
  'emoji.🐱': '小猫',
  'emoji.🐰': '小兔子',
  'emoji.🐼': '熊猫',
  'emoji.🦊': '狐狸',
  'emoji.🐷': '小猪',
  'emoji.🐸': '青蛙',
  'emoji.🐵': '猴子',
  'emoji.🐯': '老虎',
  'emoji.🦁': '狮子',
  'emoji.🐟': '小鱼',
  'emoji.🐥': '小鸡',
  'emoji.🐔': '母鸡',
  'emoji.🐄': '奶牛',
  'emoji.🐘': '大象',
  'emoji.🦒': '长颈鹿',
  'emoji.🐜': '蚂蚁',
  'emoji.🦋': '蝴蝶',
  // 植物 / 自然 / 图案
  'emoji.🌸': '小花',
  'emoji.🌻': '向日葵',
  'emoji.🌳': '大树',
  'emoji.⭐': '星星',
  'emoji.🎈': '气球',
  'emoji.❤️': '红心',
  'emoji.🔴': '红圆点',
  'emoji.🔵': '蓝圆点',
  'emoji.🟡': '黄圆点',
  'emoji.🟢': '绿圆点',
  'emoji.🔺': '红三角',
  // 交通
  'emoji.🚗': '小汽车',
  'emoji.🚕': '出租车',
  'emoji.🚌': '公共汽车',
  'emoji.✈️': '飞机',
  'emoji.🚂': '火车',
  'emoji.🚲': '自行车',
  'emoji.🚁': '直升机',
  'emoji.🚡': '缆车',
  'emoji.🛗': '电梯',
  // 学习用品 / 生活用品
  'emoji.✏️': '铅笔',
  'emoji.🖍️': '蜡笔',
  'emoji.📏': '尺子',
  'emoji.📖': '课本',
  'emoji.📚': '书',
  'emoji.🎒': '书包',
  'emoji.📎': '回形针',
  'emoji.📱': '手机',
  'emoji.🥢': '筷子',
  'emoji.🚪': '门',
  'emoji.🛏️': '床',
  'emoji.🗄️': '抽屉',
  'emoji.🚰': '水龙头',
  'emoji.🕰️': '钟',
  'emoji.👕': '上衣',
  'emoji.👖': '裤子',
  'emoji.🧒': '小朋友',
  'emoji.🏫': '学校',
  'emoji.🚩': '红旗',
  // 玩具 / 游乐
  'emoji.⚽': '足球',
  'emoji.🏀': '篮球',
  'emoji.🎁': '礼物',
  'emoji.🧸': '玩具熊',
  'emoji.🎡': '摩天轮',
  'emoji.🎠': '旋转木马',
  'emoji.🛞': '车轮',
  'emoji.🛝': '滑梯',
  'emoji.🪁': '风筝',
}

export const EMOJI_EN: Record<string, string> = {
  'emoji.🍎': 'apple',
  'emoji.🍌': 'banana',
  'emoji.🍓': 'strawberry',
  'emoji.🍇': 'grapes',
  'emoji.🍊': 'orange',
  'emoji.🍉': 'watermelon',
  'emoji.🍑': 'peach',
  'emoji.🍐': 'pear',
  'emoji.🍭': 'lollipop',
  'emoji.🍬': 'candy',
  'emoji.🍪': 'cookie',
  'emoji.🧁': 'cupcake',
  'emoji.🥟': 'dumpling',
  'emoji.🍞': 'bread',
  'emoji.🥚': 'egg',
  'emoji.🥕': 'carrot',
  'emoji.🐶': 'puppy',
  'emoji.🐱': 'kitten',
  'emoji.🐰': 'bunny',
  'emoji.🐼': 'panda',
  'emoji.🦊': 'fox',
  'emoji.🐷': 'piggy',
  'emoji.🐸': 'frog',
  'emoji.🐵': 'monkey',
  'emoji.🐯': 'tiger',
  'emoji.🦁': 'lion',
  'emoji.🐟': 'fish',
  'emoji.🐥': 'chick',
  'emoji.🐔': 'hen',
  'emoji.🐄': 'cow',
  'emoji.🐘': 'elephant',
  'emoji.🦒': 'giraffe',
  'emoji.🐜': 'ant',
  'emoji.🦋': 'butterfly',
  'emoji.🌸': 'flower',
  'emoji.🌻': 'sunflower',
  'emoji.🌳': 'tree',
  'emoji.⭐': 'star',
  'emoji.🎈': 'balloon',
  'emoji.❤️': 'red heart',
  'emoji.🔴': 'red dot',
  'emoji.🔵': 'blue dot',
  'emoji.🟡': 'yellow dot',
  'emoji.🟢': 'green dot',
  'emoji.🔺': 'red triangle',
  'emoji.🚗': 'car',
  'emoji.🚕': 'taxi',
  'emoji.🚌': 'bus',
  'emoji.✈️': 'airplane',
  'emoji.🚂': 'train',
  'emoji.🚲': 'bicycle',
  'emoji.🚁': 'helicopter',
  'emoji.🚡': 'cable car',
  'emoji.🛗': 'elevator',
  'emoji.✏️': 'pencil',
  'emoji.🖍️': 'crayon',
  'emoji.📏': 'ruler',
  'emoji.📖': 'textbook',
  'emoji.📚': 'books',
  'emoji.🎒': 'schoolbag',
  'emoji.📎': 'paper clip',
  'emoji.📱': 'phone',
  'emoji.🥢': 'chopsticks',
  'emoji.🚪': 'door',
  'emoji.🛏️': 'bed',
  'emoji.🗄️': 'drawer',
  'emoji.🚰': 'faucet',
  'emoji.🕰️': 'clock',
  'emoji.👕': 'shirt',
  'emoji.👖': 'pants',
  'emoji.🧒': 'child',
  'emoji.🏫': 'school',
  'emoji.🚩': 'flag',
  'emoji.⚽': 'soccer ball',
  'emoji.🏀': 'basketball',
  'emoji.🎁': 'gift',
  'emoji.🧸': 'teddy bear',
  'emoji.🎡': 'Ferris wheel',
  'emoji.🎠': 'carousel',
  'emoji.🛞': 'wheel',
  'emoji.🛝': 'slide',
  'emoji.🪁': 'kite',
}
