// 二年级数学内容包的拼音：键与 i18n.ts 的中文词条一致，每条与模板里的汉字逐字对齐
// （占位符、数字、标点、emoji 不占位）。一 / 不 按实际读音标变调，个 / 什么 / 早上等按课本习惯标轻声。
// 有测试保证每个中文词条都有拼音、音节数与汉字数相等。
import { registerPinyin } from '@/engine/i18n'
import type { ShapeKind } from '@/types/models'
import { SHAPE_PINYIN } from '@/content/math/shared/labels'
import { KNOWLEDGE_POINTS } from './curriculum'
import { NUMWORD_PINYIN } from './numword'

export const PINYIN: Record<string, string> = {
  // 分类与整理
  'q.countCategory': 'shǔ yi shǔ yǒu jǐ gè',
  'q.oddOne': 'nǎ ge hé qí tā bú shì yí lèi',
  'cat.fruit': 'shuǐ guǒ',
  'cat.animal': 'xiǎo dòng wù',
  'cat.vehicle': 'jiāo tōng gōng jù',
  'q.sort.byColor': 'àn yán sè fēn de yǒu jǐ gè',
  'q.sort.byForm': 'àn xíng zhuàng fēn de yǒu jǐ gè',
  'q.sort.most': 'àn fēn nǎ yí lèi zuì duō',
  'q.sort.least': 'àn fēn nǎ yí lèi zuì shǎo',
  'q.sort.tally': 'yí gè quān dài biǎo míng tóng xué zuì xǐ huan de yǒu jǐ rén',
  'q.sort.tallyMost': 'yí gè quān dài biǎo míng tóng xué zuì xǐ huan nǎ ge dòng wù de rén shù zuì duō',
  'q.sort.table': 'fēn yi fēn shǔ yi shǔ bǎ biǎo tián wán zhěng',
  'cat.byColor': 'yán sè',
  'cat.byForm': 'xíng zhuàng',
  'cat.red': 'hóng sè',
  'cat.yellow': 'huáng sè',
  'cat.blue': 'lán sè',
  'cat.green': 'lǜ sè',
  'cat.circle': 'yuán xíng',
  'cat.square': 'zhèng fāng xíng',
  'cat.heart': 'xīn xíng',
  // 表内乘法
  'q.mul.arrayTotal': 'měi pái yǒu gè yǒu pái yí gòng yǒu duō shao gè',
  'q.mul.groups': 'kàn tú yí gòng yǒu jǐ gè',
  'q.mul.rewrite': 'gè xiāng jiā xiě chéng chéng fǎ suàn shì shì',
  'q.mul.kOfN': 'gè shì duō shao',
  'q.mul.arrayPlus': 'kàn tú yí gòng yǒu duō shao gè',
  'q.mul.price': 'yí gè yuán mǎi gè yào duō shao yuán',
  'q.mul.rows': 'yǒu pái měi pái gè yí gòng yǒu duō shao gè',
  'q.mul.each': 'gè xiǎo péng yǒu měi rén yǒu gè yí gòng yǒu duō shao gè',
  'q.mul.wheels': 'yí liàng yǒu gè lún zi liàng yí gòng yǒu jǐ gè lún zi',
  'q.mul.product': 'jī shì jǐ',
  'q.mul.factors': 'yí gè chéng shù shì lìng yí gè chéng shù shì jī shì duō shao',
  'q.mul.twoRows': 'yǒu liǎng pái yì pái yǒu gè lìng yì pái yǒu gè yí gòng yǒu duō shao gè',
  'q.mul.priceList': 'mǎi gè yí gòng yào duō shao yuán',
  'q.mul.priceTitle': 'měi gè jǐ yuán',
  // 表内除法
  'q.div.fromMul': 'yīn wèi suǒ yǐ jǐ',
  'q.div.shareEach': 'bǎ gè píng jūn fēn chéng fèn měi fèn jǐ gè',
  'q.div.shareGroups': 'gè měi gè yí fèn kě yǐ fēn chéng jǐ fèn',
  'q.div.shareKids': 'bǎ gè píng jūn fēn gěi gè xiǎo péng yǒu měi rén fēn jǐ gè',
  'q.div.writeEq': 'bǎ gè píng jūn fēn chéng fèn měi fèn gè xiě chéng chú fǎ suàn shì shì',
  'q.div.writeEqGroups': 'gè měi gè fàng yì pán fàng le pán xiě chéng chú fǎ suàn shì shì',
  'q.div.isEqual': 'měi yì pái shì yí fèn zhè yàng fēn shì píng jūn fēn duì ma',
  'opt.tf.yes': 'duì',
  'opt.tf.no': 'bú duì',
  'q.div.part.dividend': 'bèi chú shù shì jǐ',
  'q.div.part.divisor': 'chú shù shì jǐ',
  'q.div.part.quotient': 'shāng shì jǐ',
  'q.div.perPerson': 'gè píng jūn fēn gěi gè xiǎo péng yǒu měi rén jǐ gè',
  'q.div.bags': 'gè měi gè zhuāng yí dài kě yǐ zhuāng jǐ dài',
  'q.div.priceEach': 'yuán mǎi le gè měi gè jǐ yuán',
  'q.div.canBuy': 'yí gè yuán yuán kě yǐ mǎi jǐ gè',
  // 连续两问
  'q.two.wheel': 'mó tiān lún měi gè jiào xiāng zuò rén zhèng hǎo zuò mǎn gè jiào xiāng pèng pèng chē rén yí liàng yào zuò jǐ liàng pèng pèng chē',
  'q.two.pencils': 'yì hé qiān bǐ yǒu zhī hé qiān bǐ píng jūn fēn gěi míng tóng xué měi míng tóng xué fēn dào jǐ zhī',
  'q.two.penPrice': 'yuán kě yǐ mǎi zhī tóng yàng de qiān bǐ yì zhī zhōng xìng bǐ bǐ yì zhī qiān bǐ guì yuán mǎi yì zhī zhōng xìng bǐ yào duō shao yuán',
  'q.two.flowers': 'měi pén huā bǎi yí gè tú àn yào yòng pén rú guǒ měi gè tú àn gǎi yòng pén tú àn gè shù bú biàn yí gòng yào yòng jǐ pén',
  'q.two.books': 'bǎ běn shū píng jūn fēn gěi gè xiǎo zǔ měi gè xiǎo zǔ yǒu rén píng jūn měi rén fēn dào jǐ běn',
  // 东南西北
  'q.dir.sunrise': 'zǎo shang tài yáng cóng nǎ ge fāng xiàng shēng qǐ',
  'q.dir.sunset': 'bàng wǎn tài yáng cóng nǎ ge fāng xiàng luò xià',
  'q.dir.opposite': 'de duì miàn shì nǎ ge fāng xiàng',
  'q.dir.map': 'zài dì tú shàng shì nǎ ge fāng xiàng',
  'q.dir.facing': 'miàn xiàng zhàn zhe nǐ de shì nǎ ge fāng xiàng',
  'q.dir.sun': 'zǎo chen miàn xiàng tài yáng zhàn zhe nǐ de shì nǎ ge fāng xiàng',
  'q.tour.title': 'píng miàn tú shàng běi xià nán zuǒ xī yòu dōng',
  'q.tour.where': 'zài píng miàn tú shàng zài de nǎ miàn',
  'q.tour.what': 'zài píng miàn tú shàng de miàn shì shén me',
  'q.tour.walk': 'zài píng miàn tú shàng cóng wǎng zǒu xiān dào nǎ lǐ',
  'opt.east': 'dōng',
  'opt.south': 'nán',
  'opt.west': 'xī',
  'opt.north': 'běi',
  'side.up': 'shàng miàn',
  'side.down': 'xià miàn',
  'side.left': 'zuǒ biān',
  'side.right': 'yòu biān',
  'side.back': 'hòu miàn',
  'side.fFront': 'qián miàn',
  'side.fLeft': 'zuǒ miàn',
  'side.fRight': 'yòu miàn',
  // 厘米和米
  'q.len.unit': 'de dù dà yuē shì dān wèi shì lí mǐ hái shi mǐ',
  'q.len.m2cm': 'mǐ jǐ lí mǐ',
  'q.len.cm2m': 'lí mǐ jǐ mǐ',
  'q.len.cut': 'yì gēn mǐ de shéng zi jiǎn qù lí mǐ hái shèng jǐ lí mǐ',
  'q.len.cmpFill': 'bǐ yi bǐ tián huò',
  'q.len.cmpMcm': 'mǐ lí mǐ',
  'q.len.cmpCmM': 'lí mǐ mǐ',
  'q.len.measure': 'zhè tiáo xiàn duàn yǒu jǐ lí mǐ',
  'q.seg.count': 'zhè ge tú xíng yóu jǐ tiáo xiàn duàn zǔ chéng',
  'q.seg.which': 'nǎ yí gè shì xiàn duàn',
  'q.seg.connect': 'bǎ měi liǎng gè diǎn yòng xiàn duàn lián qǐ lái yí gòng kě yǐ huà jǐ tiáo xiàn duàn',
  'opt.long': 'cháng',
  'opt.tall': 'gāo',
  'opt.cm': 'lí mǐ',
  'opt.m': 'mǐ',
  // 时间在哪里
  'q.whatTime': 'xiàn zài shì jǐ shí',
  'q.time.minuteHand': 'fēn zhēn cóng zǒu dào zǒu le jǐ fēn',
  'q.time.read': 'zhōng miàn shàng shì jǐ shí jǐ fēn',
  'q.time.digital': 'diàn zǐ biǎo shàng yīng gāi xiǎn shì nǎ ge',
  'q.time.bigTick': 'fēn zhēn zǒu yí dà gé shì jǐ fēn',
  'q.time.smallTick': 'fēn zhēn zǒu yì xiǎo gé shì jǐ fēn',
  'q.time.round': 'fēn zhēn zǒu yì quān biǎo shì shí jiān guò le jǐ fēn',
  'q.time.hourTick': 'shí zhēn zǒu yí dà gé biǎo shì shí jiān guò le jǐ xiǎo shí',
  'q.time.hourRound': 'shí zhēn zǒu yì quān biǎo shì shí jiān guò le jǐ xiǎo shí',
  'q.time.secTick': 'miǎo zhēn zǒu yì xiǎo gé shì jǐ miǎo',
  'q.time.secRound': 'miǎo zhēn zǒu yì quān biǎo shì shí jiān guò le jǐ miǎo',
  'q.time.hourToMin': 'shí jǐ fēn',
  'q.time.minToHour': 'fēn jǐ shí',
  'q.time.minToSec': 'fēn jǐ miǎo',
  'q.time.secToMin': 'miǎo jǐ fēn',
  'q.time.halfHour': 'bàn xiǎo shí shì jǐ fēn',
  'q.time.halfMin': 'bàn fēn zhōng shì jǐ miǎo',
  'q.time.unit': 'dà yuē yòng dān wèi shì shí fēn hái shi miǎo',
  'q.time.act.run50': 'pǎo mǐ',
  'q.time.act.blink': 'zhǎ yí xià yǎn jing',
  'q.time.act.clap': 'pāi yí xià shǒu',
  'q.time.act.run1000': 'pǎo mǐ',
  'q.time.act.brush': 'shuā yí cì yá',
  'q.time.act.lesson': 'shàng yì jié kè',
  'q.time.act.lunch': 'chī yí dùn wǔ fàn',
  'q.time.act.song': 'chàng yì shǒu ér gē',
  'q.time.act.marathon': 'pǎo wán mǎ lā sōng',
  'q.time.act.movie': 'kàn yí bù diàn yǐng',
  'q.time.act.school': 'shàng wǔ zài xué xiào',
  'q.time.act.train': 'zuò gāo tiě cóng běi jīng dào shàng hǎi',
  'opt.hour': 'shí',
  'opt.minute': 'fēn',
  'opt.second': 'miǎo',
  // 有余数的除法
  'q.rem.groups': 'gè měi gè yí fèn kě yǐ fēn chéng jǐ fèn',
  'q.rem.left': 'gè měi gè yí fèn fēn wán hòu hái shèng jǐ gè',
  'q.rem.eachKid': 'bǎ gè píng jūn fēn gěi gè xiǎo péng yǒu měi rén zuì duō fēn jǐ gè',
  'q.rem.kidLeft': 'bǎ gè píng jūn fēn gěi gè xiǎo péng yǒu hái shèng jǐ gè',
  'q.rem.maxRem': 'chú shù shì yú shù zuì dà shì jǐ',
  'q.rem.dividend': 'yí gè shù chú yǐ shāng shì yú shù shì zhè ge shù shì jǐ',
  'q.rem.calcQ': 'yòng shù shì jì suàn shāng shì jǐ',
  'q.rem.calcR': 'yòng shù shì jì suàn yú shù shì jǐ',
  'q.rem.cakeBoxes': 'kuài dàn gāo měi gè hé zi zhuāng kuài zhuāng xià quán bù dàn gāo xū yào jǐ gè hé zi',
  'q.rem.breadFull': 'gè miàn bāo gè zhuāng yì hé kě yǐ zhuāng mǎn jǐ hé',
  'q.rem.buyBoxes': 'yì hé miàn bāo yuán yòng yuán zuì duō kě yǐ mǎi jǐ hé',
  'q.rem.boats': 'míng tóng xué qù huá chuán měi tiáo chuán zuì duō zuò rén zhì shǎo yào jǐ tiáo chuán',
  'q.rem.pattern': 'àn zhè yàng de guī lǜ bǎi xià qù dì gè shì shén me yán sè de',
  // 数量间的乘除关系
  'q.times.howMany': 'yǒu gè yǒu gè de gè shù shì de jǐ bèi',
  'q.times.timesOf': 'yǒu gè de gè shù shì gè shù de bèi yǒu jǐ gè',
  'q.times.base': 'yǒu gè shì gè shù de bèi yǒu jǐ gè',
  'q.rel.total': 'měi hé yǒu gè hé yí gòng yǒu duō shao gè',
  'q.rel.perBox': 'gè píng jūn zhuāng zài gè hé zi lǐ měi hé jǐ gè',
  'q.rel.boxes': 'gè měi hé zhuāng gè xū yào jǐ gè hé zi',
  'q.rel.timesSum': 'mǎi le gè mǎi de de gè shù shì de bèi hé yí gòng mǎi le duō shao gè',
  'q.rel.timesMore': 'mǎi le gè mǎi de de gè shù shì de bèi bǐ duō mǎi le duō shao gè',
  'q.rel.pairTimes': 'yǒu rén yǒu rén rén shù shì de jǐ bèi',
  'q.rel.pairMore': 'yǒu rén yǒu rén bǐ duō jǐ rén',
  'q.rel.pairSum': 'yǒu rén yǒu rén yí gòng yǒu duō shao rén',
  'rel.boy': 'nán shēng',
  'rel.girl': 'nǚ shēng',
  // 万以内数的认识
  'num.unit.k': 'gè qiān',
  'num.unit.h': 'gè bǎi',
  'num.unit.t': 'gè shí',
  'num.unit.o': 'gè yī',
  'q.num.compose2': 'hé zǔ chéng de shù shì jǐ',
  'q.num.compose3': 'hé zǔ chéng de shù shì jǐ',
  'q.num.compose4': 'hé zǔ chéng de shù shì jǐ',
  'q.num.after': 'hòu miàn de yí gè shù shì jǐ',
  'q.num.before': 'qián miàn de yí gè shù shì jǐ',
  'q.num.seq': 'zhǎo guī lǜ wèn hào chù tián jǐ',
  'q.num.place.k': 'de qiān wèi shàng shì jǐ',
  'q.num.place.h': 'de bǎi wèi shàng shì jǐ',
  'q.num.place.t': 'de shí wèi shàng shì jǐ',
  'q.num.place.o': 'de gè wèi shàng shì jǐ',
  'q.num.howManyHundreds': 'lǐ miàn yǒu jǐ gè bǎi',
  'q.num.howManyThousands': 'lǐ miàn yǒu jǐ gè qiān',
  'q.num.tenTens': 'gè shí shì jǐ',
  'q.num.tenHundreds': 'gè bǎi shì jǐ',
  'q.num.tenThousands': 'gè qiān shì jǐ',
  'q.num.readAs': 'zhè ge shù dú zuò shén me',
  'q.num.writeAs': 'xiě zuò duō shao',
  'q.num.expand': 'wèn hào chù tián jǐ',
  'q.num.nearK': 'jiē jìn jǐ qiān',
  'q.num.about': 'dà yuē shì duō shao',
  // 汉字读法（numword.ts）：每个字一条
  ...NUMWORD_PINYIN,
  'q.num.largest': 'xià miàn nǎ ge shù zuì dà',
  'q.num.smallest': 'xià miàn nǎ ge shù zuì xiǎo',
  'q.num.cmpFill': 'bǐ yi bǐ tián huò',
  // 加减法各部分间的关系
  'q.chk.add': 'kě yǐ yòng nǎ ge suàn shì yàn suàn',
  'q.chk.sub': 'kě yǐ yòng nǎ ge suàn shì yàn suàn',
  'q.est.buy': 'yí gè yuán yí gè yuán gè mǎi yí gè yuán gòu ma',
  'q.est.seats': 'yī nián jí yǒu rén èr nián jí yǒu rén gè zuò wèi gòu zuò ma',
  'opt.enough': 'gòu',
  'opt.notEnough': 'bú gòu',
  // 图形名（各年级共用一张表）
  ...Object.fromEntries((Object.keys(SHAPE_PINYIN) as ShapeKind[]).map((s) => [`shape.${s}`, SHAPE_PINYIN[s]])),
  // 知识点标题（练习页页头）
  'kp.m2s1-01-sorting': 'fēn lèi yǔ zhěng lǐ',
  'kp.m2s1-02-mult-intro': 'chéng fǎ de chū bù rèn shi',
  'kp.m2s1-02-table-6': 'de chéng fǎ kǒu jué',
  'kp.m2s1-02-mult-addsub': 'chéng jiā chéng jiǎn',
  'kp.m2s1-02-mult-solve': 'yòng chéng fǎ jiě jué wèn tí',
  'kp.m2s1-03-share': 'píng jūn fēn',
  'kp.m2s1-03-div-parts': 'chú fǎ',
  'kp.m2s1-03-div-6': 'yòng de chéng fǎ kǒu jué qiú shāng',
  'kp.m2s1-03-div-solve': 'yòng chú fǎ jiě jué wèn tí',
  'kp.m2s1-04-directions': 'rèn shi dōng nán xī běi',
  'kp.m2s1-04-tour': 'xiào yuán xiǎo dǎo yóu',
  'kp.m2s1-05-cm-m': 'rèn shi lí mǐ hé mǐ',
  'kp.m2s1-05-measure': 'liáng yi liáng',
  'kp.m2s1-05-segment': 'rèn shi xiàn duàn',
  'kp.m2s1-06-table-9': 'de chéng fǎ kǒu jué',
  'kp.m2s1-06-div-9': 'yòng de chéng fǎ kǒu jué qiú shāng',
  'kp.m2s1-06-two-questions': 'lián xù liǎng wèn',
  'kp.m2s2-01-clock-hour': 'rèn shi jǐ shí jǐ shí bàn',
  'kp.m2s2-01-time-read': 'rèn shi jǐ shí jǐ fēn',
  'kp.m2s2-01-time-calc': 'shí fēn miǎo',
  'kp.m2s2-01-time-story': 'wǒ yǔ shí jiān de gù shi',
  'kp.m2s2-02-remainder': 'rèn shi yú shù',
  'kp.m2s2-02-rem-calc': 'yǒu yú shù chú fǎ de jì suàn',
  'kp.m2s2-02-rem-solve': 'yòng yǒu yú shù de chú fǎ jiě jué wèn tí',
  'kp.m2s2-03-times': 'bèi de rèn shi',
  'kp.m2s2-03-mul-div-solve': 'yòng chéng chú fǎ jiě jué wèn tí',
  'kp.m2s2-04-num-1000': 'yǐ nèi shù de rèn shi',
  'kp.m2s2-04-num-10000': 'yǐ nèi shù de rèn shi',
  'kp.m2s2-04-compare': 'dà xiǎo bǐ jiào hé jìn sì shù',
  'kp.m2s2-04-round-addsub': 'jiǎn dān de jiā jiǎn fǎ',
  'kp.m2s2-05-add': 'jiā fǎ',
  'kp.m2s2-05-sub': 'jiǎn fǎ',
  'kp.m2s2-05-relations': 'jiā jiǎn fǎ gè bù fen jiān de guān xi',
}

/** 时刻是按数值算出来的（如「3时半」「7时35分」），这几个字逐字兜底；米 / 厘也放进来，字面量里出现时能注音。 */
export const CHAR_PINYIN: Record<string, string> = {
  时: 'shí',
  分: 'fēn',
  半: 'bàn',
  米: 'mǐ',
  厘: 'lí',
}

// 每个知识点标题都应有拼音（测试也会查），这里在开发期就把漏掉的暴露出来
for (const kp of KNOWLEDGE_POINTS) {
  if (!PINYIN[`kp.${kp.id}`]) throw new Error(`knowledge point ${kp.id} has no pinyin for its title`)
}

registerPinyin(PINYIN, CHAR_PINYIN)
