// 语文各年级共用的题目要求（yq.*）：中英文（Y7）与中文的拼音（与汉字逐字对齐，占位符、数字、标点不占位；
// 一 / 不 标变调，「听一听」这类的一读轻声）。课文、字词、问答题的问题与选项是中文内容，不在这里——它们走各年级
// 内容包的 yw.* 词条（用到时注册，拼音查各包的 py.ts）。makers.ts 导入本文件：出题时要查考的字在不在要求里（inPrompt）。
import type { Dict } from '@/engine/i18n'
import { registerDict, registerPinyin } from '@/engine/i18n'

const ZH: Dict = {
  // 识字
  'yq.listenZi': '听一听，选出你听到的字。',
  'yq.pyZi': '看拼音，选出这个字。',
  'yq.ziPy': '这个字怎么读？',
  'yq.picZi': '看图，选出对应的字。',
  'yq.picWord': '看图，选出对应的词语。',
  'yq.ziPic': '看字，选出对应的图。',
  'yq.digit': '看数字，选出对应的汉字。',
  'yq.ziDigit': '这个汉字是数字几？按一按。',
  // 写字与字的结构
  'yq.strokes': '这个字一共有几画？',
  'yq.first': '这个字的第一笔是什么？',
  'yq.compose': '加一加，变成了什么字？',
  'yq.subtract': '减一减，剩下什么字？',
  'yq.split': '这个字是由哪几个部分组成的？',
  'yq.radicalOf': '这个字的偏旁是哪一个？',
  'yq.whichRadical': '哪个字是{r}？',
  // 课文与词语
  'yq.cloze': '选一选，填一填。',
  'yq.poet': '《{t}》的作者是谁？',
  'yq.antonym': '「{w}」的反义词是哪一个？',
  // 汉语拼音
  'yq.tone': '这个音节是第几声？按一按。',
  // 声调用汉字（第一声）：阿拉伯数字夹在中文句子里，合成出来是读数字的调子（「第1声」的 1 往下掉，像四声）
  'yq.pickTone': '选出第{n}声。',
  'yq.toneNum.1': '一',
  'yq.toneNum.2': '二',
  'yq.toneNum.3': '三',
  'yq.toneNum.4': '四',
  'yq.spell': '拼一拼，选出拼成的音节。',
  'yq.hearPy': '听一听，选出你听到的音节。',
  'yq.picPy': '看图，选出正确的音节。',
  'yq.pyPic': '看拼音，选出对应的图。',
  'yq.pyWord': '看拼音，选出对应的词语。',
  'yq.is.initial': '下面哪一个是声母？',
  'yq.is.final': '下面哪一个是韵母？',
  'yq.is.whole': '下面哪一个是整体认读音节？',
  'yq.is.compound': '下面哪一个是复韵母？',
  'yq.is.front': '下面哪一个是前鼻韵母？',
  'yq.is.back': '下面哪一个是后鼻韵母？',
  'yq.initialOf': '这个音节的声母是哪一个？',
  'yq.finalOf': '这个音节的韵母是哪一个？',
  'yq.flatCurl': '听一听，是平舌音还是翘舌音？',
  'yq.nasal': '听一听，是前鼻韵母还是后鼻韵母？',
  'yq.order': '按顺序，问号那里是哪一个？',
  'yq.lower': '这个大写字母的小写是哪一个？',
  'yq.upper': '这个小写字母的大写是哪一个？',
  'yq.yinxu': '用音序查字法查「{c}」字，先找哪个大写字母？',
  // 二年级（Y9）：词语、多音字、近义词、部首查字法
  'yq.listenCi': '听一听，选出你听到的词语。',
  'yq.polyRead': '这个词里红色的字怎么读？',
  'yq.synonym': '「{w}」的近义词是哪一个？',
  'yq.bushouOf': '用部首查字法查这个字，先查哪个部首？',
  'yq.bushouLeft': '这个字除去部首，还有几画？',
}

const EN: Dict = {
  'yq.listenZi': 'Listen. Which character did you hear?',
  'yq.pyZi': 'Read the pinyin. Which character is it?',
  'yq.ziPy': 'How do you read this character?',
  'yq.picZi': 'Look at the picture. Which character matches it?',
  'yq.picWord': 'Look at the picture. Which word matches it?',
  'yq.ziPic': 'Read the character. Which picture matches it?',
  'yq.digit': 'Which Chinese character is this number?',
  'yq.ziDigit': 'Which number is this Chinese character?',
  'yq.strokes': 'How many strokes does this character have?',
  'yq.first': 'What is the first stroke of this character?',
  'yq.compose': 'Put them together. Which character do they make?',
  'yq.subtract': 'Take one part away. Which character is left?',
  'yq.split': 'Which parts make up this character?',
  'yq.radicalOf': 'Which is the radical of this character?',
  'yq.whichRadical': 'Which character has the radical {r}?',
  'yq.cloze': 'Choose the word that fills the blank.',
  'yq.poet': 'Who wrote the poem "{t}"?',
  'yq.antonym': 'Which word means the opposite of "{w}"?',
  'yq.tone': 'Which tone is this syllable?',
  'yq.pickTone': 'Choose tone {n}.',
  'yq.toneNum.1': '1',
  'yq.toneNum.2': '2',
  'yq.toneNum.3': '3',
  'yq.toneNum.4': '4',
  'yq.spell': 'Blend the sounds. Which syllable do they make?',
  'yq.hearPy': 'Listen. Which syllable did you hear?',
  'yq.picPy': 'Look at the picture. Which pinyin is right?',
  'yq.pyPic': 'Read the pinyin. Which picture matches it?',
  'yq.pyWord': 'Read the pinyin. Which word is it?',
  'yq.is.initial': 'Which one is an initial?',
  'yq.is.final': 'Which one is a final?',
  'yq.is.whole': 'Which one is read as a whole syllable?',
  'yq.is.compound': 'Which one is a compound final?',
  'yq.is.front': 'Which one is a front nasal final?',
  'yq.is.back': 'Which one is a back nasal final?',
  'yq.initialOf': 'Which is the initial of this syllable?',
  'yq.finalOf': 'Which is the final of this syllable?',
  'yq.flatCurl': 'Listen. Flat-tongue or curled-tongue sound?',
  'yq.nasal': 'Listen. Front nasal or back nasal final?',
  'yq.order': 'Which one is missing from the order?',
  'yq.lower': 'What is the small letter for this capital?',
  'yq.upper': 'What is the capital for this letter?',
  'yq.yinxu': 'To look up "{c}" by pinyin order, which capital letter do you find first?',
  'yq.listenCi': 'Listen. Which word did you hear?',
  'yq.polyRead': 'How is the red character read in this word?',
  'yq.synonym': 'Which word means almost the same as "{w}"?',
  'yq.bushouOf': 'To look this character up by its radical, which radical do you look for first?',
  'yq.bushouLeft': 'How many strokes are left without the radical?',
}

export const PINYIN: Record<string, string> = {
  'yq.listenZi': 'tīng yi tīng xuǎn chū nǐ tīng dào de zì',
  'yq.pyZi': 'kàn pīn yīn xuǎn chū zhè ge zì',
  'yq.ziPy': 'zhè ge zì zěn me dú',
  'yq.picZi': 'kàn tú xuǎn chū duì yìng de zì',
  'yq.picWord': 'kàn tú xuǎn chū duì yìng de cí yǔ',
  'yq.ziPic': 'kàn zì xuǎn chū duì yìng de tú',
  'yq.digit': 'kàn shù zì xuǎn chū duì yìng de hàn zì',
  'yq.ziDigit': 'zhè ge hàn zì shì shù zì jǐ àn yi àn',
  'yq.strokes': 'zhè ge zì yí gòng yǒu jǐ huà',
  'yq.first': 'zhè ge zì de dì yī bǐ shì shén me',
  'yq.compose': 'jiā yi jiā biàn chéng le shén me zì',
  'yq.subtract': 'jiǎn yi jiǎn shèng xià shén me zì',
  'yq.split': 'zhè ge zì shì yóu nǎ jǐ gè bù fen zǔ chéng de',
  'yq.radicalOf': 'zhè ge zì de piān páng shì nǎ yí gè',
  'yq.whichRadical': 'nǎ ge zì shì',
  'yq.cloze': 'xuǎn yi xuǎn tián yi tián',
  'yq.poet': 'de zuò zhě shì shuí',
  'yq.antonym': 'de fǎn yì cí shì nǎ yí gè',
  'yq.tone': 'zhè ge yīn jié shì dì jǐ shēng àn yi àn',
  'yq.pickTone': 'xuǎn chū dì shēng',
  'yq.toneNum.1': 'yī',
  'yq.toneNum.2': 'èr',
  'yq.toneNum.3': 'sān',
  'yq.toneNum.4': 'sì',
  'yq.spell': 'pīn yi pīn xuǎn chū pīn chéng de yīn jié',
  'yq.hearPy': 'tīng yi tīng xuǎn chū nǐ tīng dào de yīn jié',
  'yq.picPy': 'kàn tú xuǎn chū zhèng què de yīn jié',
  'yq.pyPic': 'kàn pīn yīn xuǎn chū duì yìng de tú',
  'yq.pyWord': 'kàn pīn yīn xuǎn chū duì yìng de cí yǔ',
  'yq.is.initial': 'xià miàn nǎ yí gè shì shēng mǔ',
  'yq.is.final': 'xià miàn nǎ yí gè shì yùn mǔ',
  'yq.is.whole': 'xià miàn nǎ yí gè shì zhěng tǐ rèn dú yīn jié',
  'yq.is.compound': 'xià miàn nǎ yí gè shì fù yùn mǔ',
  'yq.is.front': 'xià miàn nǎ yí gè shì qián bí yùn mǔ',
  'yq.is.back': 'xià miàn nǎ yí gè shì hòu bí yùn mǔ',
  'yq.initialOf': 'zhè ge yīn jié de shēng mǔ shì nǎ yí gè',
  'yq.finalOf': 'zhè ge yīn jié de yùn mǔ shì nǎ yí gè',
  'yq.flatCurl': 'tīng yi tīng shì píng shé yīn hái shì qiào shé yīn',
  'yq.nasal': 'tīng yi tīng shì qián bí yùn mǔ hái shì hòu bí yùn mǔ',
  'yq.order': 'àn shùn xù wèn hào nà lǐ shì nǎ yí gè',
  'yq.lower': 'zhè ge dà xiě zì mǔ de xiǎo xiě shì nǎ yí gè',
  'yq.upper': 'zhè ge xiǎo xiě zì mǔ de dà xiě shì nǎ yí gè',
  'yq.yinxu': 'yòng yīn xù chá zì fǎ chá zì xiān zhǎo nǎ ge dà xiě zì mǔ',
  'yq.listenCi': 'tīng yi tīng xuǎn chū nǐ tīng dào de cí yǔ',
  'yq.polyRead': 'zhè ge cí lǐ hóng sè de zì zěn me dú',
  'yq.synonym': 'de jìn yì cí shì nǎ yí gè',
  'yq.bushouOf': 'yòng bù shǒu chá zì fǎ chá zhè ge zì xiān chá nǎ ge bù shǒu',
  'yq.bushouLeft': 'zhè ge zì chú qù bù shǒu hái yǒu jǐ huà',
}

registerDict({ zh: ZH, en: EN })
registerPinyin(PINYIN)
