// 三年级语文的知识点 / 单元名（英文名 + 中文标题的拼音）：随目录一起加载——地图、页头、对战页、浏览器标题在内容包
// 按需加载之前就要用（engine/catalog.ts 的 loadCourse）。中文标题的单一事实源是 curriculum.ts。
import { registerPinyin, registerTitles } from '@/engine/i18n'
import { KNOWLEDGE_POINTS, UNITS } from './curriculum'

// 知识点英文名（中文标题在 curriculum.ts 作单一事实源）
const KP_TITLE_EN: Record<string, string> = {
  'c3s1-01-dashu': 'The School Under the Big Banyan Tree',
  'c3s1-01-huaxuexiao': 'The Flower School',
  'c3s1-01-budong': 'Ask When You Don\'t Understand',
  'c3s1-01-garden': 'Language Garden 1',
  'c3s1-02-gushi': 'Three Ancient Poems',
  'c3s1-02-shuinidao': 'A Cement Road Covered with Golden Palms',
  'c3s1-02-qiuyu': 'Autumn Rain',
  'c3s1-02-qiusheng': 'Listen, the Sounds of Autumn',
  'c3s1-02-garden': 'Language Garden 2',
  'c3s1-03-laowu': 'The Old House That Never Falls Down',
  'c3s1-03-jianggui': 'The Stubborn Tortoise',
  'c3s1-03-xiaogou': 'The Puppy Who Learned to Bark',
  'c3s1-03-garden': 'Language Garden 3',
  'c3s1-04-baohulu': 'The Secret of the Magic Gourd',
  'c3s1-04-niudu': 'A Trip Inside a Cow\'s Stomach',
  'c3s1-04-nailao': 'A Piece of Cheese',
  'c3s1-04-garden': 'Language Garden 4',
  'c3s1-05-dachuan': 'The Bird That Rode on Our Boat',
  'c3s1-05-caodi': 'The Golden Meadow',
  'c3s1-06-xisha': 'The Rich Xisha Islands',
  'c3s1-06-haibin': 'A Little Seaside Town',
  'c3s1-06-xinganling': 'The Beautiful Lesser Khingan Mountains',
  'c3s1-06-xianggang': 'Hong Kong, a Dazzling Pearl',
  'c3s1-06-garden': 'Language Garden 6',
  'c3s1-07-gushi': 'Three Ancient Poems',
  'c3s1-07-shengyin': 'The Sounds of Nature',
  'c3s1-07-dashu': 'The Big Book That Never Ends',
  'c3s1-07-garden': 'Language Garden 7',
  'c3s1-08-simaguang': 'Sima Guang',
  'c3s1-08-zhengqi': 'Determined to Do Well',
  'c3s1-08-shoushutai': 'The Operating Table Is My Battlefield',
  'c3s1-08-ciwan': 'A Big Coarse Porcelain Bowl',
  'c3s1-08-garden': 'Language Garden 8',
  'c3s2-01-gushi': 'Three Ancient Poems',
  'c3s2-01-yanzi': 'Swallows',
  'c3s2-01-hehua': 'Lotus Flowers',
  'c3s2-01-kunchong': 'Notes on Insects',
  'c3s2-01-garden': 'Language Garden 1',
  'c3s2-02-shouzhu': 'Waiting by a Tree Stump for a Hare',
  'c3s2-02-lang': 'The Wolf Who Wagged His Tail',
  'c3s2-02-lujiao': 'The Deer\'s Antlers and Legs',
  'c3s2-02-chizi': 'The Pond and the River',
  'c3s2-02-garden': 'Language Garden 2',
  'c3s2-03-haidi': 'The World Under the Sea',
  'c3s2-03-shifeng': 'The Mason Bee',
  'c3s2-03-xiaoxia': 'Little Shrimps',
  'c3s2-03-garden': 'Language Garden 3',
  'c3s2-04-gushi': 'Three Ancient Poems',
  'c3s2-04-zhi': 'The Invention of Paper',
  'c3s2-04-zhaozhou': 'Zhaozhou Bridge',
  'c3s2-04-minghua': 'A Painting Famous at Home and Abroad',
  'c3s2-04-garden': 'Language Garden 4',
  'c3s2-05-huluobo': 'Mr. Carrot\'s Long Beard',
  'c3s2-05-yikeshu': 'I Turned into a Tree',
  'c3s2-06-shuimo': 'Ink Paintings of Childhood',
  'c3s2-06-feizao': 'Soap Bubbles',
  'c3s2-06-huique': 'The Grey Bullfinches',
  'c3s2-06-shixin': 'I Can\'t Break My Promise',
  'c3s2-06-garden': 'Language Garden 6',
  'c3s2-07-huoshaoyun': 'Fire Clouds',
  'c3s2-07-baofengyu': 'Before the Storm',
  'c3s2-07-shijie': 'Our Wonderful World',
  'c3s2-07-garden': 'Language Garden 7',
  'c3s2-08-caifeng': 'The Slow Tailor and the Hasty Customer',
  'c3s2-08-lou': 'The Leak',
  'c3s2-08-zaohe': 'Little Date Pit',
  'c3s2-08-garden': 'Language Garden 8',
}

const UNIT_TITLE_EN: Record<string, string> = Object.fromEntries(UNITS.map((u) => [u.id, 'Reading']))

registerTitles(
  { zh: Object.fromEntries(KNOWLEDGE_POINTS.map((kp) => [kp.id, kp.title])), en: KP_TITLE_EN },
  { zh: Object.fromEntries(UNITS.map((u) => [u.id, u.title])), en: UNIT_TITLE_EN },
)

// 知识点标题的拼音（练习页页头），与 curriculum.ts 的中文逐字对齐
export const TITLE_PINYIN: Record<string, string> = {
  'kp.c3s1-01-dashu': 'dà qīng shù xià de xiǎo xué',
  'kp.c3s1-01-huaxuexiao': 'huā de xué xiào',
  'kp.c3s1-01-budong': 'bù dǒng jiù yào wèn',
  'kp.c3s1-01-garden': 'yǔ wén yuán dì yī',
  'kp.c3s1-02-gushi': 'gǔ shī sān shǒu',
  'kp.c3s1-02-shuinidao': 'pū mǎn jīn sè bā zhang de shuǐ ní dào',
  'kp.c3s1-02-qiuyu': 'qiū tiān de yǔ',
  'kp.c3s1-02-qiusheng': 'tīng ting qiū de shēng yīn',
  'kp.c3s1-02-garden': 'yǔ wén yuán dì èr',
  'kp.c3s1-03-laowu': 'zǒng yě dǎo bù liǎo de lǎo wū',
  'kp.c3s1-03-jianggui': 'jiàng guī',
  'kp.c3s1-03-xiaogou': 'xiǎo gǒu xué jiào',
  'kp.c3s1-03-garden': 'yǔ wén yuán dì sān',
  'kp.c3s1-04-baohulu': 'bǎo hú lu de mì mì',
  'kp.c3s1-04-niudu': 'zài niú dù zi lǐ lǚ xíng',
  'kp.c3s1-04-nailao': 'yí kuài nǎi lào',
  'kp.c3s1-04-garden': 'yǔ wén yuán dì sì',
  'kp.c3s1-05-dachuan': 'dā chuán de niǎo',
  'kp.c3s1-05-caodi': 'jīn sè de cǎo dì',
  'kp.c3s1-06-xisha': 'fù ráo de xī shā qún dǎo',
  'kp.c3s1-06-haibin': 'hǎi bīn xiǎo chéng',
  'kp.c3s1-06-xinganling': 'měi lì de xiǎo xīng ān lǐng',
  'kp.c3s1-06-xianggang': 'xiāng gǎng cuǐ càn de míng zhū',
  'kp.c3s1-06-garden': 'yǔ wén yuán dì liù',
  'kp.c3s1-07-gushi': 'gǔ shī sān shǒu',
  'kp.c3s1-07-shengyin': 'dà zì rán de shēng yīn',
  'kp.c3s1-07-dashu': 'dú bù wán de dà shū',
  'kp.c3s1-07-garden': 'yǔ wén yuán dì qī',
  'kp.c3s1-08-simaguang': 'sī mǎ guāng',
  'kp.c3s1-08-zhengqi': 'yí dìng yào zhēng qì',
  'kp.c3s1-08-shoushutai': 'shǒu shù tái jiù shì zhèn dì',
  'kp.c3s1-08-ciwan': 'yí gè cū cí dà wǎn',
  'kp.c3s1-08-garden': 'yǔ wén yuán dì bā',
  'kp.c3s2-01-gushi': 'gǔ shī sān shǒu',
  'kp.c3s2-01-yanzi': 'yàn zi',
  'kp.c3s2-01-hehua': 'hé huā',
  'kp.c3s2-01-kunchong': 'kūn chóng bèi wàng lù',
  'kp.c3s2-01-garden': 'yǔ wén yuán dì yī',
  'kp.c3s2-02-shouzhu': 'shǒu zhū dài tù',
  'kp.c3s2-02-lang': 'huì yáo wěi ba de láng',
  'kp.c3s2-02-lujiao': 'lù jiǎo hé lù tuǐ',
  'kp.c3s2-02-chizi': 'chí zi yǔ hé liú',
  'kp.c3s2-02-garden': 'yǔ wén yuán dì èr',
  'kp.c3s2-03-haidi': 'hǎi dǐ shì jiè',
  'kp.c3s2-03-shifeng': 'shí fēng',
  'kp.c3s2-03-xiaoxia': 'xiǎo xiā',
  'kp.c3s2-03-garden': 'yǔ wén yuán dì sān',
  'kp.c3s2-04-gushi': 'gǔ shī sān shǒu',
  'kp.c3s2-04-zhi': 'zhǐ de fā míng',
  'kp.c3s2-04-zhaozhou': 'zhào zhōu qiáo',
  'kp.c3s2-04-minghua': 'yì fú míng yáng zhōng wài de huà',
  'kp.c3s2-04-garden': 'yǔ wén yuán dì sì',
  'kp.c3s2-05-huluobo': 'hú luó bo xiān sheng de cháng hú zi',
  'kp.c3s2-05-yikeshu': 'wǒ biàn chéng le yì kē shù',
  'kp.c3s2-06-shuimo': 'tóng nián de shuǐ mò huà',
  'kp.c3s2-06-feizao': 'féi zào pào',
  'kp.c3s2-06-huique': 'huī què',
  'kp.c3s2-06-shixin': 'wǒ bù néng shī xìn',
  'kp.c3s2-06-garden': 'yǔ wén yuán dì liù',
  'kp.c3s2-07-huoshaoyun': 'huǒ shāo yún',
  'kp.c3s2-07-baofengyu': 'bào fēng yǔ lái lín zhī qián',
  'kp.c3s2-07-shijie': 'wǒ men qí miào de shì jiè',
  'kp.c3s2-07-garden': 'yǔ wén yuán dì qī',
  'kp.c3s2-08-caifeng': 'màn xìng zi cái feng hé jí xìng zi gù kè',
  'kp.c3s2-08-lou': 'lòu',
  'kp.c3s2-08-zaohe': 'zǎo hé',
  'kp.c3s2-08-garden': 'yǔ wén yuán dì bā',
}

registerPinyin(TITLE_PINYIN)
