// 生成器通过副作用导入完成注册：每个单元一个文件，新增后在此追加一行。
// 上册
import './views'
import './mixed'
import './length'
import './mass'
import './multiply'
import './coding'
import './lines'
import './fractions'
// 下册
import './motion'
import './divide'
import './rect'
import './area'
import './data'
import './calendar'
import './decimals'
