// 二年级语文的知识点 / 单元名（英文名 + 中文标题的拼音）：随目录一起加载——地图、页头、对战页、浏览器标题在内容包
// 按需加载之前就要用（engine/catalog.ts 的 loadCourse）。中文标题的单一事实源是 curriculum.ts。
import { registerPinyin, registerTitles } from '@/engine/i18n'
import { KNOWLEDGE_POINTS, UNITS } from './curriculum'

// 知识点英文名（中文标题在 curriculum.ts 作单一事实源）
const KP_TITLE_EN: Record<string, string> = {
  'c2s1-01-kedou': 'Little Tadpoles Look for Their Mother',
  'c2s1-01-woshi': 'What Am I?',
  'c2s1-01-zhiwu': 'Plant Mothers Have Their Ways',
  'c2s1-01-garden': 'Language Garden 1',
  'c2s1-02-changjing': 'Song of Scenes',
  'c2s1-02-shuzhi': 'Song of Trees',
  'c2s1-02-paishou': 'Clapping Song',
  'c2s1-02-tianjia': 'Farmers\' Song of the Four Seasons',
  'c2s1-02-garden': 'Language Garden 2',
  'c2s1-03-caihong': 'The Rainbow',
  'c2s1-03-waipo': 'Going to Grandma\'s House',
  'c2s1-03-shuxing': 'The Boy Who Counted the Stars',
  'c2s1-03-garden': 'Language Garden 3',
  'c2s1-04-gushi': 'Two Ancient Poems',
  'c2s1-04-huangshan': 'The Strange Rocks of Mount Huangshan',
  'c2s1-04-riyuetan': 'Sun Moon Lake',
  'c2s1-04-putaogou': 'Grape Valley',
  'c2s1-04-garden': 'Language Garden 4',
  'c2s1-05-zuojing': 'Looking at the Sky from a Well',
  'c2s1-05-hanhao': 'The Cold-Crying Bird',
  'c2s1-05-hulu': 'All I Want Is the Gourds',
  'c2s1-05-garden': 'Language Garden 5',
  'c2s1-06-bajiaolou': 'In the Octagonal Tower',
  'c2s1-06-biandan': 'Zhu De\'s Carrying Pole',
  'c2s1-06-poshui': 'An Unforgettable Water-Splashing Festival',
  'c2s1-06-liuhulan': 'Liu Hulan',
  'c2s1-06-garden': 'Language Garden 6',
  'c2s1-07-gushi': 'Two Ancient Poems',
  'c2s1-07-wu': 'Where Is the Fog?',
  'c2s1-07-xuehaizi': 'The Snow Child',
  'c2s1-07-garden': 'Language Garden 7',
  'c2s1-08-chengzan': 'Praise',
  'c2s1-08-zhichuan': 'Paper Boats and Kites',
  'c2s1-08-xiaohe': 'The Happy Little River',
  'c2s1-08-garden': 'Language Garden 8',
  'c2s2-01-gushi': 'Two Ancient Poems',
  'c2s2-01-chuntian': 'Looking for Spring',
  'c2s2-01-xiaolu': 'A Path Full of Flowers',
  'c2s2-01-zhishu': 'Grandpa Deng Xiaoping Plants a Tree',
  'c2s2-01-garden': 'Language Garden 1',
  'c2s2-02-leifeng': 'Uncle Lei Feng, Where Are You?',
  'c2s2-02-qianrengao': 'A Cake Made by a Thousand People',
  'c2s2-02-ruoxiao': 'I\'m Not the Weakest',
  'c2s2-02-garden': 'Language Garden 2',
  'c2s2-03-shenzhou': 'Song of the Divine Land',
  'c2s2-03-jieri': 'Traditional Festivals',
  'c2s2-03-bei': 'The Story of Bei (Shell)',
  'c2s2-03-meishi': 'Chinese Food',
  'c2s2-03-garden': 'Language Garden 3',
  'c2s2-04-caisemeng': 'Colourful Dreams',
  'c2s2-04-yipima': 'A Fine Horse',
  'c2s2-04-xique': 'Magpies in the Maple Tree',
  'c2s2-04-garden': 'Language Garden 4',
  'c2s2-05-yuyan': 'Two Fables',
  'c2s2-05-yangtao': 'Drawing a Star Fruit',
  'c2s2-05-xiaoma': 'The Little Horse Crosses the River',
  'c2s2-05-garden': 'Language Garden 5',
  'c2s2-06-gushi': 'Two Ancient Poems',
  'c2s2-06-leiyu': 'The Thunderstorm',
  'c2s2-06-milu': 'If You Get Lost in the Wild',
  'c2s2-06-taikong': 'Fun Things About Life in Space',
  'c2s2-06-garden': 'Language Garden 6',
  'c2s2-07-erduo': 'The Elephant\'s Ears',
  'c2s2-07-zhizhu': 'The Spider Opens a Shop',
  'c2s2-07-nitang': 'The Frog Sells His Pond',
  'c2s2-07-maochong': 'The Little Caterpillar',
  'c2s2-07-garden': 'Language Garden 7',
  'c2s2-08-yishe': 'Yi Shoots Down Nine Suns',
  'c2s2-08-huangdi': 'Legends of the Yellow Emperor',
  'c2s2-08-dayu': 'Yu the Great Tames the Floods',
  'c2s2-08-garden': 'Language Garden 8',
}

const UNIT_TITLE_EN: Record<string, string> = Object.fromEntries(UNITS.map((u) => [u.id, u.title === '识字' ? 'Characters' : 'Reading']))

registerTitles(
  { zh: Object.fromEntries(KNOWLEDGE_POINTS.map((kp) => [kp.id, kp.title])), en: KP_TITLE_EN },
  { zh: Object.fromEntries(UNITS.map((u) => [u.id, u.title])), en: UNIT_TITLE_EN },
)

// 知识点标题的拼音（练习页页头），与 curriculum.ts 的中文逐字对齐
export const TITLE_PINYIN: Record<string, string> = {
  'kp.c2s1-01-kedou': 'xiǎo kē dǒu zhǎo mā ma',
  'kp.c2s1-01-woshi': 'wǒ shì shén me',
  'kp.c2s1-01-zhiwu': 'zhí wù mā ma yǒu bàn fǎ',
  'kp.c2s1-01-garden': 'yǔ wén yuán dì yī',
  'kp.c2s1-02-changjing': 'chǎng jǐng gē',
  'kp.c2s1-02-shuzhi': 'shù zhī gē',
  'kp.c2s1-02-paishou': 'pāi shǒu gē',
  'kp.c2s1-02-tianjia': 'tián jiā sì jì gē',
  'kp.c2s1-02-garden': 'yǔ wén yuán dì èr',
  'kp.c2s1-03-caihong': 'cǎi hóng',
  'kp.c2s1-03-waipo': 'qù wài pó jiā',
  'kp.c2s1-03-shuxing': 'shǔ xīng xing de hái zi',
  'kp.c2s1-03-garden': 'yǔ wén yuán dì sān',
  'kp.c2s1-04-gushi': 'gǔ shī èr shǒu',
  'kp.c2s1-04-huangshan': 'huáng shān qí shí',
  'kp.c2s1-04-riyuetan': 'rì yuè tán',
  'kp.c2s1-04-putaogou': 'pú tao gōu',
  'kp.c2s1-04-garden': 'yǔ wén yuán dì sì',
  'kp.c2s1-05-zuojing': 'zuò jǐng guān tiān',
  'kp.c2s1-05-hanhao': 'hán hào niǎo',
  'kp.c2s1-05-hulu': 'wǒ yào de shì hú lu',
  'kp.c2s1-05-garden': 'yǔ wén yuán dì wǔ',
  'kp.c2s1-06-bajiaolou': 'bā jiǎo lóu shàng',
  'kp.c2s1-06-biandan': 'zhū dé de biǎn dan',
  'kp.c2s1-06-poshui': 'nán wàng de pō shuǐ jié',
  'kp.c2s1-06-liuhulan': 'liú hú lán',
  'kp.c2s1-06-garden': 'yǔ wén yuán dì liù',
  'kp.c2s1-07-gushi': 'gǔ shī èr shǒu',
  'kp.c2s1-07-wu': 'wù zài nǎ lǐ',
  'kp.c2s1-07-xuehaizi': 'xuě hái zi',
  'kp.c2s1-07-garden': 'yǔ wén yuán dì qī',
  'kp.c2s1-08-chengzan': 'chēng zàn',
  'kp.c2s1-08-zhichuan': 'zhǐ chuán hé fēng zheng',
  'kp.c2s1-08-xiaohe': 'kuài lè de xiǎo hé',
  'kp.c2s1-08-garden': 'yǔ wén yuán dì bā',
  'kp.c2s2-01-gushi': 'gǔ shī èr shǒu',
  'kp.c2s2-01-chuntian': 'zhǎo chūn tiān',
  'kp.c2s2-01-xiaolu': 'kāi mǎn xiān huā de xiǎo lù',
  'kp.c2s2-01-zhishu': 'dèng xiǎo píng yé ye zhí shù',
  'kp.c2s2-01-garden': 'yǔ wén yuán dì yī',
  'kp.c2s2-02-leifeng': 'léi fēng shū shu nǐ zài nǎ lǐ',
  'kp.c2s2-02-qianrengao': 'qiān rén gāo',
  'kp.c2s2-02-ruoxiao': 'wǒ bú shì zuì ruò xiǎo de',
  'kp.c2s2-02-garden': 'yǔ wén yuán dì èr',
  'kp.c2s2-03-shenzhou': 'shén zhōu yáo',
  'kp.c2s2-03-jieri': 'chuán tǒng jié rì',
  'kp.c2s2-03-bei': 'bèi de gù shi',
  'kp.c2s2-03-meishi': 'zhōng guó měi shí',
  'kp.c2s2-03-garden': 'yǔ wén yuán dì sān',
  'kp.c2s2-04-caisemeng': 'cǎi sè de mèng',
  'kp.c2s2-04-yipima': 'yì pǐ chū sè de mǎ',
  'kp.c2s2-04-xique': 'fēng shù shàng de xǐ què',
  'kp.c2s2-04-garden': 'yǔ wén yuán dì sì',
  'kp.c2s2-05-yuyan': 'yù yán èr zé',
  'kp.c2s2-05-yangtao': 'huà yáng táo',
  'kp.c2s2-05-xiaoma': 'xiǎo mǎ guò hé',
  'kp.c2s2-05-garden': 'yǔ wén yuán dì wǔ',
  'kp.c2s2-06-gushi': 'gǔ shī èr shǒu',
  'kp.c2s2-06-leiyu': 'léi yǔ',
  'kp.c2s2-06-milu': 'yào shi nǐ zài yě wài mí le lù',
  'kp.c2s2-06-taikong': 'tài kōng shēng huó qù shì duō',
  'kp.c2s2-06-garden': 'yǔ wén yuán dì liù',
  'kp.c2s2-07-erduo': 'dà xiàng de ěr duo',
  'kp.c2s2-07-zhizhu': 'zhī zhū kāi diàn',
  'kp.c2s2-07-nitang': 'qīng wā mài ní táng',
  'kp.c2s2-07-maochong': 'xiǎo máo chóng',
  'kp.c2s2-07-garden': 'yǔ wén yuán dì qī',
  'kp.c2s2-08-yishe': 'yì shè jiǔ rì',
  'kp.c2s2-08-huangdi': 'huáng dì de chuán shuō',
  'kp.c2s2-08-dayu': 'dà yǔ zhì shuǐ',
  'kp.c2s2-08-garden': 'yǔ wén yuán dì bā',
}

registerPinyin(TITLE_PINYIN)
