// 一年级语文内容包的拼音：题目要求（yq.*），与 i18n.ts 的中文逐字对齐
// （占位符、数字、标点不占位）。课文与字词的拼音在 py.ts。一 / 不 标变调，「听一听」这类的一读轻声。
import { registerPinyin } from '@/engine/i18n'

export const PINYIN: Record<string, string> = {
  'yq.listenZi': 'tīng yi tīng xuǎn chū nǐ tīng dào de zì',
  'yq.pyZi': 'kàn pīn yīn xuǎn chū zhè ge zì',
  'yq.ziPy': 'zhè ge zì zěn me dú',
  'yq.picZi': 'kàn tú xuǎn chū duì yìng de zì',
  'yq.picWord': 'kàn tú xuǎn chū duì yìng de cí yǔ',
  'yq.ziPic': 'kàn zì xuǎn chū duì yìng de tú',
  'yq.digit': 'kàn shù zì xuǎn chū duì yìng de hàn zì',
  'yq.ziDigit': 'zhè ge hàn zì shì shù zì jǐ àn yi àn',
  'yq.strokes': 'zhè ge zì yí gòng yǒu jǐ huà',
  'yq.first': 'zhè ge zì de dì yī bǐ shì shén me',
  'yq.compose': 'jiā yi jiā biàn chéng le shén me zì',
  'yq.subtract': 'jiǎn yi jiǎn shèng xià shén me zì',
  'yq.split': 'zhè ge zì shì yóu nǎ jǐ gè bù fen zǔ chéng de',
  'yq.radicalOf': 'zhè ge zì de piān páng shì nǎ yí gè',
  'yq.whichRadical': 'nǎ ge zì shì',
  'yq.cloze': 'xuǎn yi xuǎn tián yi tián',
  'yq.poet': 'de zuò zhě shì shuí',
  'yq.antonym': 'de fǎn yì cí shì nǎ yí gè',
  'yq.tone': 'zhè ge yīn jié shì dì jǐ shēng àn yi àn',
  'yq.pickTone': 'xuǎn chū dì shēng',
  'yq.toneNum.1': 'yī',
  'yq.toneNum.2': 'èr',
  'yq.toneNum.3': 'sān',
  'yq.toneNum.4': 'sì',
  'yq.spell': 'pīn yi pīn xuǎn chū pīn chéng de yīn jié',
  'yq.hearPy': 'tīng yi tīng xuǎn chū nǐ tīng dào de yīn jié',
  'yq.picPy': 'kàn tú xuǎn chū zhèng què de yīn jié',
  'yq.pyPic': 'kàn pīn yīn xuǎn chū duì yìng de tú',
  'yq.pyWord': 'kàn pīn yīn xuǎn chū duì yìng de cí yǔ',
  'yq.is.initial': 'xià miàn nǎ yí gè shì shēng mǔ',
  'yq.is.final': 'xià miàn nǎ yí gè shì yùn mǔ',
  'yq.is.whole': 'xià miàn nǎ yí gè shì zhěng tǐ rèn dú yīn jié',
  'yq.is.compound': 'xià miàn nǎ yí gè shì fù yùn mǔ',
  'yq.is.front': 'xià miàn nǎ yí gè shì qián bí yùn mǔ',
  'yq.is.back': 'xià miàn nǎ yí gè shì hòu bí yùn mǔ',
  'yq.initialOf': 'zhè ge yīn jié de shēng mǔ shì nǎ yí gè',
  'yq.finalOf': 'zhè ge yīn jié de yùn mǔ shì nǎ yí gè',
  'yq.flatCurl': 'tīng yi tīng shì píng shé yīn hái shì qiào shé yīn',
  'yq.nasal': 'tīng yi tīng shì qián bí yùn mǔ hái shì hòu bí yùn mǔ',
  'yq.order': 'àn shùn xù wèn hào nà lǐ shì nǎ yí gè',
  'yq.lower': 'zhè ge dà xiě zì mǔ de xiǎo xiě shì nǎ yí gè',
  'yq.upper': 'zhè ge xiǎo xiě zì mǔ de dà xiě shì nǎ yí gè',
  'yq.yinxu': 'yòng yīn xù chá zì fǎ chá zì xiān zhǎo nǎ ge dà xiě zì mǔ',
}

registerPinyin(PINYIN)
