// 一年级语文内容的拼音表（需求 F12 / Y3）：键是课文句子、词语、问题、要注音的选项里的中文（带 emoji 的去掉 emoji），
// 值是与其中汉字逐个对齐的拼音（空格分隔，标点不占位）。按课本注音习惯：一 / 不 标变调，轻声词标轻声（朋友 péng you），
// 多音字按上下文（种田 zhòng、长出 zhǎng、得 de），儿化的「儿」标 r（雨点儿 yǔ diǎn r），作后缀单念的标 er（花儿 huā er）。
// 测试查：每课要用的中文都在表里、音节数等于汉字数；表里没有用不到的条目。
export const PY: Readonly<Record<string, string>> = {
  '一': 'yī',
  '七': 'qī',
  '万': 'wàn',
  '丈': 'zhàng',
  '三': 'sān',
  '上': 'shàng',
  '下': 'xià',
  '专': 'zhuān',
  '业': 'yè',
  '东': 'dōng',
  '丢': 'diū',
  '两': 'liǎng',
  '严': 'yán',
  '个': 'gè',
  '中': 'zhōng',
  '为': 'wèi',
  '主': 'zhǔ',
  '丽': 'lì',
  '举': 'jǔ',
  '义': 'yì',
  '之': 'zhī',
  '乌': 'wū',
  '乐': 'lè',
  '九': 'jiǔ',
  '习': 'xí',
  '乡': 'xiāng',
  '书': 'shū',
  '买': 'mǎi',
  '乱': 'luàn',
  '了': 'le',
  '事': 'shì',
  '二': 'èr',
  '云': 'yún',
  '互': 'hù',
  '五': 'wǔ',
  '井': 'jǐng',
  '些': 'xiē',
  '产': 'chǎn',
  '京': 'jīng',
  '亮': 'liàng',
  '亲': 'qīn',
  '人': 'rén',
  '今': 'jīn',
  '从': 'cóng',
  '仔': 'zǐ',
  '他': 'tā',
  '令': 'lìng',
  '以': 'yǐ',
  '件': 'jiàn',
  '众': 'zhòng',
  '会': 'huì',
  '伞': 'sǎn',
  '传': 'chuán',
  '伸': 'shēn',
  '低': 'dī',
  '体': 'tǐ',
  '作': 'zuò',
  '你': 'nǐ',
  '保': 'bǎo',
  '信': 'xìn',
  '借': 'jiè',
  '偏': 'piān',
  '做': 'zuò',
  '停': 'tíng',
  '偷': 'tōu',
  '像': 'xiàng',
  '元': 'yuán',
  '先': 'xiān',
  '光': 'guāng',
  '兔': 'tù',
  '党': 'dǎng',
  '入': 'rù',
  '八': 'bā',
  '公': 'gōng',
  '六': 'liù',
  '共': 'gòng',
  '关': 'guān',
  '具': 'jù',
  '内': 'nèi',
  '册': 'cè',
  '冬': 'dōng',
  '净': 'jìng',
  '准': 'zhǔn',
  '凉': 'liáng',
  '几': 'jǐ',
  '出': 'chū',
  '刀': 'dāo',
  '分': 'fēn',
  '初': 'chū',
  '别': 'bié',
  '到': 'dào',
  '前': 'qián',
  '剪': 'jiǎn',
  '力': 'lì',
  '办': 'bàn',
  '加': 'jiā',
  '动': 'dòng',
  '勇': 'yǒng',
  '包': 'bāo',
  '北': 'běi',
  '医': 'yī',
  '十': 'shí',
  '升': 'shēng',
  '午': 'wǔ',
  '半': 'bàn',
  '协': 'xié',
  '单': 'dān',
  '南': 'nán',
  '卧': 'wò',
  '厂': 'chǎng',
  '原': 'yuán',
  '去': 'qù',
  '参': 'cān',
  '友': 'yǒu',
  '双': 'shuāng',
  '反': 'fǎn',
  '古': 'gǔ',
  '只': 'zhī',
  '叫': 'jiào',
  '可': 'kě',
  '台': 'tái',
  '右': 'yòu',
  '叶': 'yè',
  '吃': 'chī',
  '合': 'hé',
  '同': 'tóng',
  '后': 'hòu',
  '向': 'xiàng',
  '吓': 'xià',
  '听': 'tīng',
  '吴': 'wú',
  '吹': 'chuī',
  '告': 'gào',
  '周': 'zhōu',
  '呼': 'hū',
  '命': 'mìng',
  '咕': 'gū',
  '咚': 'dōng',
  '响': 'xiǎng',
  '哥': 'gē',
  '哪': 'nǎ',
  '哭': 'kū',
  '唱': 'chàng',
  '善': 'shàn',
  '喜': 'xǐ',
  '喝': 'hē',
  '器': 'qì',
  '四': 'sì',
  '回': 'huí',
  '园': 'yuán',
  '国': 'guó',
  '图': 'tú',
  '圆': 'yuán',
  '土': 'tǔ',
  '在': 'zài',
  '地': 'dì',
  '场': 'chǎng',
  '坐': 'zuò',
  '坑': 'kēng',
  '块': 'kuài',
  '坡': 'pō',
  '坪': 'píng',
  '堂': 'táng',
  '墙': 'qiáng',
  '壁': 'bì',
  '士': 'shì',
  '壮': 'zhuàng',
  '声': 'shēng',
  '壳': 'ké',
  '处': 'chù',
  '夏': 'xià',
  '夕': 'xī',
  '外': 'wài',
  '多': 'duō',
  '夜': 'yè',
  '大': 'dà',
  '天': 'tiān',
  '头': 'tóu',
  '奇': 'qí',
  '女': 'nǚ',
  '好': 'hǎo',
  '妹': 'mèi',
  '姓': 'xìng',
  '娃': 'wá',
  '娘': 'niáng',
  '字': 'zì',
  '孙': 'sūn',
  '孤': 'gū',
  '学': 'xué',
  '它': 'tā',
  '完': 'wán',
  '官': 'guān',
  '宜': 'yí',
  '宝': 'bǎo',
  '害': 'hài',
  '家': 'jiā',
  '寒': 'hán',
  '对': 'duì',
  '小': 'xiǎo',
  '尖': 'jiān',
  '尘': 'chén',
  '就': 'jiù',
  '尺': 'chǐ',
  '尾': 'wěi',
  '居': 'jū',
  '屋': 'wū',
  '展': 'zhǎn',
  '山': 'shān',
  '岸': 'àn',
  '工': 'gōng',
  '左': 'zuǒ',
  '已': 'yǐ',
  '巴': 'bā',
  '布': 'bù',
  '帆': 'fān',
  '师': 'shī',
  '席': 'xí',
  '常': 'cháng',
  '帽': 'mào',
  '平': 'píng',
  '年': 'nián',
  '幸': 'xìng',
  '幼': 'yòu',
  '广': 'guǎng',
  '床': 'chuáng',
  '座': 'zuò',
  '开': 'kāi',
  '弓': 'gōng',
  '张': 'zhāng',
  '弯': 'wān',
  '当': 'dāng',
  '彩': 'cǎi',
  '影': 'yǐng',
  '很': 'hěn',
  '微': 'wēi',
  '心': 'xīn',
  '忘': 'wàng',
  '快': 'kuài',
  '念': 'niàn',
  '忽': 'hū',
  '怕': 'pà',
  '思': 'sī',
  '急': 'jí',
  '性': 'xìng',
  '总': 'zǒng',
  '息': 'xī',
  '悄': 'qiāo',
  '情': 'qíng',
  '惊': 'jīng',
  '惜': 'xī',
  '想': 'xiǎng',
  '意': 'yì',
  '慢': 'màn',
  '战': 'zhàn',
  '戴': 'dài',
  '房': 'fáng',
  '所': 'suǒ',
  '扁': 'biǎn',
  '手': 'shǒu',
  '才': 'cái',
  '扔': 'rēng',
  '扛': 'káng',
  '找': 'zhǎo',
  '把': 'bǎ',
  '折': 'zhé',
  '护': 'hù',
  '抱': 'bào',
  '拉': 'lā',
  '拍': 'pāi',
  '拔': 'bá',
  '招': 'zhāo',
  '拨': 'bō',
  '拿': 'ná',
  '挑': 'tiāo',
  '挣': 'zhèng',
  '捉': 'zhuō',
  '捧': 'pěng',
  '掉': 'diào',
  '掰': 'bāi',
  '握': 'wò',
  '摇': 'yáo',
  '摘': 'zhāi',
  '摸': 'mō',
  '撇': 'piě',
  '操': 'cāo',
  '支': 'zhī',
  '放': 'fàng',
  '故': 'gù',
  '救': 'jiù',
  '敢': 'gǎn',
  '散': 'sàn',
  '敬': 'jìng',
  '数': 'shǔ',
  '斜': 'xié',
  '断': 'duàn',
  '新': 'xīn',
  '方': 'fāng',
  '旗': 'qí',
  '无': 'wú',
  '日': 'rì',
  '早': 'zǎo',
  '明': 'míng',
  '星': 'xīng',
  '春': 'chūn',
  '是': 'shì',
  '晓': 'xiǎo',
  '晚': 'wǎn',
  '晨': 'chén',
  '晴': 'qíng',
  '晶': 'jīng',
  '暑': 'shǔ',
  '暖': 'nuǎn',
  '暮': 'mù',
  '更': 'gèng',
  '最': 'zuì',
  '月': 'yuè',
  '有': 'yǒu',
  '朋': 'péng',
  '望': 'wàng',
  '朝': 'zhāo',
  '木': 'mù',
  '本': 'běn',
  '朵': 'duǒ',
  '机': 'jī',
  '李': 'lǐ',
  '村': 'cūn',
  '条': 'tiáo',
  '来': 'lái',
  '杨': 'yáng',
  '杯': 'bēi',
  '松': 'sōng',
  '林': 'lín',
  '果': 'guǒ',
  '枣': 'zǎo',
  '柔': 'róu',
  '查': 'chá',
  '柳': 'liǔ',
  '树': 'shù',
  '校': 'xiào',
  '桃': 'táo',
  '桥': 'qiáo',
  '桨': 'jiǎng',
  '检': 'jiǎn',
  '棉': 'mián',
  '棒': 'bàng',
  '森': 'sēn',
  '棵': 'kē',
  '楼': 'lóu',
  '模': 'mú',
  '横': 'héng',
  '次': 'cì',
  '欢': 'huān',
  '歌': 'gē',
  '正': 'zhèng',
  '此': 'cǐ',
  '步': 'bù',
  '每': 'měi',
  '比': 'bǐ',
  '毛': 'máo',
  '毽': 'jiàn',
  '氏': 'shì',
  '气': 'qì',
  '水': 'shuǐ',
  '江': 'jiāng',
  '池': 'chí',
  '沉': 'chén',
  '沙': 'shā',
  '没': 'méi',
  '河': 'hé',
  '治': 'zhì',
  '沾': 'zhān',
  '泉': 'quán',
  '法': 'fǎ',
  '波': 'bō',
  '注': 'zhù',
  '泪': 'lèi',
  '洗': 'xǐ',
  '洞': 'dòng',
  '流': 'liú',
  '浪': 'làng',
  '浮': 'fú',
  '海': 'hǎi',
  '消': 'xiāo',
  '淘': 'táo',
  '深': 'shēn',
  '清': 'qīng',
  '渴': 'kě',
  '游': 'yóu',
  '湖': 'hú',
  '湿': 'shī',
  '满': 'mǎn',
  '潮': 'cháo',
  '火': 'huǒ',
  '灯': 'dēng',
  '点': 'diǎn',
  '炼': 'liàn',
  '热': 'rè',
  '然': 'rán',
  '照': 'zhào',
  '煮': 'zhǔ',
  '熊': 'xióng',
  '熟': 'shú',
  '燕': 'yàn',
  '爬': 'pá',
  '爱': 'ài',
  '片': 'piàn',
  '牙': 'yá',
  '牛': 'niú',
  '狗': 'gǒu',
  '猫': 'māo',
  '猴': 'hóu',
  '玉': 'yù',
  '王': 'wáng',
  '玩': 'wán',
  '珠': 'zhū',
  '瓜': 'guā',
  '瓦': 'wǎ',
  '瓶': 'píng',
  '甜': 'tián',
  '生': 'shēng',
  '用': 'yòng',
  '甩': 'shuǎi',
  '田': 'tián',
  '男': 'nán',
  '画': 'huà',
  '疑': 'yí',
  '病': 'bìng',
  '白': 'bái',
  '百': 'bǎi',
  '皮': 'pí',
  '盒': 'hé',
  '盘': 'pán',
  '目': 'mù',
  '直': 'zhí',
  '相': 'xiāng',
  '盼': 'pàn',
  '看': 'kàn',
  '真': 'zhēn',
  '眼': 'yǎn',
  '着': 'zháo',
  '睛': 'jīng',
  '睡': 'shuì',
  '知': 'zhī',
  '短': 'duǎn',
  '碗': 'wǎn',
  '碧': 'bì',
  '福': 'fú',
  '秀': 'xiù',
  '秋': 'qiū',
  '空': 'kōng',
  '窗': 'chuāng',
  '窝': 'wō',
  '立': 'lì',
  '竖': 'shù',
  '站': 'zhàn',
  '端': 'duān',
  '竹': 'zhú',
  '笑': 'xiào',
  '笔': 'bǐ',
  '第': 'dì',
  '答': 'dá',
  '篮': 'lán',
  '米': 'mǐ',
  '粽': 'zòng',
  '红': 'hóng',
  '纯': 'chún',
  '纸': 'zhǐ',
  '细': 'xì',
  '经': 'jīng',
  '结': 'jié',
  '给': 'gěi',
  '绳': 'shéng',
  '绿': 'lǜ',
  '网': 'wǎng',
  '羊': 'yáng',
  '美': 'měi',
  '翅': 'chì',
  '翘': 'qiào',
  '老': 'lǎo',
  '考': 'kǎo',
  '肉': 'ròu',
  '胆': 'dǎn',
  '能': 'néng',
  '脑': 'nǎo',
  '脚': 'jiǎo',
  '脸': 'liǎn',
  '腰': 'yāo',
  '膀': 'bǎng',
  '舌': 'shé',
  '舟': 'zhōu',
  '船': 'chuán',
  '艇': 'tǐng',
  '色': 'sè',
  '节': 'jié',
  '花': 'huā',
  '苦': 'kǔ',
  '茶': 'chá',
  '草': 'cǎo',
  '药': 'yào',
  '荷': 'hé',
  '莲': 'lián',
  '菜': 'cài',
  '萍': 'píng',
  '落': 'luò',
  '蓝': 'lán',
  '藕': 'ǒu',
  '虎': 'hǔ',
  '虫': 'chóng',
  '虾': 'xiā',
  '蚁': 'yǐ',
  '蚂': 'mǎ',
  '蚊': 'wén',
  '蛇': 'shé',
  '蛙': 'wā',
  '蛛': 'zhū',
  '蜘': 'zhī',
  '蝴': 'hú',
  '蝶': 'dié',
  '血': 'xuè',
  '行': 'xíng',
  '衣': 'yī',
  '袄': 'ǎo',
  '裁': 'cái',
  '装': 'zhuāng',
  '西': 'xī',
  '见': 'jiàn',
  '观': 'guān',
  '觉': 'jiào',
  '角': 'jiǎo',
  '言': 'yán',
  '让': 'ràng',
  '讲': 'jiǎng',
  '许': 'xǔ',
  '诉': 'sù',
  '话': 'huà',
  '语': 'yǔ',
  '说': 'shuō',
  '请': 'qǐng',
  '课': 'kè',
  '谁': 'shuí',
  '豆': 'dòu',
  '走': 'zǒu',
  '赵': 'zhào',
  '赶': 'gǎn',
  '起': 'qǐ',
  '足': 'zú',
  '跑': 'pǎo',
  '路': 'lù',
  '跳': 'tiào',
  '踢': 'tī',
  '踩': 'cǎi',
  '蹦': 'bèng',
  '蹲': 'dūn',
  '身': 'shēn',
  '躺': 'tǎng',
  '辣': 'là',
  '边': 'biān',
  '迁': 'qiān',
  '迈': 'mài',
  '运': 'yùn',
  '近': 'jìn',
  '进': 'jìn',
  '远': 'yuǎn',
  '连': 'lián',
  '迟': 'chí',
  '追': 'zhuī',
  '逃': 'táo',
  '透': 'tòu',
  '造': 'zào',
  '遇': 'yù',
  '遍': 'biàn',
  '道': 'dào',
  '邻': 'lín',
  '部': 'bù',
  '酷': 'kù',
  '酸': 'suān',
  '醒': 'xǐng',
  '采': 'cǎi',
  '里': 'lǐ',
  '金': 'jīn',
  '钟': 'zhōng',
  '钱': 'qián',
  '铃': 'líng',
  '铅': 'qiān',
  '银': 'yín',
  '锻': 'duàn',
  '镜': 'jìng',
  '长': 'cháng',
  '门': 'mén',
  '闪': 'shǎn',
  '问': 'wèn',
  '间': 'jiān',
  '闹': 'nào',
  '队': 'duì',
  '阳': 'yáng',
  '阴': 'yīn',
  '降': 'jiàng',
  '院': 'yuàn',
  '难': 'nán',
  '雨': 'yǔ',
  '雪': 'xuě',
  '霜': 'shuāng',
  '霞': 'xiá',
  '露': 'lù',
  '青': 'qīng',
  '静': 'jìng',
  '非': 'fēi',
  '鞋': 'xié',
  '音': 'yīn',
  '顶': 'dǐng',
  '领': 'lǐng',
  '颗': 'kē',
  '风': 'fēng',
  '飘': 'piāo',
  '飞': 'fēi',
  '餐': 'cān',
  '饭': 'fàn',
  '首': 'shǒu',
  '香': 'xiāng',
  '马': 'mǎ',
  '高': 'gāo',
  '鬼': 'guǐ',
  '鱼': 'yú',
  '鲜': 'xiān',
  '鸟': 'niǎo',
  '鸡': 'jī',
  '鸦': 'yā',
  '鹿': 'lù',
  '黄': 'huáng',
  '黑': 'hēi',
  '鼓': 'gǔ',
  '一天': 'yì tiān',
  '一尺': 'yì chǐ',
  '一步': 'yí bù',
  '一米': 'yì mǐ',
  '一般': 'yì bān',
  '一起': 'yì qǐ',
  '一里': 'yì lǐ',
  '万里': 'wàn lǐ',
  '上午': 'shàng wǔ',
  '上官': 'shàng guān',
  '上课': 'shàng kè',
  '上面': 'shàng miàn',
  '下午': 'xià wǔ',
  '下课': 'xià kè',
  '不好': 'bù hǎo',
  '不少': 'bù shǎo',
  '不许': 'bù xǔ',
  '东方': 'dōng fāng',
  '东西': 'dōng xī',
  '严寒': 'yán hán',
  '个子': 'gè zi',
  '中午': 'zhōng wǔ',
  '中国': 'zhōng guó',
  '乌黑': 'wū hēi',
  '乘凉': 'chéng liáng',
  '书包': 'shū bāo',
  '乱叫': 'luàn jiào',
  '乱跑': 'luàn pǎo',
  '乱跳': 'luàn tiào',
  '乱飞': 'luàn fēi',
  '事情': 'shì qing',
  '云彩': 'yún cai',
  '云朵': 'yún duǒ',
  '作业': 'zuò yè',
  '你好': 'nǐ hǎo',
  '做工': 'zuò gōng',
  '傍晚': 'bàng wǎn',
  '光阴': 'guāng yīn',
  '兔子': 'tù zi',
  '公园': 'gōng yuán',
  '公路': 'gōng lù',
  '公鸡': 'gōng jī',
  '写字': 'xiě zì',
  '冬天': 'dōng tiān',
  '冲冲': 'chōng chōng',
  '凉伞': 'liáng sǎn',
  '凉风': 'liáng fēng',
  '几朵': 'jǐ duǒ',
  '创造': 'chuàng zào',
  '到处': 'dào chù',
  '刷牙': 'shuā yá',
  '前天': 'qián tiān',
  '前年': 'qián nián',
  '前面': 'qián miàn',
  '割草': 'gē cǎo',
  '力气': 'lì qi',
  '办法': 'bàn fǎ',
  '加法': 'jiā fǎ',
  '动物': 'dòng wù',
  '包子': 'bāo zi',
  '北京': 'běi jīng',
  '北方': 'běi fāng',
  '医生': 'yī shēng',
  '医院': 'yī yuàn',
  '十十': 'shí shí',
  '十四': 'shí sì',
  '千里': 'qiān lǐ',
  '升起': 'shēng qǐ',
  '半夜': 'bàn yè',
  '南方': 'nán fāng',
  '参加': 'cān jiā',
  '双人': 'shuāng rén',
  '双手': 'shuāng shǒu',
  '双脚': 'shuāng jiǎo',
  '发芽': 'fā yá',
  '叔叔': 'shū shu',
  '口天': 'kǒu tiān',
  '口袋': 'kǒu dài',
  '古月': 'gǔ yuè',
  '可口': 'kě kǒu',
  '台湾': 'tái wān',
  '叶子': 'yè zi',
  '吃果': 'chī guǒ',
  '吃草': 'chī cǎo',
  '吃饭': 'chī fàn',
  '后天': 'hòu tiān',
  '后年': 'hòu nián',
  '后面': 'hòu miàn',
  '听听': 'tīng ting',
  '呱呱': 'guā guā',
  '和风': 'hé fēng',
  '咏鹅': 'yǒng é',
  '咕咕': 'gū gū',
  '哈欠': 'hā qian',
  '哗哗': 'huā huā',
  '哥哥': 'gē ge',
  '哭声': 'kū shēng',
  '哭泣': 'kū qì',
  '唐寅': 'táng yín',
  '唱歌': 'chàng gē',
  '商店': 'shāng diàn',
  '喇叭': 'lǎ ba',
  '喝着': 'hē zháo',
  '喵喵': 'miāo miāo',
  '喷嚏': 'pēn ti',
  '嘎嘎': 'gā gā',
  '器物': 'qì wù',
  '四十': 'sì shí',
  '四四': 'sì sì',
  '四处': 'sì chù',
  '回家': 'huí jiā',
  '回来': 'huí lái',
  '回答': 'huí dá',
  '围巾': 'wéi jīn',
  '国旗': 'guó qí',
  '国歌': 'guó gē',
  '圆圆': 'yuán yuán',
  '地方': 'dì fang',
  '地里': 'dì lǐ',
  '地面': 'dì miàn',
  '墙角': 'qiáng jiǎo',
  '声音': 'shēng yīn',
  '夏天': 'xià tiān',
  '夕阳': 'xī yáng',
  '多多': 'duō duō',
  '多少': 'duō shao',
  '大大': 'dà dà',
  '大树': 'dà shù',
  '大海': 'dà hǎi',
  '大脑': 'dà nǎo',
  '大象': 'dà xiàng',
  '大雁': 'dà yàn',
  '大雨': 'dà yǔ',
  '天下': 'tiān xià',
  '天山': 'tiān shān',
  '天空': 'tiān kōng',
  '太阳': 'tài yáng',
  '奶奶': 'nǎi nai',
  '好冷': 'hǎo lěng',
  '好玩': 'hǎo wán',
  '好疼': 'hǎo téng',
  '好痒': 'hǎo yǎng',
  '好看': 'hǎo kàn',
  '好累': 'hǎo lèi',
  '妈妈': 'mā ma',
  '妹妹': 'mèi mei',
  '姐姐': 'jiě jie',
  '姑姑': 'gū gu',
  '姥姥': 'lǎo lao',
  '姥爷': 'lǎo ye',
  '姨妈': 'yí mā',
  '娃娃': 'wá wa',
  '孔雀': 'kǒng què',
  '孤单': 'gū dān',
  '学堂': 'xué táng',
  '学校': 'xué xiào',
  '安静': 'ān jìng',
  '宝贝': 'bǎo bèi',
  '宫殿': 'gōng diàn',
  '害虫': 'hài chóng',
  '家乡': 'jiā xiāng',
  '家人': 'jiā rén',
  '宽宽': 'kuān kuān',
  '小小': 'xiǎo xiǎo',
  '小池': 'xiǎo chí',
  '小河': 'xiǎo hé',
  '小狗': 'xiǎo gǒu',
  '小猫': 'xiǎo māo',
  '小船': 'xiǎo chuán',
  '小艇': 'xiǎo tǐng',
  '小花': 'xiǎo huā',
  '小草': 'xiǎo cǎo',
  '小荷': 'xiǎo hé',
  '小虾': 'xiǎo xiā',
  '小马': 'xiǎo mǎ',
  '小鱼': 'xiǎo yú',
  '小鸟': 'xiǎo niǎo',
  '小鸡': 'xiǎo jī',
  '小鸭': 'xiǎo yā',
  '少少': 'shǎo shǎo',
  '尖尖': 'jiān jiān',
  '尖角': 'jiān jiǎo',
  '尺子': 'chǐ zi',
  '屈原': 'qū yuán',
  '山南': 'shān nán',
  '山洞': 'shān dòng',
  '山清': 'shān qīng',
  '工人': 'gōng rén',
  '工厂': 'gōng chǎng',
  '左边': 'zuǒ biān',
  '干净': 'gān jìng',
  '年糕': 'nián gāo',
  '广场': 'guǎng chǎng',
  '开心': 'kāi xīn',
  '开放': 'kāi fàng',
  '开花': 'kāi huā',
  '弓长': 'gōng cháng',
  '弯弯': 'wān wān',
  '影子': 'yǐng zi',
  '很大': 'hěn dà',
  '很好': 'hěn hǎo',
  '很小': 'hěn xiǎo',
  '微笑': 'wēi xiào',
  '快乐': 'kuài lè',
  '快快': 'kuài kuài',
  '思考': 'sī kǎo',
  '悯农': 'mǐn nóng',
  '成长': 'chéng zhǎng',
  '我们': 'wǒ men',
  '房子': 'fáng zi',
  '房间': 'fáng jiān',
  '手下': 'shǒu xià',
  '手套': 'shǒu tào',
  '手心': 'shǒu xīn',
  '手绢': 'shǒu juàn',
  '打球': 'dǎ qiú',
  '打鼓': 'dǎ gǔ',
  '找到': 'zhǎo dào',
  '折纸': 'zhé zhǐ',
  '报纸': 'bào zhǐ',
  '抽屉': 'chōu tì',
  '拍拍': 'pāi pāi',
  '拔河': 'bá hé',
  '拖鞋': 'tuō xié',
  '招呼': 'zhāo hu',
  '拨水': 'bō shuǐ',
  '搓搓': 'cuō cuō',
  '摇篮': 'yáo lán',
  '摘花': 'zhāi huā',
  '擦手': 'cā shǒu',
  '擦擦': 'cā cā',
  '放学': 'fàng xué',
  '放牛': 'fàng niú',
  '放进': 'fàng jìn',
  '故乡': 'gù xiāng',
  '散步': 'sàn bù',
  '敬礼': 'jìng lǐ',
  '数学': 'shù xué',
  '新年': 'xīn nián',
  '新疆': 'xīn jiāng',
  '方向': 'fāng xiàng',
  '旁边': 'páng biān',
  '早上': 'zǎo shang',
  '早操': 'zǎo cāo',
  '明天': 'míng tiān',
  '明年': 'míng nián',
  '明月': 'míng yuè',
  '星星': 'xīng xing',
  '春天': 'chūn tiān',
  '春晓': 'chūn xiǎo',
  '春暖': 'chūn nuǎn',
  '春节': 'chūn jié',
  '晚上': 'wǎn shang',
  '晚饭': 'wǎn fàn',
  '晴柔': 'qíng róu',
  '更好': 'gèng hǎo',
  '月亮': 'yuè liang',
  '月牙': 'yuè yá',
  '朋友': 'péng you',
  '朝霞': 'zhāo xiá',
  '木子': 'mù zǐ',
  '李峤': 'lǐ qiáo',
  '李白': 'lǐ bái',
  '李绅': 'lǐ shēn',
  '村长': 'cūn zhǎng',
  '杜甫': 'dù fǔ',
  '松鼠': 'sōng shǔ',
  '果子': 'guǒ zi',
  '果皮': 'guǒ pí',
  '枫叶': 'fēng yè',
  '柳枝': 'liǔ zhī',
  '柳绿': 'liǔ lǜ',
  '树上': 'shù shang',
  '树下': 'shù xià',
  '树林': 'shù lín',
  '树皮': 'shù pí',
  '树阴': 'shù yīn',
  '校园': 'xiào yuán',
  '桃子': 'táo zi',
  '桃红': 'táo hóng',
  '桌子': 'zhuō zi',
  '梅花': 'méi huā',
  '梳头': 'shū tóu',
  '棉被': 'mián bèi',
  '橡皮': 'xiàng pí',
  '欧阳': 'ōu yáng',
  '歌台': 'gē tái',
  '歌声': 'gē shēng',
  '每天': 'měi tiān',
  '毽子': 'jiàn zi',
  '水秀': 'shuǐ xiù',
  '江北': 'jiāng běi',
  '江南': 'jiāng nán',
  '池上': 'chí shàng',
  '汪伦': 'wāng lún',
  '汪汪': 'wāng wāng',
  '汽车': 'qì chē',
  '沙包': 'shā bāo',
  '沙沙': 'shā shā',
  '没有': 'méi yǒu',
  '河南': 'hé nán',
  '河里': 'hé lǐ',
  '洁白': 'jié bái',
  '洋洋': 'yáng yáng',
  '洗澡': 'xǐ zǎo',
  '洗脸': 'xǐ liǎn',
  '浮萍': 'fú píng',
  '游戏': 'yóu xì',
  '满满': 'mǎn mǎn',
  '漂亮': 'piào liang',
  '火红': 'huǒ hóng',
  '火车': 'huǒ chē',
  '灯笼': 'dēng long',
  '热闹': 'rè nao',
  '燕子': 'yàn zi',
  '燕舞': 'yàn wǔ',
  '爷爷': 'yé ye',
  '爸爸': 'bà ba',
  '狐狸': 'hú li',
  '狗熊': 'gǒu xióng',
  '狗狗': 'gǒu gǒu',
  '猴子': 'hóu zi',
  '玉米': 'yù mǐ',
  '王维': 'wáng wéi',
  '玩玩': 'wán wan',
  '珍珠': 'zhēn zhū',
  '瓜地': 'guā dì',
  '瓶子': 'píng zi',
  '甜美': 'tián měi',
  '生气': 'shēng qì',
  '生病': 'shēng bìng',
  '田田': 'tián tián',
  '电话': 'diàn huà',
  '画家': 'huà jiā',
  '画画': 'huà huà',
  '画鸡': 'huà jī',
  '白云': 'bái yún',
  '白兔': 'bái tù',
  '白白': 'bái bái',
  '白色': 'bái sè',
  '白莲': 'bái lián',
  '白菜': 'bái cài',
  '百里': 'bǎi lǐ',
  '皮球': 'pí qiú',
  '盒子': 'hé zi',
  '盘子': 'pán zi',
  '看书': 'kàn shū',
  '看看': 'kàn kan',
  '看见': 'kàn jiàn',
  '眼睛': 'yǎn jing',
  '睡觉': 'shuì jiào',
  '石头': 'shí tou',
  '禾苗': 'hé miáo',
  '秋凉': 'qiū liáng',
  '秋天': 'qiū tiān',
  '种子': 'zhǒng zi',
  '种树': 'zhòng shù',
  '种田': 'zhòng tián',
  '稻谷': 'dào gǔ',
  '空中': 'kōng zhōng',
  '立正': 'lì zhèng',
  '童子': 'tóng zǐ',
  '竹叶': 'zhú yè',
  '笑声': 'xiào shēng',
  '笔袋': 'bǐ dài',
  '笛子': 'dí zi',
  '篮子': 'lán zi',
  '米饭': 'mǐ fàn',
  '红旗': 'hóng qí',
  '红灯': 'hóng dēng',
  '红红': 'hóng hóng',
  '红色': 'hóng sè',
  '红花': 'hóng huā',
  '细流': 'xì liú',
  '细雨': 'xì yǔ',
  '结果': 'jié guǒ',
  '绿灯': 'lǜ dēng',
  '绿绿': 'lǜ lǜ',
  '绿色': 'lǜ sè',
  '美丽': 'měi lì',
  '美术': 'měi shù',
  '翅膀': 'chì bǎng',
  '老师': 'lǎo shī',
  '老牛': 'lǎo niú',
  '耳朵': 'ěr duo',
  '肚子': 'dù zi',
  '胆子': 'dǎn zi',
  '脑袋': 'nǎo dai',
  '脚上': 'jiǎo shàng',
  '脚丫': 'jiǎo yā',
  '脸蛋': 'liǎn dàn',
  '舅舅': 'jiù jiu',
  '花儿': 'huā er',
  '花园': 'huā yuán',
  '花朵': 'huā duǒ',
  '花猫': 'huā māo',
  '花红': 'huā hóng',
  '花里': 'huā lǐ',
  '花香': 'huā xiāng',
  '苍蝇': 'cāng yíng',
  '草地': 'cǎo dì',
  '草芽': 'cǎo yá',
  '荒芜': 'huāng wú',
  '荷叶': 'hé yè',
  '荷花': 'hé huā',
  '莺歌': 'yīng gē',
  '菜籽': 'cài zǐ',
  '萝卜': 'luó bo',
  '蒲扇': 'pú shàn',
  '蓝天': 'lán tiān',
  '蓝色': 'lán sè',
  '蓝蓝': 'lán lán',
  '虫子': 'chóng zi',
  '蚂蚁': 'mǎ yǐ',
  '蚊子': 'wén zi',
  '蚊香': 'wén xiāng',
  '蚯蚓': 'qiū yǐn',
  '蜘蛛': 'zhī zhū',
  '蜜蜂': 'mì fēng',
  '蜡烛': 'là zhú',
  '蜻蜓': 'qīng tíng',
  '蝌蚪': 'kē dǒu',
  '蝴蝶': 'hú dié',
  '融融': 'róng róng',
  '衣服': 'yī fu',
  '西方': 'xī fāng',
  '西瓜': 'xī guā',
  '言午': 'yán wǔ',
  '许多': 'xǔ duō',
  '语文': 'yǔ wén',
  '说话': 'shuō huà',
  '诸葛': 'zhū gě',
  '读书': 'dú shū',
  '课本': 'kè běn',
  '课桌': 'kè zhuō',
  '谷穗': 'gǔ suì',
  '贾岛': 'jiǎ dǎo',
  '走走': 'zǒu zou',
  '走路': 'zǒu lù',
  '起床': 'qǐ chuáng',
  '足下': 'zú xià',
  '足球': 'zú qiú',
  '跑步': 'pǎo bù',
  '跳舞': 'tiào wǔ',
  '跳高': 'tiào gāo',
  '踪迹': 'zōng jì',
  '轻轻': 'qīng qīng',
  '辛勤': 'xīn qín',
  '辛苦': 'xīn kǔ',
  '还行': 'hái xíng',
  '迷藏': 'mí cáng',
  '遥远': 'yáo yuǎn',
  '邻居': 'lín jū',
  '酷暑': 'kù shǔ',
  '采花': 'cǎi huā',
  '采药': 'cǎi yào',
  '采莲': 'cǎi lián',
  '采蜜': 'cǎi mì',
  '重重': 'chóng chóng',
  '野牛': 'yě niú',
  '金子': 'jīn zi',
  '金黄': 'jīn huáng',
  '钓鱼': 'diào yú',
  '铃铛': 'líng dang',
  '铅笔': 'qiān bǐ',
  '长城': 'cháng chéng',
  '长大': 'zhǎng dà',
  '长长': 'cháng cháng',
  '门卫': 'mén wèi',
  '闪闪': 'shǎn shǎn',
  '院子': 'yuàn zi',
  '难过': 'nán guò',
  '雄伟': 'xióng wěi',
  '雨点': 'yǔ diǎn',
  '雪人': 'xuě rén',
  '雪白': 'xuě bái',
  '雪花': 'xuě huā',
  '雪莲': 'xuě lián',
  '雷声': 'léi shēng',
  '青山': 'qīng shān',
  '青草': 'qīng cǎo',
  '青蛙': 'qīng wā',
  '青青': 'qīng qīng',
  '鞭炮': 'biān pào',
  '音乐': 'yīn yuè',
  '顺利': 'shùn lì',
  '飘扬': 'piāo yáng',
  '飞翔': 'fēi xiáng',
  '飞舞': 'fēi wǔ',
  '食粮': 'shí liáng',
  '饭碗': 'fàn wǎn',
  '饭菜': 'fàn cài',
  '馒头': 'mán tou',
  '高兴': 'gāo xìng',
  '高大': 'gāo dà',
  '高高': 'gāo gāo',
  '鱼儿': 'yú er',
  '鲜花': 'xiān huā',
  '鸟儿': 'niǎo er',
  '鸟窝': 'niǎo wō',
  '鸟语': 'niǎo yǔ',
  '鸭子': 'yā zi',
  '鸭梨': 'yā lí',
  '黄灯': 'huáng dēng',
  '黄牛': 'huáng niú',
  '黄色': 'huáng sè',
  '黄金': 'huáng jīn',
  '黄黄': 'huáng huáng',
  '黑狗': 'hēi gǒu',
  '黑色': 'hēi sè',
  '鼻子': 'bí zi',
  '一个个': 'yí gè gè',
  '一册书': 'yí cè shū',
  '一只鸡': 'yì zhī jī',
  '一场空': 'yì cháng kōng',
  '一块饼': 'yí kuài bǐng',
  '一座山': 'yí zuò shān',
  '一把伞': 'yì bǎ sǎn',
  '一把刀': 'yì bǎ dāo',
  '一本本': 'yì běn běn',
  '一条条': 'yì tiáo tiáo',
  '一条鱼': 'yì tiáo yú',
  '一棵树': 'yì kē shù',
  '一片肉': 'yí piàn ròu',
  '一道道': 'yí dào dào',
  '丁零零': 'dīng líng líng',
  '七朵花': 'qī duǒ huā',
  '三点水': 'sān diǎn shuǐ',
  '上个月': 'shàng gè yuè',
  '下个月': 'xià gè yuè',
  '下象棋': 'xià xiàng qí',
  '下起来': 'xià qǐ lái',
  '中秋节': 'zhōng qiū jié',
  '乡亲们': 'xiāng qīn men',
  '云彩里': 'yún cai lǐ',
  '亮晶晶': 'liàng jīng jīng',
  '传达室': 'chuán dá shì',
  '作业本': 'zuò yè běn',
  '停下来': 'tíng xià lái',
  '停机坪': 'tíng jī píng',
  '儿童节': 'ér tóng jié',
  '写秃了': 'xiě tū le',
  '冬雪飘': 'dōng xuě piāo',
  '去睡觉': 'qù shuì jiào',
  '反犬旁': 'fǎn quǎn páng',
  '发烧了': 'fā shāo le',
  '口字旁': 'kǒu zì páng',
  '叮当当': 'dīng dāng dāng',
  '叶子上': 'yè zi shang',
  '听一听': 'tīng yi tīng',
  '哗啦啦': 'huā lā lā',
  '唱着歌': 'chàng zhe gē',
  '啄木鸟': 'zhuó mù niǎo',
  '圆圆叶': 'yuán yuán yè',
  '圆溜溜': 'yuán liū liū',
  '夏雨落': 'xià yǔ luò',
  '大树上': 'dà shù shang',
  '大树下': 'dà shù xià',
  '大河边': 'dà hé biān',
  '大海里': 'dà hǎi lǐ',
  '大灰狼': 'dà huī láng',
  '大白鹅': 'dà bái é',
  '天安门': 'tiān ān mén',
  '天空中': 'tiān kōng zhōng',
  '女字旁': 'nǚ zì páng',
  '好朋友': 'hǎo péng you',
  '好老师': 'hǎo lǎo shī',
  '孟浩然': 'mèng hào rán',
  '学校里': 'xué xiào lǐ',
  '家门口': 'jiā mén kǒu',
  '对不起': 'duì bù qǐ',
  '小兔子': 'xiǎo tù zi',
  '小公鸡': 'xiǎo gōng jī',
  '小动物': 'xiǎo dòng wù',
  '小妹妹': 'xiǎo mèi mei',
  '小姑娘': 'xiǎo gū niang',
  '小山村': 'xiǎo shān cūn',
  '小弟弟': 'xiǎo dì di',
  '小朋友': 'xiǎo péng you',
  '小树枝': 'xiǎo shù zhī',
  '小水珠': 'xiǎo shuǐ zhū',
  '小河边': 'xiǎo hé biān',
  '小河里': 'xiǎo hé lǐ',
  '小猴子': 'xiǎo hóu zi',
  '小白兔': 'xiǎo bái tù',
  '小花猫': 'xiǎo huā māo',
  '小蜻蜓': 'xiǎo qīng tíng',
  '小青蛙': 'xiǎo qīng wā',
  '小鱼儿': 'xiǎo yú er',
  '小鸭子': 'xiǎo yā zi',
  '小鸽子': 'xiǎo gē zi',
  '小黄鸡': 'xiǎo huáng jī',
  '小黑狗': 'xiǎo hēi gǒu',
  '尖尖角': 'jiān jiān jiǎo',
  '屋顶上': 'wū dǐng shàng',
  '山坡上': 'shān pō shàng',
  '山洞里': 'shān dòng lǐ',
  '山花红': 'shān huā hóng',
  '平舌音': 'píng shé yīn',
  '弯着腰': 'wān zhe yāo',
  '很难过': 'hěn nán guò',
  '慢慢长': 'màn màn zhǎng',
  '战士们': 'zhàn shì men',
  '房子里': 'fáng zi lǐ',
  '房顶上': 'fáng dǐng shàng',
  '打蚊子': 'dǎ wén zi',
  '找虫子': 'zhǎo chóng zi',
  '折纸船': 'zhé zhǐ chuán',
  '抱着瓜': 'bào zhe guā',
  '拍皮球': 'pāi pí qiú',
  '拔萝卜': 'bá luó bo',
  '挖井人': 'wā jǐng rén',
  '捉虫子': 'zhuō chóng zi',
  '提手旁': 'tí shǒu páng',
  '搬东西': 'bān dōng xi',
  '搭积木': 'dā jī mù',
  '摔倒了': 'shuāi dǎo le',
  '操场上': 'cāo chǎng shàng',
  '文具盒': 'wén jù hé',
  '日字旁': 'rì zì páng',
  '春风吹': 'chūn fēng chuī',
  '晒太阳': 'shài tài yáng',
  '有点大': 'yǒu diǎn dà',
  '木字旁': 'mù zì páng',
  '村子里': 'cūn zi lǐ',
  '杨万里': 'yáng wàn lǐ',
  '松树下': 'sōng shù xià',
  '树林里': 'shù lín lǐ',
  '根断了': 'gēn duàn le',
  '桃树下': 'táo shù xià',
  '梅花鹿': 'méi huā lù',
  '每个月': 'měi gè yuè',
  '毛主席': 'máo zhǔ xí',
  '池草青': 'chí cǎo qīng',
  '沙洲坝': 'shā zhōu bà',
  '沙滩上': 'shā tān shàng',
  '没关系': 'méi guān xi',
  '没意思': 'méi yì si',
  '满满的': 'mǎn mǎn de',
  '牛伯伯': 'niú bó bo',
  '牛姐姐': 'niú jiě jie',
  '牛弟弟': 'niú dì di',
  '牛阿姨': 'niú ā yí',
  '玉米地': 'yù mǐ dì',
  '瑞金城': 'ruì jīn chéng',
  '白居易': 'bái jū yì',
  '目字旁': 'mù zì páng',
  '看一看': 'kàn yi kàn',
  '看星星': 'kàn xīng xing',
  '看电视': 'kàn diàn shì',
  '睡着觉': 'shuì zhe jiào',
  '秋霜降': 'qiū shuāng jiàng',
  '种树人': 'zhòng shù rén',
  '空着手': 'kōng zhe shǒu',
  '竖心旁': 'shù xīn páng',
  '端午节': 'duān wǔ jié',
  '算一算': 'suàn yi suàn',
  '箬竹叶': 'ruò zhú yè',
  '红红花': 'hóng hóng huā',
  '红通通': 'hóng tōng tōng',
  '细细流': 'xì xì liú',
  '绿水里': 'lǜ shuǐ lǐ',
  '绿油油': 'lǜ yóu yóu',
  '翘舌音': 'qiào shé yīn',
  '老公公': 'lǎo gōng gong',
  '老婆婆': 'lǎo pó po',
  '节节高': 'jié jié gāo',
  '草地上': 'cǎo dì shang',
  '虫字旁': 'chóng zì páng',
  '言字旁': 'yán zì páng',
  '讲故事': 'jiǎng gù shi',
  '读一读': 'dú yi dú',
  '谁来开': 'shuí lái kāi',
  '谢谢你': 'xiè xie nǐ',
  '贺知章': 'hè zhī zhāng',
  '赠汪伦': 'zèng wāng lún',
  '走着去': 'zǒu zhe qù',
  '走过来': 'zǒu guò lái',
  '赶蝇子': 'gǎn yíng zi',
  '足字旁': 'zú zì páng',
  '跳着舞': 'tiào zhe wǔ',
  '踢足球': 'tī zú qiú',
  '转笔刀': 'zhuàn bǐ dāo',
  '轮流跳': 'lún liú tiào',
  '轰隆隆': 'hōng lōng lōng',
  '这个月': 'zhè ge yuè',
  '都很累': 'dōu hěn lèi',
  '阳光下': 'yáng guāng xià',
  '阴沉沉': 'yīn chén chén',
  '雪莲花': 'xuě lián huā',
  '静夜思': 'jìng yè sī',
  '飞起来': 'fēi qǐ lái',
  '骆宾王': 'luò bīn wáng',
  '高山上': 'gāo shān shàng',
  '鱼出水': 'yú chū shuǐ',
  '鸟入林': 'niǎo rù lín',
  '鸟字旁': 'niǎo zì páng',
  '一个玉米': 'yí gè yù mǐ',
  '一件上衣': 'yí jiàn shàng yī',
  '一台电视': 'yì tái diàn shì',
  '一块菜地': 'yí kuài cài dì',
  '一床棉被': 'yì chuáng mián bèi',
  '一心一意': 'yì xīn yí yì',
  '一支铅笔': 'yì zhī qiān bǐ',
  '一条裤子': 'yì tiáo kù zi',
  '一根绳子': 'yì gēn shéng zi',
  '一模一样': 'yì mú yí yàng',
  '一片叶子': 'yí piàn yè zi',
  '一片草地': 'yí piàn cǎo dì',
  '一部手机': 'yí bù shǒu jī',
  '一颗石子': 'yì kē shí zǐ',
  '七上八下': 'qī shàng bā xià',
  '七星瓢虫': 'qī xīng piáo chóng',
  '三头六臂': 'sān tóu liù bì',
  '不会游泳': 'bú huì yóu yǒng',
  '买新文具': 'mǎi xīn wén jù',
  '云对雨，': 'yún duì yǔ',
  '五星国旗': 'wǔ xīng guó qí',
  '五星红旗': 'wǔ xīng hóng qí',
  '五颜六色': 'wǔ yán liù sè',
  '公鸡哥哥': 'gōng jī gē ge',
  '公鸡妹妹': 'gōng jī mèi mei',
  '公鸡姐姐': 'gōng jī jiě jie',
  '公鸡弟弟': 'gōng jī dì di',
  '其乐融融': 'qí lè róng róng',
  '几个桃子': 'jǐ gè táo zi',
  '几点钟开': 'jǐ diǎn zhōng kāi',
  '前鼻韵母': 'qián bí yùn mǔ',
  '十全十美': 'shí quán shí měi',
  '升旗仪式': 'shēng qí yí shì',
  '去操场玩': 'qù cāo chǎng wán',
  '去河边玩': 'qù hé biān wán',
  '又大又圆': 'yòu dà yòu yuán',
  '又大又多': 'yòu dà yòu duō',
  '又大又红': 'yòu dà yòu hóng',
  '又小又少': 'yòu xiǎo yòu shǎo',
  '又小又扁': 'yòu xiǎo yòu biǎn',
  '又小又青': 'yòu xiǎo yòu qīng',
  '变成了冰': 'biàn chéng le bīng',
  '古对今，': 'gǔ duì jīn',
  '古朗月行': 'gǔ lǎng yuè xíng',
  '叶子上的': 'yè zi shang de',
  '同心协力': 'tóng xīn xié lì',
  '同甘共苦': 'tóng gān gòng kǔ',
  '后鼻韵母': 'hòu bí yùn mǔ',
  '哪一天开': 'nǎ yì tiān kāi',
  '四只鸽子': 'sì zhī gē zi',
  '圆对方。': 'yuán duì fāng',
  '在哪儿开': 'zài nǎ r kāi',
  '壁虎妈妈': 'bì hǔ mā ma',
  '大海里面': 'dà hǎi lǐ miàn',
  '大雨点儿': 'dà yǔ diǎn r',
  '天伦之乐': 'tiān lún zhī lè',
  '天太冷了': 'tiān tài lěng le',
  '它飞走了': 'tā fēi zǒu le',
  '尊老爱幼': 'zūn lǎo ài yòu',
  '小桥下面': 'xiǎo qiáo xià miàn',
  '小雨点儿': 'xiǎo yǔ diǎn r',
  '小鱼伯伯': 'xiǎo yú bó bo',
  '小鱼妹妹': 'xiǎo yú mèi mei',
  '小鱼姐姐': 'xiǎo yú jiě jie',
  '小鱼阿姨': 'xiǎo yú ā yí',
  '很大很大': 'hěn dà hěn dà',
  '很小很小': 'hěn xiǎo hěn xiǎo',
  '慢慢变少': 'màn màn biàn shǎo',
  '手会很累': 'shǒu huì hěn lèi',
  '手足情深': 'shǒu zú qíng shēn',
  '扛着玉米': 'káng zhe yù mǐ',
  '找不到家': 'zhǎo bú dào jiā',
  '捧着桃子': 'pěng zhe táo zi',
  '掌握方向': 'zhǎng wò fāng xiàng',
  '新的书包': 'xīn de shū bāo',
  '新的玩具': 'xīn de wán jù',
  '新的衣服': 'xīn de yī fu',
  '晨对暮，': 'chén duì mù',
  '柳对杨。': 'liǔ duì yáng',
  '树太高了': 'shù tài gāo le',
  '树干里的': 'shù gàn lǐ de',
  '桃对李，': 'táo duì lǐ',
  '森林广场': 'sēn lín guǎng chǎng',
  '欢聚一堂': 'huān jù yì táng',
  '水田里的': 'shuǐ tián lǐ de',
  '没吃早饭': 'méi chī zǎo fàn',
  '没有斧头': 'méi yǒu fǔ tóu',
  '渐渐升高': 'jiàn jiàn shēng gāo',
  '火红火红': 'huǒ hóng huǒ hóng',
  '燕子伯伯': 'yàn zi bó bo',
  '燕子姐姐': 'yàn zi jiě jie',
  '燕子弟弟': 'yàn zi dì di',
  '燕子累了': 'yàn zi lèi le',
  '燕子阿姨': 'yàn zi ā yí',
  '狐狸走了': 'hú li zǒu le',
  '独一无二': 'dú yī wú èr',
  '白白的云': 'bái bái de yún',
  '石头下面': 'shí tou xià miàn',
  '碧绿碧绿': 'bì lǜ bì lǜ',
  '空中飞的': 'kōng zhōng fēi de',
  '红色国旗': 'hóng sè guó qí',
  '自己的脚': 'zì jǐ de jiǎo',
  '花对树，': 'huā duì shù',
  '莲叶中间': 'lián yè zhōng jiān',
  '血浓于水': 'xuè nóng yú shuǐ',
  '谁会游？': 'shuí huì yóu',
  '谁会跑？': 'shuí huì pǎo',
  '谁会飞？': 'shuí huì fēi',
  '跑出去玩': 'pǎo chū qù wán',
  '都很孤单': 'dōu hěn gū dān',
  '都很快乐': 'dōu hěn kuài lè',
  '都很生气': 'dōu hěn shēng qì',
  '金黄金黄': 'jīn huáng jīn huáng',
  '雪对霜。': 'xuě duì shuāng',
  '雪白雪白': 'xuě bái xuě bái',
  '非常后悔': 'fēi cháng hòu huǐ',
  '非常生气': 'fēi cháng shēng qì',
  '非常高兴': 'fēi cháng gāo xìng',
  '颜料和笔': 'yán liào hé bǐ',
  '骑自行车': 'qí zì xíng chē',
  '鸭子哥哥': 'yā zi gē ge',
  '鸭子妹妹': 'yā zi mèi mei',
  '鸭子姐姐': 'yā zi jiě jie',
  '鸭子弟弟': 'yā zi dì di',
  '黄星红旗': 'huáng xīng hóng qí',
  '《三字经》': 'sān zì jīng',
  '《千字文》': 'qiān zì wén',
  '《弟子规》': 'dì zǐ guī',
  '《百家姓》': 'bǎi jiā xìng',
  '一下子没了': 'yí xià zi méi le',
  '一个大西瓜': 'yí gè dà xī guā',
  '一点也不小': 'yì diǎn yě bù xiǎo',
  '下起了大雪': 'xià qǐ le dà xuě',
  '不敢往外瞧': 'bù gǎn wǎng wài qiáo',
  '乌鸦不口渴': 'wū yā bù kǒu kě',
  '书包和文具': 'shū bāo hé wén jù',
  '事情做不好': 'shì qing zuò bù hǎo',
  '什么也没有': 'shén me yě méi yǒu',
  '他不会画画': 'tā bú huì huà huà',
  '出来找朋友': 'chū lái zhǎo péng you',
  '出来捉虫子': 'chū lái zhuō chóng zi',
  '出来晒太阳': 'chū lái shài tài yáng',
  '去小河边喝': 'qù xiǎo hé biān hē',
  '去找小白兔': 'qù zhǎo xiǎo bái tù',
  '双手和大脑': 'shuāng shǒu hé dà nǎo',
  '双脚和嘴巴': 'shuāng jiǎo hé zuǐ ba',
  '变成了小河': 'biàn chéng le xiǎo hé',
  '叶子掉光了': 'yè zi diào guāng le',
  '唱得很好听': 'chàng de hěn hǎo tīng',
  '啥也办不到': 'shá yě bàn bú dào',
  '喜鹊飞走了': 'xǐ què fēi zǒu le',
  '圆圆的石头': 'yuán yuán de shí tou',
  '在树下唱歌': 'zài shù xià chàng gē',
  '在河边喝水': 'zài hé biān hē shuǐ',
  '在窝里睡觉': 'zài wō lǐ shuì jiào',
  '地里的小草': 'dì lǐ de xiǎo cǎo',
  '坐公共汽车': 'zuò gōng gòng qì chē',
  '天上的太阳': 'tiān shang de tài yáng',
  '天气太冷了': 'tiān qì tài lěng le',
  '好多好多树': 'hǎo duō hǎo duō shù',
  '好多好多花': 'hǎo duō hǎo duō huā',
  '妈妈的手绢': 'mā ma de shǒu juàn',
  '姥姥的厨房': 'lǎo lao de chú fáng',
  '宽宽的公路': 'kuān kuān de gōng lù',
  '寻隐者不遇': 'xún yǐn zhě bú yù',
  '小河里的船': 'xiǎo hé lǐ de chuán',
  '弯弯的小河': 'wān wān de xiǎo hé',
  '弯弯的月儿': 'wān wān de yuè er',
  '影子在前，': 'yǐng zi zài qián',
  '影子在左，': 'yǐng zi zài zuǒ',
  '很远的地方': 'hěn yuǎn de dì fang',
  '忘了带书包': 'wàng le dài shū bāo',
  '才能有创造': 'cái néng yǒu chuàng zào',
  '才能长得高': 'cái néng zhǎng de gāo',
  '打雷的声音': 'dǎ léi de shēng yīn',
  '找不到虫子': 'zhǎo bú dào chóng zi',
  '把瓶子推倒': 'bǎ píng zi tuī dǎo',
  '断成了两半': 'duàn chéng le liǎng bàn',
  '木瓜熟了。': 'mù guā shú le',
  '树上的果子': 'shù shang de guǒ zi',
  '没有尾巴了': 'méi yǒu wěi ba le',
  '洁白的雪莲': 'jié bái de xuě lián',
  '燕子要回家': 'yàn zi yào huí jiā',
  '爸爸开车送': 'bà ba kāi chē sòng',
  '爸爸的拖鞋': 'bà ba de tuō xié',
  '瓶子太重了': 'píng zi tài zhòng le',
  '用脚踢进去': 'yòng jiǎo tī jìn qù',
  '白白的糯米': 'bái bái de nuò mǐ',
  '白白的面粉': 'bái bái de miàn fěn',
  '盘中的饭菜': 'pán zhōng de fàn cài',
  '眼睛和耳朵': 'yǎn jing hé ěr duo',
  '粉粉的荷花': 'fěn fěn de hé huā',
  '红红的桃花': 'hóng hóng de táo huā',
  '绿绿的草地': 'lǜ lǜ de cǎo dì',
  '绿绿的青菜': 'lǜ lǜ de qīng cài',
  '美丽的天山': 'měi lì de tiān shān',
  '老鹰捉小鸡': 'lǎo yīng zhuō xiǎo jī',
  '肉掉了下来': 'ròu diào le xià lái',
  '自己家门口': 'zì jǐ jiā mén kǒu',
  '自己的小手': 'zì jǐ de xiǎo shǒu',
  '自己的尾巴': 'zì jǐ de wěi ba',
  '自己的背上': 'zì jǐ de bèi shang',
  '自己种白菜': 'zì jǐ zhòng bái cài',
  '草芽尖尖，': 'cǎo yá jiān jiān',
  '荷叶圆圆，': 'hé yè yuán yuán',
  '被风吹断了': 'bèi fēng chuī duàn le',
  '请朋友帮忙': 'qǐng péng you bāng máng',
  '谷穗弯弯，': 'gǔ suì wān wān',
  '长长的海带': 'cháng cháng de hǎi dài',
  '闪闪的星星': 'shǎn shǎn de xīng xing',
  '马上跑回家': 'mǎ shàng pǎo huí jiā',
  '高高的大山': 'gāo gāo de dà shān',
  '黄黄的菊花': 'huáng huáng de jú huā',
  '黄黄的鸡蛋': 'huáng huáng de jī dàn',
  '一二三四五，': 'yī èr sān sì wǔ',
  '一人不成众，': 'yì rén bù chéng zhòng',
  '一把一把地扔': 'yì bǎ yì bǎ de rēng',
  '一点也不在乎': 'yì diǎn yě bú zài hu',
  '一颗一颗地放': 'yì kē yì kē de fàng',
  '不解藏踪迹，': 'bù jiě cáng zōng jì',
  '严寒对酷暑，': 'yán hán duì kù shǔ',
  '举头望明月，': 'jǔ tóu wàng míng yuè',
  '人有两件宝，': 'rén yǒu liǎng jiàn bǎo',
  '什么也没有了': 'shén me yě méi yǒu le',
  '今天上午八点': 'jīn tiān shàng wǔ bā diǎn',
  '仔细检查文具': 'zǐ xì jiǎn chá wén jù',
  '他在家里画画': 'tā zài jiā lǐ huà huà',
  '他在河里游泳': 'tā zài hé lǐ yóu yǒng',
  '众人一条心，': 'zhòng rén yì tiáo xīn',
  '你也不肯让，': 'nǐ yě bù kěn ràng',
  '你们饿了吗？': 'nǐ men è le ma',
  '兔子摔了一跤': 'tù zi shuāi le yì jiāo',
  '公共汽车坏了': 'gōng gòng qì chē huài le',
  '又疑瑶台镜，': 'yòu yí yáo tái jìng',
  '双手会做工，': 'shuāng shǒu huì zuò gōng',
  '只在此山中，': 'zhǐ zài cǐ shān zhōng',
  '和风对细雨，': 'hé fēng duì xì yǔ',
  '哪个是水果？': 'nǎ ge shì shuǐ guǒ',
  '哪个是蔬菜？': 'nǎ ge shì shū cài',
  '多睡了一分钟': 'duō shuì le yì fēn zhōng',
  '夜来风雨声，': 'yè lái fēng yǔ shēng',
  '大脑会思考。': 'dà nǎo huì sī kǎo',
  '天地分上下，': 'tiān dì fēn shàng xià',
  '天天起得早，': 'tiān tiān qǐ de zǎo',
  '天阴沉沉的，': 'tiān yīn chén chén de',
  '小娃撑小艇，': 'xiǎo wá chēng xiǎo tǐng',
  '小时不识月，': 'xiǎo shí bù shí yuè',
  '山清对水秀，': 'shān qīng duì shuǐ xiù',
  '床前明月光，': 'chuáng qián míng yuè guāng',
  '影子像什么？': 'yǐng zi xiàng shén me',
  '房前花果香，': 'fáng qián huā guǒ xiāng',
  '明天上午八点': 'míng tiān shàng wǔ bā diǎn',
  '明天下午八点': 'míng tiān xià wǔ bā diǎn',
  '明天晚上八点': 'míng tiān wǎn shang bā diǎn',
  '春去花还在，': 'chūn qù huā hái zài',
  '春暖对秋凉。': 'chūn nuǎn duì qiū liáng',
  '春眠不觉晓，': 'chūn mián bù jué xiǎo',
  '有手轻轻抱。': 'yǒu shǒu qīng qīng bào',
  '有水把茶泡。': 'yǒu shuǐ bǎ chá pào',
  '有火放鞭炮。': 'yǒu huǒ fàng biān pào',
  '有衣穿长袍，': 'yǒu yī chuān cháng páo',
  '有足快快跑，': 'yǒu zú kuài kuài pǎo',
  '有雨山戴帽，': 'yǒu yǔ shān dài mào',
  '有饭能吃饱，': 'yǒu fàn néng chī bǎo',
  '朝霞对夕阳。': 'zhāo xiá duì xī yáng',
  '松下问童子，': 'sōng xià wèn tóng zǐ',
  '柳绿对桃红。': 'liǔ lǜ duì táo hóng',
  '树上没有叶子': 'shù shang méi yǒu yè zi',
  '江南可采莲，': 'jiāng nán kě cǎi lián',
  '浪花像什么？': 'làng huā xiàng shén me',
  '淘气的小娃娃': 'táo qì de xiǎo wá wa',
  '燕子在找妈妈': 'yàn zi zài zhǎo mā ma',
  '瓶子里没有水': 'píng zi lǐ méi yǒu shuǐ',
  '白毛浮绿水，': 'bái máo fú lǜ shuǐ',
  '红掌拨清波。': 'hóng zhǎng bō qīng bō',
  '莺歌对燕舞，': 'yīng gē duì yàn wǔ',
  '蜜蜂来采蜜，': 'mì fēng lái cǎi mì',
  '被小狗踩断了': 'bèi xiǎo gǒu cǎi duàn le',
  '被弟弟拿走了': 'bèi dì di ná zǒu le',
  '被石头压断了': 'bèi shí tou yā duàn le',
  '解落三秋叶，': 'jiě luò sān qiū yè',
  '课本作业本，': 'kè běn zuò yè běn',
  '谁不会游泳？': 'shuí bú huì yóu yǒng',
  '谁来送李白？': 'shuí lái sòng lǐ bái',
  '谁没有参加？': 'shuí méi yǒu cān jiā',
  '谁画了月牙？': 'shuí huà le yuè yá',
  '谁画了枫叶？': 'shuí huà le fēng yè',
  '谁画了梅花？': 'shuí huà le méi huā',
  '谁画了竹叶？': 'shuí huà le zhú yè',
  '谁的尾巴弯？': 'shuí de wěi ba wān',
  '谁的尾巴扁？': 'shuí de wěi ba biǎn',
  '谁的尾巴短？': 'shuí de wěi ba duǎn',
  '谁的尾巴长？': 'shuí de wěi ba cháng',
  '谁知盘中餐，': 'shuí zhī pán zhōng cān',
  '谁跑得最快？': 'shuí pǎo de zuì kuài',
  '过江千尺浪，': 'guò jiāng qiān chǐ làng',
  '远看山有色，': 'yuǎn kàn shān yǒu sè',
  '铅笔转笔刀。': 'qiān bǐ zhuàn bǐ dāo',
  '锄禾日当午，': 'chú hé rì dāng wǔ',
  '雄伟的天安门': 'xióng wěi de tiān ān mén',
  '马儿怎样跑？': 'mǎ er zěn yàng pǎo',
  '鱼儿怎样游？': 'yú er zěn yàng yóu',
  '鱼戏莲叶间。': 'yú xì lián yè jiān',
  '鸟儿怎样飞？': 'niǎo er zěn yàng fēi',
  '鸟语对花香。': 'niǎo yǔ duì huā xiāng',
  '鹅在哪里游？': 'é zài nǎ lǐ yóu',
  '「人」和「一」': 'rén hé yī',
  '「入」和「口」': 'rù hé kǒu',
  '「八」和「十」': 'bā hé shí',
  '「大」和「二」': 'dà hé èr',
  '一下子全倒进去': 'yí xià zi quán dǎo jìn qù',
  '他在洞里睡着了': 'tā zài dòng lǐ shuì zháo le',
  '你们要去哪里？': 'nǐ men yào qù nǎ lǐ',
  '你写作业了吗？': 'nǐ xiě zuò yè le ma',
  '十四不是四十。': 'shí sì bú shì sì shí',
  '向老山羊要白菜': 'xiàng lǎo shān yáng yào bái cài',
  '啊！秋天来了！': 'a qiū tiān lái le',
  '四十不是十四，': 'sì shí bú shì shí sì',
  '四脚腾空仰天叫': 'sì jiǎo téng kōng yǎng tiān jiào',
  '大会在哪里开？': 'dà huì zài nǎ lǐ kāi',
  '大象走路的声音': 'dà xiàng zǒu lù de shēng yīn',
  '大雁往哪里飞？': 'dà yàn wǎng nǎ lǐ fēi',
  '小青蛙吃什么？': 'xiǎo qīng wā chī shén me',
  '我在哪里玩耍？': 'wǒ zài nǎ lǐ wán shuǎ',
  '扇扇翅膀去又回': 'shān shān chì bǎng qù yòu huí',
  '摇摇尾巴摆摆头': 'yáo yáo wěi ba bǎi bǎi tóu',
  '有花有草的地方': 'yǒu huā yǒu cǎo de dì fang',
  '用梳子做什么？': 'yòng shū zi zuò shén me',
  '用毛巾做什么？': 'yòng máo jīn zuò shén me',
  '用牙刷做什么？': 'yòng yá shuā zuò shén me',
  '用脸盆做什么？': 'yòng liǎn pén zuò shén me',
  '用香皂做什么？': 'yòng xiāng zào zuò shén me',
  '白菜粽和萝卜粽': 'bái cài zòng hé luó bo zòng',
  '石头落地的声音': 'shí tou luò dì de shēng yīn',
  '红豆粽和鲜肉粽': 'hóng dòu zòng hé xiān ròu zòng',
  '花儿喜欢什么？': 'huā er xǐ huan shén me',
  '花儿喜欢太阳，': 'huā er xǐ huan tài yáng',
  '苹果粽和香蕉粽': 'píng guǒ zòng hé xiāng jiāo zòng',
  '谁先去拔萝卜？': 'shuí xiān qù bá luó bo',
  '谁拦住了大家？': 'shuí lán zhù le dà jiā',
  '还是什么也没有': 'hái shì shén me yě méi yǒu',
  '这里只有一棵树': 'zhè lǐ zhǐ yǒu yì kē shù',
  '野牛讲了个笑话': 'yě niú jiǎng le gè xiào huà',
  '鸟儿喜欢什么？': 'niǎo er xǐ huan shén me',
  '鸟儿喜欢蓝天，': 'niǎo er xǐ huan lán tiān',
  '鸡蛋粽和面条粽': 'jī dàn zòng hé miàn tiáo zòng',
  '一动一动总在笑。': 'yí dòng yí dòng zǒng zài xiào',
  '一只乌鸦口渴了，': 'yì zhī wū yā kǒu kě le',
  '一只船，扬起帆，': 'yì zhī chuán yáng qǐ fān',
  '一寸光阴一寸金，': 'yí cùn guāng yīn yí cùn jīn',
  '一年之计在于春，': 'yì nián zhī jì zài yú chūn',
  '一片两片三四片，': 'yí piàn liǎng piàn sān sì piàn',
  '一群大雁往南飞，': 'yì qún dà yàn wǎng nán fēi',
  '一起走到小桥上。': 'yì qǐ zǒu dào xiǎo qiáo shang',
  '三瓣嘴，胡子翘，': 'sān bàn zuǐ hú zi qiào',
  '上午　下午　晚上': 'shàng wǔ xià wǔ wǎn shang',
  '不用颜料不用笔，': 'bú yòng yán liào bú yòng bǐ',
  '九片十片无数片，': 'jiǔ piàn shí piàn wú shù piàn',
  '二人从，三人众。': 'èr rén cóng sān rén zhòng',
  '二十九，蒸馒头。': 'èr shí jiǔ zhēng mán tou',
  '二十六，去买肉。': 'èr shí liù qù mǎi ròu',
  '二十四，扫房子。': 'èr shí sì sǎo fáng zi',
  '云对雨，雪对风。': 'yún duì yǔ xuě duì fēng',
  '人不学，不知义。': 'rén bù xué bù zhī yì',
  '人之初，性本善。': 'rén zhī chū xìng běn shàn',
  '什么张？弓长张。': 'shén me zhāng gōng cháng zhāng',
  '什么李？木子李。': 'shén me lǐ mù zǐ lǐ',
  '他们找到了好吃的': 'tā men zhǎo dào le hǎo chī de',
  '伸出双手紧紧握，': 'shēn chū shuāng shǒu jǐn jǐn wò',
  '保护禾苗吃害虫。': 'bǎo hù hé miáo chī hài chóng',
  '借到了小鱼的尾巴': 'jiè dào le xiǎo yú de wěi ba',
  '借到了老牛的尾巴': 'jiè dào le lǎo niú de wěi ba',
  '做了不少好事情。': 'zuò le bù shǎo hǎo shì qing',
  '做对了，走过桥，': 'zuò duì le zǒu guò qiáo',
  '元元打了个哈欠，': 'yuán yuán dǎ le gè hā qian',
  '兰兰画的是什么？': 'lán lán huà de shì shén me',
  '几步就成一幅画。': 'jǐ bù jiù chéng yì fú huà',
  '刨刨土，捉捉虫，': 'páo páo tǔ zhuō zhuō chóng',
  '医生在哪里工作？': 'yī shēng zài nǎ lǐ gōng zuò',
  '去年　今年　明年': 'qù nián jīn nián míng nián',
  '双人徐，言午许。': 'shuāng rén xú yán wǔ xǔ',
  '双木林，三木森。': 'shuāng mù lín sān mù sēn',
  '古月胡，口天吴，': 'gǔ yuè hú kǒu tiān wú',
  '叶子上有许多蚜虫': 'yè zi shang yǒu xǔ duō yá chóng',
  '吃水不忘挖井人，': 'chī shuǐ bú wàng wā jǐng rén',
  '周、吴、郑、王，': 'zhōu wú zhèng wáng',
  '哪个动作要用手？': 'nǎ ge dòng zuò yào yòng shǒu',
  '哪个动作要用脚？': 'nǎ ge dòng zuò yào yòng jiǎo',
  '哪个字是提手旁？': 'nǎ ge zì shì tí shǒu páng',
  '哪个字是足字旁？': 'nǎ ge zì shì zú zì páng',
  '四是四，十是十。': 'sì shì sì shí shì shí',
  '国旗上有几颗星？': 'guó qí shàng yǒu jǐ kē xīng',
  '大河弯弯流入海，': 'dà hé wān wān liú rù hǎi',
  '天天锻炼身体好。': 'tiān tiān duàn liàn shēn tǐ hǎo',
  '头上红冠不用裁，': 'tóu shàng hóng guān bú yòng cái',
  '好让禾苗不生病。': 'hǎo ràng hé miáo bù shēng bìng',
  '子不学，非所宜。': 'zǐ bù xué fēi suǒ yí',
  '它是我的好朋友。': 'tā shì wǒ de hǎo péng you',
  '小大尖，小土尘。': 'xiǎo dà jiān xiǎo tǔ chén',
  '小小青蛙大眼睛。': 'xiǎo xiǎo qīng wā dà yǎn jing',
  '小手洗得真干净，': 'xiǎo shǒu xǐ de zhēn gān jìng',
  '小河是鱼儿的家，': 'xiǎo hé shì yú er de jiā',
  '小溪弯弯出青山。': 'xiǎo xī wān wān chū qīng shān',
  '小狗喊谁来帮忙？': 'xiǎo gǒu hǎn shuí lái bāng máng',
  '小狗画的是什么？': 'xiǎo gǒu huà de shì shén me',
  '小白兔，穿皮袄，': 'xiǎo bái tù chuān pí ǎo',
  '小荷才露尖尖角，': 'xiǎo hé cái lù jiān jiān jiǎo',
  '小马画的是什么？': 'xiǎo mǎ huà de shì shén me',
  '小鸟在前面带路，': 'xiǎo niǎo zài qián miàn dài lù',
  '小鸟飞得真低呀！': 'xiǎo niǎo fēi de zhēn dī ya',
  '小鸡画的是什么？': 'xiǎo jī huà de shì shén me',
  '小鸭画的是什么？': 'xiǎo yā huà de shì shén me',
  '小黄鸡，小黑鸡，': 'xiǎo huáng jī xiǎo hēi jī',
  '山路弯弯到校园。': 'shān lù wān wān dào xiào yuán',
  '左右相遇起凉风。': 'zuǒ yòu xiāng yù qǐ liáng fēng',
  '左边绿，右边红，': 'zuǒ biān lǜ yòu biān hóng',
  '平生不敢轻言语，': 'píng shēng bù gǎn qīng yán yǔ',
  '幼不学，老何为？': 'yòu bù xué lǎo hé wéi',
  '影子是我的什么？': 'yǐng zi shì wǒ de shén me',
  '快快乐乐过了桥。': 'kuài kuài lè lè guò le qiáo',
  '性相近，习相远。': 'xìng xiāng jìn xí xiāng yuǎn',
  '想一想，算一算，': 'xiǎng yi xiǎng suàn yi suàn',
  '我们像春天一样，': 'wǒ men xiàng chūn tiān yí yàng',
  '扑通掉进河中央。': 'pū tōng diào jìn hé zhōng yāng',
  '排着队，向前走，': 'pái zhe duì xiàng qián zǒu',
  '接来台湾小朋友，': 'jiē lái tái wān xiǎo péng you',
  '操场上，真热闹。': 'cāo chǎng shàng zhēn rè nao',
  '教之道，贵以专。': 'jiào zhī dào guì yǐ zhuān',
  '数学题，一道道。': 'shù xué tí yí dào dào',
  '文具的家是什么？': 'wén jù de jiā shì shén me',
  '日月明，田力男。': 'rì yuè míng tián lì nán',
  '早晨下雨当日晴，': 'zǎo chén xià yǔ dàng rì qíng',
  '昨天　今天　明天': 'zuó tiān jīn tiān míng tiān',
  '月儿弯弯挂蓝天，': 'yuè er wān wān guà lán tiān',
  '李白乘舟将欲行，': 'lǐ bái chéng zhōu jiāng yù xíng',
  '树林是小鸟的家，': 'shù lín shì xiǎo niǎo de jiā',
  '桃子长得怎么样？': 'táo zi zhǎng de zěn me yàng',
  '桃花潭水深千尺，': 'táo huā tán shuǐ shēn qiān chǐ',
  '桥东走来一只羊，': 'qiáo dōng zǒu lái yì zhī yáng',
  '欢欢喜喜在一起。': 'huān huān xǐ xǐ zài yì qǐ',
  '毛巾给我擦擦手。': 'máo jīn gěi wǒ cā cā shǒu',
  '河水清清天气晴，': 'hé shuǐ qīng qīng tiān qì qíng',
  '沿着宽宽的公路，': 'yán zhe kuān kuān de gōng lù',
  '沿着弯弯的小路，': 'yán zhe wān wān de xiǎo lù',
  '泉眼无声惜细流，': 'quán yǎn wú shēng xī xì liú',
  '泥土是种子的家。': 'ní tǔ shì zhǒng zi de jiā',
  '清水帮我冲冲手，': 'qīng shuǐ bāng wǒ chōng chōng shǒu',
  '漂啊漂啊到台湾。': 'piāo a piāo a dào tái wān',
  '玉不琢，不成器。': 'yù bù zhuó bù chéng qì',
  '玉米结得怎么样？': 'yù mǐ jié de zěn me yàng',
  '站如松，坐如钟。': 'zhàn rú sōng zuò rú zhōng',
  '等号就像一座桥。': 'děng hào jiù xiàng yí zuò qiáo',
  '红的最怕水来攻。': 'hóng de zuì pà shuǐ lái gōng',
  '绿的喜欢及时雨，': 'lǜ de xǐ huan jí shí yǔ',
  '老师在哪里工作？': 'lǎo shī zài nǎ lǐ gōng zuò',
  '耳朵长，尾巴小。': 'ěr duo cháng wěi ba xiǎo',
  '肥皂用来搓搓手，': 'féi zào yòng lái cuō cuō shǒu',
  '花儿在哪里开放？': 'huā er zài nǎ lǐ kāi fàng',
  '花对树，鸟对虫。': 'huā duì shù niǎo duì chóng',
  '苟不教，性乃迁。': 'gǒu bú jiào xìng nǎi qiān',
  '草芽是对谁说的？': 'cǎo yá shì duì shuí shuō de',
  '荷叶是对谁说的？': 'hé yè shì duì shuí shuō de',
  '蓝天是白云的家，': 'lán tiān shì bái yún de jiā',
  '蚂蚁地上运食粮。': 'mǎ yǐ dì shang yùn shí liáng',
  '蚂蚁搬家蛇过道，': 'mǎ yǐ bān jiā shé guò dào',
  '蚯蚓土里造宫殿，': 'qiū yǐn tǔ lǐ zào gōng diàn',
  '蜘蛛房前结网忙。': 'zhī zhū fáng qián jié wǎng máng',
  '蜻蜓半空展翅飞，': 'qīng tíng bàn kōng zhǎn chì fēi',
  '蝌蚪池中游得欢，': 'kē dǒu chí zhōng yóu de huān',
  '蝴蝶花间捉迷藏。': 'hú dié huā jiān zhuō mí cáng',
  '行如风，卧如弓。': 'xíng rú fēng wò rú gōng',
  '被蛇咬住，挣断了': 'bèi shé yǎo zhù zhèng duàn le',
  '西瓜长得怎么样？': 'xī guā zhǎng de zěn me yàng',
  '许多人玩，更好！': 'xǔ duō rén wán gèng hǎo',
  '诗人低头想什么？': 'shī rén dī tóu xiǎng shén me',
  '诗人抬头看什么？': 'shī rén tái tóu kàn shén me',
  '请你爱护小青蛙，': 'qǐng nǐ ài hù xiǎo qīng wā',
  '请大家准时参加！': 'qǐng dà jiā zhǔn shí cān jiā',
  '谁在半空展翅飞？': 'shuí zài bàn kōng zhǎn chì fēi',
  '谁在土里造宫殿？': 'shuí zài tǔ lǐ zào gōng diàn',
  '谁在地上运食粮？': 'shuí zài dì shang yùn shí liáng',
  '谁在山坡上割草？': 'shuí zài shān pō shàng gē cǎo',
  '谁在房前结网忙？': 'shuí zài fáng qián jié wǎng máng',
  '谁在池中游得欢？': 'shuí zài chí zhōng yóu de huān',
  '谁在花间捉迷藏？': 'shuí zài huā jiān zhuō mí cáng',
  '谁把蚜虫吃光了？': 'shuí bǎ yá chóng chī guāng le',
  '谁用尾巴赶蝇子？': 'shuí yòng wěi ba gǎn yíng zi',
  '谁的尾巴最好看？': 'shuí de wěi ba zuì hǎo kàn',
  '谁说荷叶是凉伞？': 'shuí shuō hé yè shì liáng sǎn',
  '谁说荷叶是摇篮？': 'shuí shuō hé yè shì yáo lán',
  '谁说荷叶是歌台？': 'shuí shuō hé yè shì gē tái',
  '谁说话「呱呱」？': 'shuí shuō huà guā guā',
  '谁说话「咕咕」？': 'shuí shuō huà gū gū',
  '谁说话「喵喵」？': 'shuí shuō huà miāo miāo',
  '谁说话「嘎嘎」？': 'shuí shuō huà gā gā',
  '赵、钱、孙、李，': 'zhào qián sūn lǐ',
  '跳绳踢毽丢沙包，': 'tiào shéng tī jiàn diū shā bāo',
  '野牛问大象什么？': 'yě niú wèn dà xiàng shén me',
  '铃声响，下课了。': 'líng shēng xiǎng xià kè le',
  '长出了一条新尾巴': 'zhǎng chū le yì tiáo xīn wěi ba',
  '雪人大肚子一挺，': 'xuě rén dà dù zi yì tǐng',
  '青草地上做游戏。': 'qīng cǎo dì shang zuò yóu xì',
  '鸟儿在哪里飞翔？': 'niǎo er zài nǎ lǐ fēi xiáng',
  '丁零零，闹钟响了。': 'dīng líng líng nào zhōng xiǎng le',
  '乌鸦嘴里叼着什么？': 'wū yā zuǐ lǐ diāo zhe shén me',
  '乌鸦看见一个瓶子，': 'wū yā kàn jiàn yí gè píng zi',
  '人们在江南做什么？': 'rén men zài jiāng nán zuò shén me',
  '人的两件宝是什么？': 'rén de liǎng jiàn bǎo shì shén me',
  '元元为什么迟到了？': 'yuán yuán wèi shén me chí dào le',
  '元元多睡了几分钟？': 'yuán yuán duō shuì le jǐ fēn zhōng',
  '兔子的尾巴怎么样？': 'tù zi de wěi ba zěn me yàng',
  '公鸡的尾巴怎么样？': 'gōng jī de wěi ba zěn me yàng',
  '夏天，用什么扇风？': 'xià tiān yòng shén me shān fēng',
  '大会在什么时候开？': 'dà huì zài shén me shí hou kāi',
  '大雨点儿要去哪里？': 'dà yǔ diǎn r yào qù nǎ lǐ',
  '天那么蓝，那么高。': 'tiān nà me lán nà me gāo',
  '小壁虎叫小鱼什么？': 'xiǎo bì hǔ jiào xiǎo yú shén me',
  '小壁虎叫燕子什么？': 'xiǎo bì hǔ jiào yàn zi shén me',
  '小壁虎叫老牛什么？': 'xiǎo bì hǔ jiào lǎo niú shén me',
  '小姑娘喊谁来帮忙？': 'xiǎo gū niang hǎn shuí lái bāng máng',
  '小小的船儿两头尖。': 'xiǎo xiǎo de chuán er liǎng tóu jiān',
  '小熊一家住在哪里？': 'xiǎo xióng yì jiā zhù zài nǎ lǐ',
  '小雨点儿要去哪里？': 'xiǎo yǔ diǎn r yào qù nǎ lǐ',
  '我从前胆子怎么样？': 'wǒ cóng qián dǎn zi zěn me yàng',
  '我们是祖国的花朵，': 'wǒ men shì zǔ guó de huā duǒ',
  '我们的国旗叫什么？': 'wǒ men de guó qí jiào shén me',
  '我在小小的船里坐，': 'wǒ zài xiǎo xiǎo de chuán lǐ zuò',
  '打着招呼一起飞出去': 'dǎ zhe zhāo hu yì qǐ fēi chū qù',
  '把小石子放进瓶子里': 'bǎ xiǎo shí zǐ fàng jìn píng zi lǐ',
  '新的铅笔、新的橡皮': 'xīn de qiān bǐ xīn de xiàng pí',
  '木瓜掉进湖里的声音': 'mù guā diào jìn hú lǐ de shēng yīn',
  '没有花没有草的地方': 'méi yǒu huā méi yǒu cǎo de dì fang',
  '热情的话儿说不完。': 'rè qíng de huà er shuō bù wán',
  '狗熊用喇叭大声喊：': 'gǒu xióng yòng lǎ ba dà shēng hǎn',
  '猴子的尾巴怎么样？': 'hóu zi de wěi ba zěn me yàng',
  '祖国就是我们的家。': 'zǔ guó jiù shì wǒ men de jiā',
  '竹篮打水——一场空': 'zhú lán dǎ shuǐ yì cháng kōng',
  '粽子是用什么包的？': 'zòng zi shì yòng shén me bāo de',
  '粽子里面裹着什么？': 'zòng zi lǐ miàn guǒ zhe shén me',
  '红红的花、绿绿的草': 'hóng hóng de huā lǜ lǜ de cǎo',
  '老公公喊谁来帮忙？': 'lǎo gōng gong hǎn shuí lái bāng máng',
  '老婆婆喊谁来帮忙？': 'lǎo pó po hǎn shuí lái bāng máng',
  '老虎让谁通知大家？': 'lǎo hǔ ràng shuí tōng zhī dà jiā',
  '芝麻开花——节节高': 'zhī má kāi huā jié jié gāo',
  '花儿在阳光下开放。': 'huā er zài yáng guāng xià kāi fàng',
  '花更红了，草更绿了': 'huā gèng hóng le cǎo gèng lǜ le',
  '要数我们的小学堂。': 'yào shǔ wǒ men de xiǎo xué táng',
  '谁说「我是冬天」？': 'shuí shuō wǒ shì dōng tiān',
  '谁说「我是夏天」？': 'shuí shuō wǒ shì xià tiān',
  '谁说「我是春天」？': 'shuí shuō wǒ shì chūn tiān',
  '谁说「我是秋天」？': 'shuí shuō wǒ shì qiū tiān',
  '谁说荷叶是停机坪？': 'shuí shuō hé yè shì tíng jī píng',
  '贝贝的铅笔怎么了？': 'bèi bèi de qiān bǐ zěn me le',
  '遥远的北京有什么？': 'yáo yuǎn de běi jīng yǒu shén me',
  '遥远的新疆有什么？': 'yáo yuǎn de xīn jiāng yǒu shén me',
  '雪山上盛开着什么？': 'xuě shān shàng shèng kāi zhe shén me',
  '青蛙为什么没参加？': 'qīng wā wèi shén me méi cān jiā',
  '鱼在哪里游来游去？': 'yú zài nǎ lǐ yóu lái yóu qù',
  '鸟儿在天空中飞翔。': 'niǎo er zài tiān kōng zhōng fēi xiáng',
  '鸭子的尾巴怎么样？': 'yā zi de wěi ba zěn me yàng',
  '「咕咚」是什么声音？': 'gū dōng shì shén me shēng yīn',
  '一日无书，百事荒芜。': 'yí rì wú shū bǎi shì huāng wú',
  '下雨前，谁飞得很低？': 'xià yǔ qián shuí fēi de hěn dī',
  '不知则问，不能则学。': 'bù zhī zé wèn bù néng zé xué',
  '中间有一颗红红的枣。': 'zhōng jiān yǒu yì kē hóng hóng de zǎo',
  '乌鸦为什么喝不着水？': 'wū yā wèi shén me hē bù zháo shuǐ',
  '乌鸦想出了什么办法？': 'wū yā xiǎng chū le shén me bàn fǎ',
  '从前，这里有几棵树？': 'cóng qián zhè lǐ yǒu jǐ kē shù',
  '你讲我听，我讲你听。': 'nǐ jiǎng wǒ tīng wǒ jiǎng nǐ tīng',
  '前人栽树，后人乘凉。': 'qián rén zāi shù hòu rén chéng liáng',
  '前面是东，后面是西。': 'qián miàn shì dōng hòu miàn shì xī',
  '千里之行，始于足下。': 'qiān lǐ zhī xíng shǐ yú zú xià',
  '后来，这里种了什么？': 'hòu lái zhè lǐ zhòng le shén me',
  '向着国旗，我们立正。': 'xiàng zhe guó qí wǒ men lì zhèng',
  '哪个字像圆圆的太阳？': 'nǎ ge zì xiàng yuán yuán de tài yáng',
  '哪个字像流动的河水？': 'nǎ ge zì xiàng liú dòng de hé shuǐ',
  '哪个字和看东西有关？': 'nǎ ge zì hé kàn dōng xi yǒu guān',
  '国歌声中，徐徐升起。': 'guó gē shēng zhōng xú xú shēng qǐ',
  '在工厂里做工的是谁？': 'zài gōng chǎng lǐ zuò gōng de shì shuí',
  '外婆什么时候煮粽子？': 'wài pó shén me shí hou zhǔ zòng zi',
  '天一黑，我就怎么样？': 'tiān yì hēi wǒ jiù zěn me yàng',
  '天安门前的人非常多。': 'tiān ān mén qián de rén fēi cháng duō',
  '天气凉了，树叶黄了，': 'tiān qì liáng le shù yè huáng le',
  '小公鸡叫小鸭子什么？': 'xiǎo gōng jī jiào xiǎo yā zi shén me',
  '小壁虎先向谁借尾巴？': 'xiǎo bì hǔ xiān xiàng shuí jiè wěi ba',
  '小壁虎在墙角捉蚊子，': 'xiǎo bì hǔ zài qiáng jiǎo zhuō wén zi',
  '小壁虎最后怎么样了？': 'xiǎo bì hǔ zuì hòu zěn me yàng le',
  '小水珠说荷叶是什么？': 'xiǎo shuǐ zhū shuō hé yè shì shén me',
  '小猴子先走到了哪里？': 'xiǎo hóu zi xiān zǒu dào le nǎ lǐ',
  '小画家们用什么画画？': 'xiǎo huà jiā men yòng shén me huà huà',
  '小白兔在山坡上割草。': 'xiǎo bái tù zài shān pō shàng gē cǎo',
  '小蜻蜓说荷叶是什么？': 'xiǎo qīng tíng shuō hé yè shì shén me',
  '小青蛙保护的是什么？': 'xiǎo qīng wā bǎo hù de shì shén me',
  '小青蛙说荷叶是什么？': 'xiǎo qīng wā shuō hé yè shì shén me',
  '小鱼儿说荷叶是什么？': 'xiǎo yú er shuō hé yè shì shén me',
  '小鱼的尾巴有什么用？': 'xiǎo yú de wěi ba yǒu shén me yòng',
  '小鸭子叫小公鸡什么？': 'xiǎo yā zi jiào xiǎo gōng jī shén me',
  '左面是北，右面是南。': 'zuǒ miàn shì běi yòu miàn shì nán',
  '弯弯的月儿小小的船。': 'wān wān de yuè er xiǎo xiǎo de chuán',
  '影子在前，影子在后，': 'yǐng zi zài qián yǐng zi zài hòu',
  '影子在左，影子在右，': 'yǐng zi zài zuǒ yǐng zi zài yòu',
  '悄悄地挠我的小脚丫。': 'qiāo qiāo de náo wǒ de xiǎo jiǎo yā',
  '我从前胆子很小很小，': 'wǒ cóng qián dǎn zi hěn xiǎo hěn xiǎo',
  '早晨起来，面向太阳。': 'zǎo chén qǐ lái miàn xiàng tài yáng',
  '望着国旗，我们敬礼。': 'wàng zhe guó qí wǒ men jìng lǐ',
  '李白坐着什么要走了？': 'lǐ bái zuò zhe shén me yào zǒu le',
  '松鼠的尾巴好像什么？': 'sōng shǔ de wěi ba hǎo xiàng shén me',
  '棉花姑娘生了什么病？': 'mián huā gū niang shēng le shén me bìng',
  '浪花给我捧来了什么？': 'làng huā gěi wǒ pěng lái le shén me',
  '燕子会捉哪里的害虫？': 'yàn zi huì zhuō nǎ lǐ de hài chóng',
  '燕子的尾巴有什么用？': 'yàn zi de wěi ba yǒu shén me yòng',
  '百尺竿头，更进一步。': 'bǎi chǐ gān tóu gèng jìn yí bù',
  '种瓜得瓜，种豆得豆。': 'zhòng guā dé guā zhòng dòu dé dòu',
  '老牛的尾巴有什么用？': 'lǎo niú de wěi ba yǒu shén me yòng',
  '花生的果实长在哪里？': 'huā shēng de guǒ shí zhǎng zài nǎ lǐ',
  '荷叶圆圆的，绿绿的。': 'hé yè yuán yuán de lǜ lǜ de',
  '讲故事得有人听才行，': 'jiǎng gù shi děi yǒu rén tīng cái xíng',
  '读万卷书，行万里路。': 'dú wàn juàn shū xíng wàn lǐ lù',
  '谁最先听见「咕咚」？': 'shuí zuì xiān tīng jiàn gū dōng',
  '谁游到水面上来透气？': 'shuí yóu dào shuǐ miàn shàng lái tòu qì',
  '谁的尾巴好像一把伞？': 'shuí de wěi ba hǎo xiàng yì bǎ sǎn',
  '跟水有关的是哪个字？': 'gēn shuǐ yǒu guān de shì nǎ ge zì',
  '迎风飘扬，多么美丽。': 'yíng fēng piāo yáng duō me měi lì',
  '这个村子叫什么名字？': 'zhè ge cūn zi jiào shén me míng zi',
  '这几句话出自哪本书？': 'zhè jǐ jù huà chū zì nǎ běn shū',
  '里面裹着白白的糯米，': 'lǐ miàn guǒ zhe bái bái de nuò mǐ',
  '闪闪的星星和蓝蓝的天': 'shǎn shǎn de xīng xing hé lán lán de tiān',
  '青青的瓦，白白的墙。': 'qīng qīng de wǎ bái bái de qiáng',
  '鹅的毛是什么颜色的？': 'é de máo shì shén me yán sè de',
  '一会儿排成个“一”字。': 'yí huì r pái chéng gè yī zì',
  '一会儿排成个“人”字，': 'yí huì r pái chéng gè rén zì',
  '一条蛇咬住了他的尾巴。': 'yì tiáo shé yǎo zhù le tā de wěi ba',
  '上个月　这个月　下个月': 'shàng gè yuè zhè ge yuè xià gè yuè',
  '乌鸦是怎样放小石子的？': 'wū yā shì zěn yàng fàng xiǎo shí zǐ de',
  '五星红旗，我们的国旗。': 'wǔ xīng hóng qí wǒ men de guó qí',
  '从前，树上有几个鸟窝？': 'cóng qián shù shang yǒu jǐ gè niǎo wō',
  '从前，树为什么很孤单？': 'cóng qián shù wèi shén me hěn gū dān',
  '从树上落下来的是什么？': 'cóng shù shang luò xià lái de shì shén me',
  '写错了字，用什么擦掉？': 'xiě cuò le zì yòng shén me cā diào',
  '吐出了雪白雪白的棉花。': 'tǔ chū le xuě bái xuě bái de mián huā',
  '哪个游戏一个人就能玩？': 'nǎ ge yóu xì yí gè rén jiù néng wán',
  '在医院给人看病的是谁？': 'zài yī yuàn gěi rén kàn bìng de shì shuí',
  '在学校门口看门的是谁？': 'zài xué xiào mén kǒu kān mén de shì shuí',
  '大雁排成的字是哪两个？': 'dà yàn pái chéng de zì shì nǎ liǎng gè',
  '小猴子最后带回家什么？': 'xiǎo hóu zi zuì hòu dài huí jiā shén me',
  '小猴子最后追的是什么？': 'xiǎo hóu zi zuì hòu zhuī de shì shén me',
  '小鸭子为什么急得直哭？': 'xiǎo yā zi wèi shén me jí de zhí kū',
  '小鸭子到河里去捉什么？': 'xiǎo yā zi dào hé lǐ qù zhuō shén me',
  '就扔了玉米，去摘桃子。': 'jiù rēng le yù mǐ qù zhāi táo zi',
  '我的小篮子都装不下啦！': 'wǒ de xiǎo lán zi dōu zhuāng bú xià la',
  '村子里原来有没有水井？': 'cūn zi lǐ yuán lái yǒu méi yǒu shuǐ jǐng',
  '水里闷得很，出来透透气': 'shuǐ lǐ mèn de hěn chū lái tòu tòu qì',
  '爸爸晚上拉我去做什么？': 'bà ba wǎn shang lā wǒ qù zuò shén me',
  '瓶子里水不多，瓶口又小': 'píng zi lǐ shuǐ bù duō píng kǒu yòu xiǎo',
  '用手不用脑，会怎么样？': 'yòng shǒu bú yòng nǎo huì zěn me yàng',
  '用来听声音的是哪个字？': 'yòng lái tīng shēng yīn de shì nǎ ge zì',
  '用来看东西的是哪个字？': 'yòng lái kàn dōng xi de shì nǎ ge zì',
  '谁只会捉树干里的害虫？': 'shuí zhǐ huì zhuō shù gàn lǐ de hài chóng',
  '谁只会捉水田里的害虫？': 'shuí zhǐ huì zhuō shuǐ tián lǐ de hài chóng',
  '谁只会捉空中飞的害虫？': 'shuí zhǐ huì zhuō kōng zhōng fēi de hài chóng',
  '跟天气有关的是哪个字？': 'gēn tiān qì yǒu guān de shì nǎ ge zì',
  '跟说话有关的是哪个字？': 'gēn shuō huà yǒu guān de shì nǎ ge zì',
  '雪地里来了一群小画家。': 'xuě dì lǐ lái le yì qún xiǎo huà jiā',
  '雪白的贝壳、青青的小虾': 'xuě bái de bèi ké qīng qīng de xiǎo xiā',
  '鹅的脚掌是什么颜色的？': 'é de jiǎo zhǎng shì shén me yán sè de',
  '《画鸡》写的是什么动物？': 'huà jī xiě de shì shén me dòng wù',
  '《风》这首诗写的是什么？': 'fēng zhè shǒu shī xiě de shì shén me',
  '「严寒」说的是什么时候？': 'yán hán shuō de shì shén me shí hou',
  '「冬雪」说的是哪个季节？': 'dōng xuě shuō de shì nǎ ge jì jié',
  '「夏雨」说的是哪个季节？': 'xià yǔ shuō de shì nǎ ge jì jié',
  '「春风」说的是哪个季节？': 'chūn fēng shuō de shì nǎ ge jì jié',
  '「朝霞」是什么时候的霞？': 'zhāo xiá shì shén me shí hou de xiá',
  '「秋霜」说的是哪个季节？': 'qiū shuāng shuō de shì nǎ ge jì jié',
  '「酷暑」说的是什么时候？': 'kù shǔ shuō de shì shén me shí hou',
  '一二三四五，金木水火土。': 'yī èr sān sì wǔ jīn mù shuǐ huǒ tǔ',
  '一人不成众，独木不成林。': 'yì rén bù chéng zhòng dú mù bù chéng lín',
  '一片片叶子从树上落下来。': 'yí piàn piàn yè zi cóng shù shang luò xià lái',
  '七星瓢虫身上有几个斑点？': 'qī xīng piáo chóng shēn shang yǒu jǐ gè bān diǎn',
  '上学时，书本装在什么里？': 'shàng xué shí shū běn zhuāng zài shén me lǐ',
  '不解藏踪迹，浮萍一道开。': 'bù jiě cáng zōng jì fú píng yí dào kāi',
  '举头望明月，低头思故乡。': 'jǔ tóu wàng míng yuè dī tóu sī gù xiāng',
  '人多的时候，可以玩什么？': 'rén duō de shí hou kě yǐ wán shén me',
  '人有两件宝，双手和大脑。': 'rén yǒu liǎng jiàn bǎo shuāng shǒu hé dà nǎo',
  '众人一条心，黄土变成金。': 'zhòng rén yì tiáo xīn huáng tǔ biàn chéng jīn',
  '元元最后是怎样到学校的？': 'yuán yuán zuì hòu shì zěn yàng dào xué xiào de',
  '元元迟到了，心里怎么样？': 'yuán yuán chí dào le xīn lǐ zěn me yàng',
  '兔子吓了一跳，拔腿就跑。': 'tù zi xià le yí tiào bá tuǐ jiù pǎo',
  '十四是十四，四十是四十。': 'shí sì shì shí sì sì shí shì sì shí',
  '又疑瑶台镜，飞在青云端。': 'yòu yí yáo tái jìng fēi zài qīng yún duān',
  '只在此山中，云深不知处。': 'zhǐ zài cǐ shān zhōng yún shēn bù zhī chù',
  '可我一看窗外心就乱跳……': 'kě wǒ yí kàn chuāng wài xīn jiù luàn tiào',
  '哪个字和心里的感觉有关？': 'nǎ ge zì hé xīn lǐ de gǎn jué yǒu guān',
  '哪个游戏要两个人一起玩？': 'nǎ ge yóu xì yào liǎng gè rén yì qǐ wán',
  '在学校给我们上课的是谁？': 'zài xué xiào gěi wǒ men shàng kè de shì shuí',
  '夏天晚上，点什么赶蚊子？': 'xià tiān wǎn shang diǎn shén me gǎn wén zi',
  '夜来风雨声，花落知多少。': 'yè lái fēng yǔ shēng huā luò zhī duō shǎo',
  '大伙儿最后为什么都笑了？': 'dà huǒ r zuì hòu wèi shén me dōu xiào le',
  '大兴安岭，雪花还在飞舞。': 'dà xīng ān lǐng xuě huā hái zài fēi wǔ',
  '天地分上下，日月照今古。': 'tiān dì fēn shàng xià rì yuè zhào jīn gǔ',
  '天天起得早，陪我去学校。': 'tiān tiān qǐ de zǎo péi wǒ qù xué xiào',
  '妈妈的兄弟，我叫他什么？': 'mā ma de xiōng dì wǒ jiào tā shén me',
  '妈妈的妈妈，我叫她什么？': 'mā ma de mā ma wǒ jiào tā shén me',
  '妈妈的姐妹，我叫她什么？': 'mā ma de jiě mèi wǒ jiào tā shén me',
  '妈妈的爸爸，我叫他什么？': 'mā ma de bà ba wǒ jiào tā shén me',
  '小壁虎的尾巴是怎么断的？': 'xiǎo bì hǔ de wěi ba shì zěn me duàn de',
  '小娃撑小艇，偷采白莲回。': 'xiǎo wá chēng xiǎo tǐng tōu cǎi bái lián huí',
  '小时不识月，呼作白玉盘。': 'xiǎo shí bù shí yuè hū zuò bái yù pán',
  '小溪流说话，哗哗，哗哗。': 'xiǎo xī liú shuō huà huā huā huā huā',
  '小猴子只好空着手回家去。': 'xiǎo hóu zi zhǐ hǎo kōng zhe shǒu huí jiā qù',
  '小白兔向老山羊要了什么？': 'xiǎo bái tù xiàng lǎo shān yáng yào le shén me',
  '小花猫说话，喵喵，喵喵。': 'xiǎo huā māo shuō huà miāo miāo miāo miāo',
  '小雨点说话，沙沙，沙沙。': 'xiǎo yǔ diǎn shuō huà shā shā shā shā',
  '小青蛙说话，呱呱，呱呱。': 'xiǎo qīng wā shuō huà guā guā guā guā',
  '小鸭子让小公鸡坐在哪里？': 'xiǎo yā zi ràng xiǎo gōng jī zuò zài nǎ lǐ',
  '小鸭子说话，嘎嘎，嘎嘎。': 'xiǎo yā zi shuō huà gā gā gā gā',
  '小鸽子说话，咕咕，咕咕。': 'xiǎo gē zi shuō huà gū gū gū gū',
  '就扔了西瓜，去追小兔子。': 'jiù rēng le xī guā qù zhuī xiǎo tù zi',
  '就掰了一个，扛着往前走。': 'jiù bāi le yí gè káng zhe wǎng qián zǒu',
  '床前明月光，疑是地上霜。': 'chuáng qián míng yuè guāng yí shì dì shàng shuāng',
  '我的小书包，宝贝真不少。': 'wǒ de xiǎo shū bāo bǎo bèi zhēn bù shǎo',
  '春去花还在，人来鸟不惊。': 'chūn qù huā hái zài rén lái niǎo bù jīng',
  '春眠不觉晓，处处闻啼鸟。': 'chūn mián bù jué xiǎo chù chù wén tí niǎo',
  '最后，树和喜鹊怎么样了？': 'zuì hòu shù hé xǐ què zěn me yàng le',
  '有雨山戴帽，无雨半山腰。': 'yǒu yǔ shān dài mào wú yǔ bàn shān yāo',
  '朝霞不出门，晚霞行千里。': 'zhāo xiá bù chū mén wǎn xiá xíng qiān lǐ',
  '松下问童子，言师采药去。': 'sōng xià wèn tóng zǐ yán shī cǎi yào qù',
  '树很孤单，喜鹊也很孤单。': 'shù hěn gū dān xǐ què yě hěn gū dān',
  '树很快乐，喜鹊也很快乐。': 'shù hěn kuài lè xǐ què yě hěn kuài lè',
  '江南可采莲，莲叶何田田。': 'jiāng nán kě cǎi lián lián yè hé tián tián',
  '爸爸的妈妈，我叫她什么？': 'bà ba de mā ma wǒ jiào tā shén me',
  '爸爸的姐妹，我叫她什么？': 'bà ba de jiě mèi wǒ jiào tā shén me',
  '爸爸的弟弟，我叫他什么？': 'bà ba de dì di wǒ jiào tā shén me',
  '爸爸的爸爸，我叫他什么？': 'bà ba de bà ba wǒ jiào tā shén me',
  '狐狸说，通知里少了什么？': 'hú li shuō tōng zhī lǐ shǎo le shén me',
  '用手不用脑，事情做不好。': 'yòng shǒu bú yòng nǎo shì qing zuò bù hǎo',
  '用手又用脑，才能怎么样？': 'yòng shǒu yòu yòng nǎo cái néng zěn me yàng',
  '用手又用脑，才能有创造。': 'yòng shǒu yòu yòng nǎo cái néng yǒu chuàng zào',
  '用脑不用手，啥也办不到。': 'yòng nǎo bú yòng shǒu shá yě bàn bú dào',
  '童子说，师父去做什么了？': 'tóng zǐ shuō shī fu qù zuò shén me le',
  '要下雨了，蚂蚁在做什么？': 'yào xià yǔ le mǎ yǐ zài zuò shén me',
  '解落三秋叶，能开二月花。': 'jiě luò sān qiū yè néng kāi èr yuè huā',
  '说自己的时候，用哪个字？': 'shuō zì jǐ de shí hou yòng nǎ ge zì',
  '课文说，一个人玩怎么样？': 'kè wén shuō yí gè rén wán zěn me yàng',
  '谁知盘中餐，粒粒皆辛苦。': 'shuí zhī pán zhōng cān lì lì jiē xīn kǔ',
  '过江千尺浪，入竹万竿斜。': 'guò jiāng qiān chǐ làng rù zhú wàn gān xié',
  '这双小手帮爸爸拿过什么？': 'zhè shuāng xiǎo shǒu bāng bà ba ná guò shén me',
  '这双小手给妈妈洗过什么？': 'zhè shuāng xiǎo shǒu gěi mā ma xǐ guò shén me',
  '远看山有色，近听水无声。': 'yuǎn kàn shān yǒu sè jìn tīng shuǐ wú shēng',
  '铅笔写秃了，用什么削尖？': 'qiān bǐ xiě tū le yòng shén me xiāo jiān',
  '锄禾日当午，汗滴禾下土。': 'chú hé rì dāng wǔ hàn dī hé xià tǔ',
  '长江两岸，柳枝已经发芽。': 'cháng jiāng liǎng àn liǔ zhī yǐ jīng fā yá',
  '雨点儿是从哪里落下来的？': 'yǔ diǎn r shì cóng nǎ lǐ luò xià lái de',
  '雪山上盛开着洁白的雪莲。': 'xuě shān shàng shèng kāi zhe jié bái de xuě lián',
  '风往哪里刮，云往哪里跑。': 'fēng wǎng nǎ lǐ guā yún wǎng nǎ lǐ pǎo',
  '鱼戏莲叶东，鱼戏莲叶西，': 'yú xì lián yè dōng yú xì lián yè xī',
  '鱼戏莲叶南，鱼戏莲叶北。': 'yú xì lián yè nán yú xì lián yè běi',
  '鱼戏莲叶西，鱼戏莲叶南，': 'yú xì lián yè xī yú xì lián yè nán',
  '鹅，鹅，鹅，曲项向天歌。': 'é é é qū xiàng xiàng tiān gē',
  '《静夜思》写的是什么时候？': 'jìng yè sī xiě de shì shén me shí hou',
  '「咕咚」在哪里，你看见了？': 'gū dōng zài nǎ lǐ nǐ kàn jiàn le',
  '「夕阳」是什么时候的太阳？': 'xī yáng shì shén me shí hou de tài yáng',
  '以前，乡亲们到哪里去挑水？': 'yǐ qián xiāng qīn men dào nǎ lǐ qù tiāo shuǐ',
  '十五个吊桶打水——七上八下': 'shí wǔ gè diào tǒng dǎ shuǐ qī shàng bā xià',
  '原来花草都像白天一样微笑。': 'yuán lái huā cǎo dōu xiàng bái tiān yí yàng wēi xiào',
  '只看见闪闪的星星蓝蓝的天。': 'zhǐ kàn jiàn shǎn shǎn de xīng xing lán lán de tiān',
  '哪个字像一棵弯着头的庄稼？': 'nǎ ge zì xiàng yì kē wān zhe tóu de zhuāng jia',
  '大灰狼说，通知里少了什么？': 'dà huī láng shuō tōng zhī lǐ shǎo le shén me',
  '妈妈把勇敢的故事讲了又讲，': 'mā ma bǎ yǒng gǎn de gù shi jiǎng le yòu jiǎng',
  '小公鸡在草地里找到了什么？': 'xiǎo gōng jī zài cǎo dì lǐ zhǎo dào le shén me',
  '小白兔弯着腰在山坡上割草。': 'xiǎo bái tù wān zhe yāo zài shān pō shàng gē cǎo',
  '开出了红的花，长出了绿的草': 'kāi chū le hóng de huā zhǎng chū le lǜ de cǎo',
  '我们在党的怀抱里幸福成长。': 'wǒ men zài dǎng de huái bào lǐ xìng fú chéng zhǎng',
  '我们在谁的怀抱里幸福成长？': 'wǒ men zài shuí de huái bào lǐ xìng fú chéng zhǎng',
  '我对妈妈说，我多想去看看，': 'wǒ duì mā ma shuō wǒ duō xiǎng qù kàn kan',
  '梅花鹿说，通知里少了什么？': 'méi huā lù shuō tōng zhī lǐ shǎo le shén me',
  '每天天一亮，喜鹊们做什么？': 'měi tiān tiān yí liàng xǐ què men zuò shén me',
  '海南岛上，到处盛开着鲜花。': 'hǎi nán dǎo shàng dào chù shèng kāi zhe xiān huā',
  '爸爸看见我来了开心地笑了。': 'bà ba kàn jiàn wǒ lái le kāi xīn de xiào le',
  '瑞金城外有个村子叫沙洲坝，': 'ruì jīn chéng wài yǒu gè cūn zi jiào shā zhōu bà',
  '用来装铅笔、橡皮的是什么？': 'yòng lái zhuāng qiān bǐ xiàng pí de shì shén me',
  '用来说话、吃饭的是哪个字？': 'yòng lái shuō huà chī fàn de shì nǎ ge zì',
  '用来走路、跑步的是哪个字？': 'yòng lái zǒu lù pǎo bù de shì nǎ ge zì',
  '秋天，树叶变成了什么颜色？': 'qiū tiān shù yè biàn chéng le shén me yán sè',
  '粽子是用青青的箬竹叶包的，': 'zòng zi shì yòng qīng qīng de ruò zhú yè bāo de',
  '虫子飞不高，燕子忙着捉虫子': 'chóng zi fēi bù gāo yàn zi máng zhe zhuō chóng zi',
  '诸葛、东方，上官、欧阳……': 'zhū gě dōng fāng shàng guān ōu yáng',
  '《池上》里，小娃偷采了什么？': 'chí shàng lǐ xiǎo wá tōu cǎi le shén me',
  '一只乌鸦口渴了，到处找水喝。': 'yì zhī wū yā kǒu kě le dào chù zhǎo shuǐ hē',
  '两个人甩绳子，其他人做什么？': 'liǎng gè rén shuǎi shéng zi qí tā rén zuò shén me',
  '乌鸦一张嘴唱歌，结果怎么样？': 'wū yā yì zhāng zuǐ chàng gē jié guǒ zěn me yàng',
  '五星红旗的旗面是什么颜色的？': 'wǔ xīng hóng qí de qí miàn shì shén me yán sè de',
  '他顽皮地说：“我就是冬天。”': 'tā wán pí de shuō wǒ jiù shì dōng tiān',
  '半空中，大雨点儿问小雨点儿：': 'bàn kōng zhōng dà yǔ diǎn r wèn xiǎo yǔ diǎn r',
  '哪个字像连在一起的几座高峰？': 'nǎ ge zì xiàng lián zài yì qǐ de jǐ zuò gāo fēng',
  '哪个字说的是我们头顶上面的？': 'nǎ ge zì shuō de shì wǒ men tóu dǐng shàng miàn de',
  '哪个字说的是我们脚下踩着的？': 'nǎ ge zì shuō de shì wǒ men jiǎo xià cǎi zhe de',
  '坐在小小的船里，能看见什么？': 'zuò zài xiǎo xiǎo de chuán lǐ néng kàn jiàn shén me',
  '天安门广场上，什么非常壮观？': 'tiān ān mén guǎng chǎng shàng shén me fēi cháng zhuàng guān',
  '小公鸡和小鸭子一块儿出去玩。': 'xiǎo gōng jī hé xiǎo yā zi yí kuài r chū qù wán',
  '小熊为什么一直不让爸爸砍树？': 'xiǎo xióng wèi shén me yì zhí bú ràng bà ba kǎn shù',
  '小猴子扔了玉米，又去摘什么？': 'xiǎo hóu zi rēng le yù mǐ yòu qù zhāi shén me',
  '小猴子抱着一个大西瓜往回走。': 'xiǎo hóu zi bào zhe yí gè dà xī guā wǎng huí zǒu',
  '小鸭子找不到虫子，急得直哭。': 'xiǎo yā zi zhǎo bú dào chóng zi jí de zhí kū',
  '树有了邻居，喜鹊也有了邻居。': 'shù yǒu le lín jū xǐ què yě yǒu le lín jū',
  '用来拿东西、写字的是哪个字？': 'yòng lái ná dōng xi xiě zì de shì nǎ ge zì',
  '用来量长短、画直线的是什么？': 'yòng lái liáng cháng duǎn huà zhí xiàn de shì shén me',
  '诗人把地上的月光当成了什么？': 'shī rén bǎ dì shang de yuè guāng dàng chéng le shén me',
  '说旁边的另一个人，用哪个字？': 'shuō páng biān de lìng yí gè rén yòng nǎ ge zì',
  '轰隆隆，天空响起了一阵雷声。': 'hōng lōng lōng tiān kōng xiǎng qǐ le yí zhèn léi shēng',
  '「合唱团」唱歌，是哪门课学的？': 'hé chàng tuán chàng gē shì nǎ mén kè xué de',
  '「心」至令人感动——是哪个字？': 'xīn zhì lìng rén gǎn dòng shì nǎ ge zì',
  '「日」出万里无云——是哪个字？': 'rì chū wàn lǐ wú yún shì nǎ ge zì',
  '「水」到纯净透明——是哪个字？': 'shuǐ dào chún jìng tòu míng shì nǎ ge zì',
  '「言」来互相尊重——是哪个字？': 'yán lái hù xiāng zūn zhòng shì nǎ ge zì',
  '只有自己种，才有吃不完的什么？': 'zhǐ yǒu zì jǐ zhòng cái yǒu chī bù wán de shén me',
  '只用了一次，就不知丢到哪里去了': 'zhǐ yòng le yí cì jiù bù zhī diū dào nǎ lǐ qù le',
  '哗，哗，哗，大雨真的下起来了！': 'huā huā huā dà yǔ zhēn de xià qǐ lái le',
  '她多么盼望有医生来给她治病啊！': 'tā duō me pàn wàng yǒu yī shēng lái gěi tā zhì bìng a',
  '晚上的花草像白天一样在做什么？': 'wǎn shang de huā cǎo xiàng bái tiān yí yàng zài zuò shén me',
  '有花有草的地方，后来怎么样了？': 'yǒu huā yǒu cǎo de dì fang hòu lái zěn me yàng le',
  '李老师说，元元迟到了多少分钟？': 'lǐ lǎo shī shuō yuán yuán chí dào le duō shao fēn zhōng',
  '课文里「小小的船」说的是什么？': 'kè wén lǐ xiǎo xiǎo de chuán shuō de shì shén me',
  '谁带领战士和乡亲们挖了一口井？': 'shuí dài lǐng zhàn shì hé xiāng qīn men wā le yì kǒu jǐng',
  '贝贝一回到家，就向妈妈要什么？': 'bèi bèi yì huí dào jiā jiù xiàng mā ma yào shén me',
  '跟别人说话时，叫对方用哪个字？': 'gēn bié rén shuō huà shí jiào duì fāng yòng nǎ ge zì',
  '「地」「尘」「场」都有哪个部件？': 'dì chén chǎng dōu yǒu nǎ ge bù jiàn',
  '「明」「星」「早」都有哪个部件？': 'míng xīng zǎo dōu yǒu nǎ ge bù jiàn',
  '一寸光阴一寸金，寸金难买寸光阴。': 'yí cùn guāng yīn yí cùn jīn cùn jīn nán mǎi cùn guāng yīn',
  '一年之计在于春，一日之计在于晨。': 'yì nián zhī jì zài yú chūn yí rì zhī jì zài yú chén',
  '一片两片三四片，五片六片七八片。': 'yí piàn liǎng piàn sān sì piàn wǔ piàn liù piàn qī bā piàn',
  '九片十片无数片，飞入芦花都不见。': 'jiǔ piàn shí piàn wú shù piàn fēi rù lú huā dōu bú jiàn',
  '人们端午节吃粽子，是为了纪念谁？': 'rén men duān wǔ jié chī zòng zi shì wèi le jì niàn shuí',
  '原来「咕咚」是木瓜掉进湖里的声音': 'yuán lái gū dōng shì mù guā diào jìn hú lǐ de shēng yīn',
  '吃水不忘挖井人，时刻想念毛主席。': 'chī shuǐ bú wàng wā jǐng rén shí kè xiǎng niàn máo zhǔ xí',
  '哪个字像一块块方方正正的庄稼地？': 'nǎ ge zì xiàng yí kuài kuài fāng fāng zhèng zhèng de zhuāng jia dì',
  '哪个字像晚上挂在天上的弯弯小船？': 'nǎ ge zì xiàng wǎn shang guà zài tiān shang de wān wān xiǎo chuán',
  '哪个字像烧得正旺、往上蹿的样子？': 'nǎ ge zì xiàng shāo de zhèng wàng wǎng shàng cuān de yàng zi',
  '头上红冠不用裁，满身雪白走将来。': 'tóu shàng hóng guān bú yòng cái mǎn shēn xuě bái zǒu jiāng lái',
  '妈妈说：“你怎么天天丢东西呢？”': 'mā ma shuō nǐ zěn me tiān tiān diū dōng xi ne',
  '小孩小孩你别馋，过了腊八就是年。': 'xiǎo hái xiǎo hái nǐ bié chán guò le là bā jiù shì nián',
  '小灰兔把白菜吃完了，又去做什么？': 'xiǎo huī tù bǎ bái cài chī wán le yòu qù zuò shén me',
  '小荷才露尖尖角，早有蜻蜓立上头。': 'xiǎo hé cái lù jiān jiān jiǎo zǎo yǒu qīng tíng lì shàng tóu',
  '平生不敢轻言语，一叫千门万户开。': 'píng shēng bù gǎn qīng yán yǔ yí jiào qiān mén wàn hù kāi',
  '影子常常跟着我，就像一条小黑狗。': 'yǐng zi cháng cháng gēn zhe wǒ jiù xiàng yì tiáo xiǎo hēi gǒu',
  '数不清的雨点儿，从云彩里落下来。': 'shǔ bù qīng de yǔ diǎn r cóng yún cai lǐ luò xià lái',
  '明天上午八点，在森林广场开大会，': 'míng tiān shàng wǔ bā diǎn zài sēn lín guǎng chǎng kāi dà huì',
  '李白乘舟将欲行，忽闻岸上踏歌声。': 'lǐ bái chéng zhōu jiāng yù xíng hū wén àn shàng tà gē shēng',
  '桃花潭水深千尺，不及汪伦送我情。': 'táo huā tán shuǐ shēn qiān chǐ bù jí wāng lún sòng wǒ qíng',
  '每天放学的时候，贝贝都要做什么？': 'měi tiān fàng xué de shí hou bèi bèi dōu yào zuò shén me',
  '泉眼无声惜细流，树阴照水爱晴柔。': 'quán yǎn wú shēng xī xì liú shù yīn zhào shuǐ ài qíng róu',
  '浪花挠我的小脚丫，我觉得怎么样？': 'làng huā náo wǒ de xiǎo jiǎo yā wǒ jué de zěn me yàng',
  '浪花看见了，迈着轻轻的步子走来，': 'làng huā kàn jiàn le mài zhe qīng qīng de bù zi zǒu lái',
  '要下雨了，燕子为什么飞得那么低？': 'yào xià yǔ le yàn zi wèi shén me fēi de nà me dī',
  '遥远的北京，有一座雄伟的天安门，': 'yáo yuǎn de běi jīng yǒu yí zuò xióng wěi de tiān ān mén',
  '《小池》里，是谁立在小荷的尖角上？': 'xiǎo chí lǐ shì shuí lì zài xiǎo hé de jiān jiǎo shàng',
  '「松下问童子」，诗人在哪里问童子？': 'sōng xià wèn tóng zǐ shī rén zài nǎ lǐ wèn tóng zǐ',
  '元元刚想走过十字路口，什么灯亮了？': 'yuán yuán gāng xiǎng zǒu guò shí zì lù kǒu shén me dēng liàng le',
  '后来，我在月光下看见小鸟在做什么？': 'hòu lái wǒ zài yuè guāng xià kàn jiàn xiǎo niǎo zài zuò shén me',
  '小公鸡不信，偷偷地跟在小鸭子后面，': 'xiǎo gōng jī bú xìn tōu tōu de gēn zài xiǎo yā zi hòu miàn',
  '小青蛙蹲在荷叶上，呱呱地放声歌唱。': 'xiǎo qīng wā dūn zài hé yè shang guā guā de fàng shēng gē chàng',
  '没有花没有草的地方，后来怎么样了？': 'méi yǒu huā méi yǒu cǎo de dì fang hòu lái zěn me yàng le',
  '要下雨了，小鱼为什么游到水面上来？': 'yào xià yǔ le xiǎo yú wèi shén me yóu dào shuǐ miàn shàng lái',
  '「粒粒皆辛苦」说的是什么得来不容易？': 'lì lì jiē xīn kǔ shuō de shì shén me dé lái bù róng yì',
  '「计算、减法、列算式」是哪门课学的？': 'jì suàn jiǎn fǎ liè suàn shì shì nǎ mén kè xué de',
  '「识字、组词、读课文」是哪门课学的？': 'shí zì zǔ cí dú kè wén shì nǎ mén kè xué de',
  '一个木瓜从高高的树上掉进湖里，咕咚！': 'yí gè mù guā cóng gāo gāo de shù shang diào jìn hú lǐ gū dōng',
  '他看见小鱼摇着尾巴，在河里游来游去。': 'tā kàn jiàn xiǎo yú yáo zhe wěi ba zài hé lǐ yóu lái yóu qù',
  '剥开粽叶，咬一口粽子，真是又黏又甜。': 'bāo kāi zòng yè yǎo yì kǒu zòng zi zhēn shì yòu nián yòu tián',
  '外婆包的粽子，除了红枣粽，还有什么？': 'wài pó bāo de zòng zi chú le hóng zǎo zòng hái yǒu shén me',
  '小水珠躺在荷叶上，眨着亮晶晶的眼睛。': 'xiǎo shuǐ zhū tǎng zài hé yè shang zhǎ zhe liàng jīng jīng de yǎn jing',
  '小猴子捧着几个桃子，走到一片瓜地里。': 'xiǎo hóu zi pěng zhe jǐ gè táo zi zǒu dào yí piàn guā dì lǐ',
  '放进小石子以后，瓶子里的水怎么样了？': 'fàng jìn xiǎo shí zǐ yǐ hòu píng zi lǐ de shuǐ zěn me yàng le',
  '毛主席就带领战士和乡亲们挖了一口井。': 'máo zhǔ xí jiù dài lǐng zhàn shì hé xiāng qīn men wā le yì kǒu jǐng',
  '瓶子里的水渐渐升高，乌鸦就喝着水了。': 'píng zi lǐ de shuǐ jiàn jiàn shēng gāo wū yā jiù hē zháo shuǐ le',
  '舍不得树上的花、叶子、果子和鸟儿的家': 'shě bu de shù shang de huā yè zi guǒ zi hé niǎo er de jiā',
  '铅笔，只用了一次，不知丢到哪里去了。': 'qiān bǐ zhǐ yòng le yí cì bù zhī diū dào nǎ lǐ qù le',
  '「牵牛、织女、北斗星」都是天上的什么？': 'qiān niú zhī nǚ běi dòu xīng dōu shì tiān shang de shén me',
  '叽叽喳喳叫几声，打着招呼一起飞出去了。': 'jī jī zhā zhā jiào jǐ shēng dǎ zhe zhāo hu yì qǐ fēi chū qù le',
  '妈妈说，沿着弯弯的小路，就会走出哪里？': 'mā ma shuō yán zhe wān wān de xiǎo lù jiù huì zǒu chū nǎ lǐ',
  '橡皮，只擦了一回，再想擦，就找不着了。': 'xiàng pí zhǐ cā le yì huí zài xiǎng cā jiù zhǎo bù zháo le',
  '蜻蜓、蝴蝶、蚂蚁这些字，都有什么偏旁？': 'qīng tíng hú dié mǎ yǐ zhè xiē zì dōu yǒu shén me piān páng',
  '人多，什么游戏都能玩，拔河，老鹰捉小鸡，': 'rén duō shén me yóu xì dōu néng wán bá hé lǎo yīng zhuō xiǎo jī',
  '他叹了口气，说：“要是早一分钟就好了。”': 'tā tàn le kǒu qì shuō yào shi zǎo yì fēn zhōng jiù hǎo le',
  '这次，它给我捧来雪白的贝壳、青青的小虾。': 'zhè cì tā gěi wǒ pěng lái xuě bái de bèi ké qīng qīng de xiǎo xiā',
  '不久，有花有草的地方，花更红了，草更绿了。': 'bù jiǔ yǒu huā yǒu cǎo de dì fang huā gèng hóng le cǎo gèng lǜ le',
  '哗哗哗，浪花跑去又跑来，就像淘气的小娃娃。': 'huā huā huā làng huā pǎo qù yòu pǎo lái jiù xiàng táo qì de xiǎo wá wa',
  '狐狸呀，山羊啊，小鹿哇，一个跟着一个跑起来。': 'hú li ya shān yáng a xiǎo lù wa yí gè gēn zhe yí gè pǎo qǐ lái',
  '不久，棉花姑娘的病好了，长出了碧绿碧绿的叶子，': 'bù jiǔ mián huā gū niang de bìng hǎo le zhǎng chū le bì lǜ bì lǜ de yè zi',
  '他看见玉米结得又大又多，非常高兴，就掰了一个，': 'tā kàn jiàn yù mǐ jié de yòu dà yòu duō fēi cháng gāo xìng jiù bāi le yí gè',
  '村子里没有水井，乡亲们吃水要到很远的地方去挑。': 'cūn zi lǐ méi yǒu shuǐ jǐng xiāng qīn men chī shuǐ yào dào hěn yuǎn de dì fang qù tiāo',
  '贝贝想起来了，她书包里的文具盒，就是这些文具的家。': 'bèi bèi xiǎng qǐ lái le tā shū bāo lǐ de wén jù hé jiù shì zhè xiē wén jù de jiā',
  '小公鸡上了岸，笑着对小鸭子说：“鸭子哥哥，谢谢你。”': 'xiǎo gōng jī shàng le àn xiào zhe duì xiǎo yā zi shuō yā zi gē ge xiè xie nǐ',
  '「玉不琢，不成器」说的是：玉石不经过雕琢，就不能成为什么？': 'yù bù zhuó bù chéng qì shuō de shì yù shí bù jīng guò diāo zhuó jiù bù néng chéng wéi shén me',
  '「左边绿，右边红，左右相遇起凉风。绿的喜欢及时雨，红的最怕水来攻。」打一个字': 'zuǒ biān lǜ yòu biān hóng zuǒ yòu xiāng yù qǐ liáng fēng lǜ de xǐ huan jí shí yǔ hóng de zuì pà shuǐ lái gōng dǎ yí gè zì',
}
