// 一年级语文的知识点 / 单元名（英文名 + 中文标题的拼音）：随目录一起加载——地图、页头、对战页、浏览器标题在内容包
// 按需加载之前就要用（engine/catalog.ts 的 loadCourse）。中文标题的单一事实源是 curriculum.ts。
import { registerPinyin, registerTitles } from '@/engine/i18n'
import { KNOWLEDGE_POINTS, UNITS } from './curriculum'

// 知识点 / 单元英文名（中文标题在 curriculum.ts 作单一事实源；拼音课的标题中英一样）
const KP_TITLE_EN: Record<string, string> = {
  'c1s1-01-tiandiren': 'Sky, Earth, People',
  'c1s1-01-jinmu': 'Metal, Wood, Water, Fire, Earth',
  'c1s1-01-kouer': 'Mouth, Ears, Eyes, Hands, Feet',
  'c1s1-01-riyue': 'Sun, Moon, Hills, Rivers',
  'c1s1-01-garden': 'Language Garden 1',
  'c1s1-02-aoe': 'a o e',
  'c1s1-02-iuv': 'i u ü',
  'c1s1-02-bpmf': 'b p m f',
  'c1s1-02-dtnl': 'd t n l',
  'c1s1-02-garden': 'Language Garden 2',
  'c1s1-03-gkh': 'g k h',
  'c1s1-03-jqx': 'j q x',
  'c1s1-03-zcs': 'z c s',
  'c1s1-03-zhchshr': 'zh ch sh r',
  'c1s1-03-yw': 'y w',
  'c1s1-03-garden': 'Language Garden 3',
  'c1s1-04-aieiui': 'ai ei ui',
  'c1s1-04-aoouiu': 'ao ou iu',
  'c1s1-04-ieveer': 'ie üe er',
  'c1s1-04-anen': 'an en in un ün',
  'c1s1-04-angeng': 'ang eng ing ong',
  'c1s1-04-garden': 'Language Garden 4',
  'c1s1-05-qiutian': 'Autumn',
  'c1s1-05-jiangnan': 'South of the River',
  'c1s1-05-huajia': 'Little Painters in the Snow',
  'c1s1-05-siji': 'Four Seasons',
  'c1s1-05-garden': 'Language Garden 5',
  'c1s1-06-duiyun': 'Rhyming Pairs',
  'c1s1-06-riyueming': 'Sun and Moon Make Bright',
  'c1s1-06-shubao': 'My Little Schoolbag',
  'c1s1-06-guoqi': 'Raising the Flag',
  'c1s1-06-garden': 'Language Garden 6',
  'c1s1-07-chuan': 'The Little Boat',
  'c1s1-07-yingzi': 'My Shadow',
  'c1s1-07-liangjianbao': 'Two Treasures',
  'c1s1-07-garden': 'Language Garden 7',
  'c1s1-08-weiba': 'Comparing Tails',
  'c1s1-08-wuya': 'The Crow Drinks Water',
  'c1s1-08-yudian': 'Raindrops',
  'c1s1-08-garden': 'Language Garden 8',
  'c1s2-01-chunxia': 'Spring, Summer, Autumn, Winter',
  'c1s2-01-xingshi': 'Song of Surnames',
  'c1s2-01-qingwa': 'The Little Frog',
  'c1s2-01-caizimi': 'Character Riddles',
  'c1s2-01-garden': 'Language Garden 1',
  'c1s2-02-dang': 'We Love the Communist Party of China',
  'c1s2-02-wajing': 'Remember Who Dug the Well',
  'c1s2-02-kankan': 'How I Wish to Go and See',
  'c1s2-02-garden': 'Language Garden 2',
  'c1s2-03-gongji': 'The Little Rooster and the Duckling',
  'c1s2-03-xique': 'The Tree and the Magpies',
  'c1s2-03-kuaile': 'Fun Every Way',
  'c1s2-03-garden': 'Language Garden 3',
  'c1s2-04-jingyesi': 'Quiet Night Thoughts',
  'c1s2-04-yese': 'Night',
  'c1s2-04-zongzi': 'Dragon Boat Festival Zongzi',
  'c1s2-04-garden': 'Language Garden 4',
  'c1s2-05-dongwu': 'Animal Rhymes',
  'c1s2-05-guduijin': 'Old and New',
  'c1s2-05-caochang': 'On the Playground',
  'c1s2-05-renzhichu': 'At the Beginning of Life',
  'c1s2-05-garden': 'Language Garden 5',
  'c1s2-06-gushi': 'Two Ancient Poems',
  'c1s2-06-langhua': 'The Waves',
  'c1s2-06-heye': 'Round Lotus Leaves',
  'c1s2-06-xiayu': 'It Is Going to Rain',
  'c1s2-06-garden': 'Language Garden 6',
  'c1s2-07-wenju': 'A Home for Stationery',
  'c1s2-07-yifenzhong': 'One Minute',
  'c1s2-07-dahui': 'The Animal Kingdom Meeting',
  'c1s2-07-xiaohouzi': 'The Little Monkey Comes Down the Hill',
  'c1s2-07-garden': 'Language Garden 7',
  'c1s2-08-mianhua': 'Miss Cotton',
  'c1s2-08-gudong': 'Gudong!',
  'c1s2-08-bihu': 'The Little Gecko Borrows a Tail',
  'c1s2-08-garden': 'Language Garden 8',
}

const UNIT_TITLE_EN: Record<string, string> = Object.fromEntries(
  UNITS.map((u) => [u.id, u.title === '识字' ? 'Characters' : u.title === '汉语拼音' ? 'Pinyin' : 'Reading']),
)

registerTitles(
  { zh: Object.fromEntries(KNOWLEDGE_POINTS.map((kp) => [kp.id, kp.title])), en: KP_TITLE_EN },
  { zh: Object.fromEntries(UNITS.map((u) => [u.id, u.title])), en: UNIT_TITLE_EN },
)

// 知识点标题的拼音（练习页页头；拼音课的标题没有汉字，不用注音），与 curriculum.ts 的中文逐字对齐
export const TITLE_PINYIN: Record<string, string> = {
  'kp.c1s1-01-tiandiren': 'tiān dì rén',
  'kp.c1s1-01-jinmu': 'jīn mù shuǐ huǒ tǔ',
  'kp.c1s1-01-kouer': 'kǒu ěr mù shǒu zú',
  'kp.c1s1-01-riyue': 'rì yuè shān chuān',
  'kp.c1s1-01-garden': 'yǔ wén yuán dì yī',
  'kp.c1s1-02-garden': 'yǔ wén yuán dì èr',
  'kp.c1s1-03-garden': 'yǔ wén yuán dì sān',
  'kp.c1s1-04-garden': 'yǔ wén yuán dì sì',
  'kp.c1s1-05-qiutian': 'qiū tiān',
  'kp.c1s1-05-jiangnan': 'jiāng nán',
  'kp.c1s1-05-huajia': 'xuě dì lǐ de xiǎo huà jiā',
  'kp.c1s1-05-siji': 'sì jì',
  'kp.c1s1-05-garden': 'yǔ wén yuán dì wǔ',
  'kp.c1s1-06-duiyun': 'duì yùn gē',
  'kp.c1s1-06-riyueming': 'rì yuè míng',
  'kp.c1s1-06-shubao': 'xiǎo shū bāo',
  'kp.c1s1-06-guoqi': 'shēng guó qí',
  'kp.c1s1-06-garden': 'yǔ wén yuán dì liù',
  'kp.c1s1-07-chuan': 'xiǎo xiǎo de chuán',
  'kp.c1s1-07-yingzi': 'yǐng zi',
  'kp.c1s1-07-liangjianbao': 'liǎng jiàn bǎo',
  'kp.c1s1-07-garden': 'yǔ wén yuán dì qī',
  'kp.c1s1-08-weiba': 'bǐ wěi ba',
  'kp.c1s1-08-wuya': 'wū yā hē shuǐ',
  'kp.c1s1-08-yudian': 'yǔ diǎn r',
  'kp.c1s1-08-garden': 'yǔ wén yuán dì bā',
  'kp.c1s2-01-chunxia': 'chūn xià qiū dōng',
  'kp.c1s2-01-xingshi': 'xìng shì gē',
  'kp.c1s2-01-qingwa': 'xiǎo qīng wā',
  'kp.c1s2-01-caizimi': 'cāi zì mí',
  'kp.c1s2-01-garden': 'yǔ wén yuán dì yī',
  'kp.c1s2-02-dang': 'rè ài zhōng guó gòng chǎn dǎng',
  'kp.c1s2-02-wajing': 'chī shuǐ bú wàng wā jǐng rén',
  'kp.c1s2-02-kankan': 'wǒ duō xiǎng qù kàn kan',
  'kp.c1s2-02-garden': 'yǔ wén yuán dì èr',
  'kp.c1s2-03-gongji': 'xiǎo gōng jī hé xiǎo yā zi',
  'kp.c1s2-03-xique': 'shù hé xǐ què',
  'kp.c1s2-03-kuaile': 'zěn me dōu kuài lè',
  'kp.c1s2-03-garden': 'yǔ wén yuán dì sān',
  'kp.c1s2-04-jingyesi': 'jìng yè sī',
  'kp.c1s2-04-yese': 'yè sè',
  'kp.c1s2-04-zongzi': 'duān wǔ zòng',
  'kp.c1s2-04-garden': 'yǔ wén yuán dì sì',
  'kp.c1s2-05-dongwu': 'dòng wù ér gē',
  'kp.c1s2-05-guduijin': 'gǔ duì jīn',
  'kp.c1s2-05-caochang': 'cāo chǎng shàng',
  'kp.c1s2-05-renzhichu': 'rén zhī chū',
  'kp.c1s2-05-garden': 'yǔ wén yuán dì wǔ',
  'kp.c1s2-06-gushi': 'gǔ shī èr shǒu',
  'kp.c1s2-06-langhua': 'làng huā',
  'kp.c1s2-06-heye': 'hé yè yuán yuán',
  'kp.c1s2-06-xiayu': 'yào xià yǔ le',
  'kp.c1s2-06-garden': 'yǔ wén yuán dì liù',
  'kp.c1s2-07-wenju': 'wén jù de jiā',
  'kp.c1s2-07-yifenzhong': 'yì fēn zhōng',
  'kp.c1s2-07-dahui': 'dòng wù wáng guó kāi dà huì',
  'kp.c1s2-07-xiaohouzi': 'xiǎo hóu zi xià shān',
  'kp.c1s2-07-garden': 'yǔ wén yuán dì qī',
  'kp.c1s2-08-mianhua': 'mián huā gū niang',
  'kp.c1s2-08-gudong': 'gū dōng',
  'kp.c1s2-08-bihu': 'xiǎo bì hǔ jiè wěi ba',
  'kp.c1s2-08-garden': 'yǔ wén yuán dì bā',
}

registerPinyin(TITLE_PINYIN)
