// 三年级数学的知识点 / 单元名（英文名 + 中文标题的拼音）：随目录一起加载——地图、页头、对战页、浏览器标题在内容包
// 按需加载之前就要用（engine/catalog.ts 的 loadCourse）。中文标题的单一事实源是 curriculum.ts。
import { registerPinyin, registerTitles } from '@/engine/i18n'
import { KNOWLEDGE_POINTS, UNITS } from './curriculum'

// 知识点英文名（中文标题在 curriculum.ts 作单一事实源）
export const KP_TITLE_EN: Record<string, string> = {
  'm3s1-01-views': 'Viewing Objects from Different Sides',
  'm3s1-01-guess': 'Guess the Solid',
  'm3s1-01-unfold': 'Cutting Open a Box',
  'm3s1-02-in-order': 'Only + − or Only × ÷',
  'm3s1-02-mul-first': '× ÷ Before + −',
  'm3s1-02-parens': 'Brackets First',
  'm3s1-02-steps': 'Multi-Step Word Problems',
  'm3s1-03-mm-dm': 'Millimeters & Decimeters',
  'm3s1-03-km': 'Kilometers',
  'm3s1-03-choose-unit': 'Estimating Distances',
  'm3s1-03-convert': 'Converting Units of Length',
  'm3s1-04-mass-units': 'Units of Mass',
  'm3s1-04-weighing': 'I Can Weigh Things',
  'm3s1-05-oral-mul': 'Mental Multiplication',
  'm3s1-05-written-mul': 'Written Multiplication',
  'm3s1-05-zero-mul': 'Multiplying with 0',
  'm3s1-05-estimate': 'Estimating Products',
  'm3s1-06-digit-code': 'Number Codes',
  'm3s1-07-lines': 'Line Segments, Rays & Lines',
  'm3s1-07-angles': 'Meet Angles',
  'm3s1-07-angle-kinds': 'Right, Acute & Obtuse Angles',
  'm3s1-08-unit-frac': 'Unit Fractions',
  'm3s1-08-frac': 'Non-Unit Fractions',
  'm3s1-08-frac-calc': 'Adding & Subtracting Fractions',
  'm3s1-08-frac-of-set': 'Fractions of a Group',
  'm3s2-01-symmetry': 'Axial Symmetry',
  'm3s2-01-translate': 'Translation',
  'm3s2-01-rotate': 'Rotation',
  'm3s2-02-oral': 'Mental Division',
  'm3s2-02-written': 'Written Division',
  'm3s2-02-zeros': 'Zeros in the Quotient',
  'm3s2-02-solve': 'Word Problems',
  'm3s2-03-polygons': 'Polygons',
  'm3s2-03-perimeter': 'Perimeter',
  'm3s2-03-puzzle': 'Tetromino Puzzles',
  'm3s2-04-area-units': 'Area & Units of Area',
  'm3s2-04-rect-area': 'Area of Rectangles & Squares',
  'm3s2-04-area-convert': 'Converting Units of Area',
  'm3s2-05-record': 'Collecting & Recording Data',
  'm3s2-05-table': 'Two-Way Tables',
  'm3s2-05-segments': 'Grouping Data into Ranges',
  'm3s2-06-calendar': 'Secrets of the Calendar',
  'm3s2-06-24h': 'Secrets of a Daily Schedule',
  'm3s2-07-know': 'Meet Decimals',
  'm3s2-07-compare': 'Comparing Decimals',
  'm3s2-07-addsub': 'Adding & Subtracting Decimals',
}

export const UNIT_TITLE_EN: Record<string, string> = {
  m3s1u1: 'Observing Objects',
  m3s1u2: 'Mixed Operations',
  m3s1u3: 'Millimeters, Decimeters & Kilometers',
  m3s1u4: 'How Cao Chong Weighed the Elephant',
  m3s1u5: 'Multiplying by a One-Digit Number',
  m3s1u6: 'Number Codes',
  m3s1u7: 'Lines & Angles',
  m3s1u8: 'Meet Fractions',
  m3s2u1: 'Motion Around Us',
  m3s2u2: 'Dividing by a One-Digit Number',
  m3s2u3: 'Rectangles & Squares',
  m3s2u4: 'Area of Shapes',
  m3s2u5: 'Collecting & Organizing Data',
  m3s2u6: 'Secrets of Years, Months & Days',
  m3s2u7: 'Meet Decimals',
}

/** 知识点标题的拼音（练习页页头注音），与 curriculum.ts 的中文标题逐字对齐 */
export const TITLE_PINYIN: Record<string, string> = {
  'kp.m3s1-01-views': 'cóng bù tóng fāng xiàng guān chá wù tǐ',
  'kp.m3s1-01-guess': 'cāi yi cāi shì shén me lì tǐ tú xíng',
  'kp.m3s1-01-unfold': 'jiǎn kāi cháng fāng tǐ zhǐ hé',
  'kp.m3s1-02-in-order': 'zhǐ yǒu jiā jiǎn huò zhǐ yǒu chéng chú',
  'kp.m3s1-02-mul-first': 'xiān chéng chú hòu jiā jiǎn',
  'kp.m3s1-02-parens': 'yǒu kuò hào xiān suàn kuò hào lǐ de',
  'kp.m3s1-02-steps': 'jiě jué duō bù jì suàn de shí jì wèn tí',
  'kp.m3s1-03-mm-dm': 'háo mǐ fēn mǐ de rèn shi',
  'kp.m3s1-03-km': 'qiān mǐ de rèn shi',
  'kp.m3s1-03-choose-unit': 'gū jì jù lí',
  'kp.m3s1-03-convert': 'cháng dù dān wèi de huàn suàn',
  'kp.m3s1-04-mass-units': 'rèn shi zhì liàng dān wèi',
  'kp.m3s1-04-weighing': 'chēng zhòng wǒ hěn xíng',
  'kp.m3s1-05-oral-mul': 'kǒu suàn chéng fǎ',
  'kp.m3s1-05-written-mul': 'bǐ suàn chéng fǎ',
  'kp.m3s1-05-zero-mul': 'yǒu de chéng fǎ',
  'kp.m3s1-05-estimate': 'chéng fǎ gū suàn',
  'kp.m3s1-06-digit-code': 'shù zì biān mǎ',
  'kp.m3s1-07-lines': 'xiàn duàn shè xiàn zhí xiàn',
  'kp.m3s1-07-angles': 'jiǎo de rèn shi',
  'kp.m3s1-07-angle-kinds': 'zhí jiǎo ruì jiǎo dùn jiǎo',
  'kp.m3s1-08-unit-frac': 'jǐ fēn zhī yī',
  'kp.m3s1-08-frac': 'jǐ fēn zhī jǐ',
  'kp.m3s1-08-frac-calc': 'fēn shù de jiǎn dān jì suàn',
  'kp.m3s1-08-frac-of-set': 'jìn yí bù rèn shi fēn shù',
  'kp.m3s2-01-symmetry': 'zhóu duì chèn tú xíng',
  'kp.m3s2-01-translate': 'píng yí',
  'kp.m3s2-01-rotate': 'xuán zhuǎn',
  'kp.m3s2-02-oral': 'kǒu suàn chú fǎ',
  'kp.m3s2-02-written': 'bǐ suàn chú fǎ',
  'kp.m3s2-02-zeros': 'shāng zhōng jiān huò mò wěi yǒu de chú fǎ',
  'kp.m3s2-02-solve': 'jiě jué wèn tí',
  'kp.m3s2-03-polygons': 'duō biān xíng',
  'kp.m3s2-03-perimeter': 'zhōu cháng',
  'kp.m3s2-03-puzzle': 'pīn tú yóu xì',
  'kp.m3s2-04-area-units': 'miàn jī hé miàn jī dān wèi',
  'kp.m3s2-04-rect-area': 'cháng fāng xíng hé zhèng fāng xíng de miàn jī',
  'kp.m3s2-04-area-convert': 'miàn jī dān wèi jiān de jìn lǜ',
  'kp.m3s2-05-record': 'shù jù de shōu jí hé jì lù',
  'kp.m3s2-05-table': 'fù shì tǒng jì biǎo',
  'kp.m3s2-05-segments': 'fēn duàn zhěng lǐ shù jù',
  'kp.m3s2-06-calendar': 'nián lì zhōng de mì mì',
  'kp.m3s2-06-24h': 'zuò xī shí jiān biǎo zhōng de mì mì',
  'kp.m3s2-07-know': 'rèn shi xiǎo shù',
  'kp.m3s2-07-compare': 'xiǎo shù de dà xiǎo bǐ jiào',
  'kp.m3s2-07-addsub': 'jiǎn dān de xiǎo shù jiā jiǎn fǎ',
}

registerTitles(
  { zh: Object.fromEntries(KNOWLEDGE_POINTS.map((kp) => [kp.id, kp.title])), en: KP_TITLE_EN },
  { zh: Object.fromEntries(UNITS.map((u) => [u.id, u.title])), en: UNIT_TITLE_EN },
)
registerPinyin(TITLE_PINYIN)
